### ISSUE TITLE
如果这个两个都传，会有效吗？

### ISSUE THREAD

**Issue by tobycroft** [project-mirai/mirai-api-http#105]
![image](https://user-images.githubusercontent.com/24893075/85107950-60826c80-b241-11ea-9538-ca4b0ea683b6.png)

如果这两个都传一样的内容，然后两个都传，能自动确定对象吗？

**Comment by ryoii** [comment]
临时会话就是通过群聊发起的，向不同群聊的相同一个用户发起临时会话，也是属于不同会话。

`group`和`qq`都要有才能确定一次临时会话

**Comment by tobycroft** [comment]
哦……明白了……这个tempmessage其实就是从群中发出私聊对话，group就是本群的，qq就是对象qq
