### ISSUE TITLE
1.7.2上报还是收不到临时消息

### ISSUE THREAD

**Issue by MatchaC** [project-mirai/mirai-api-http#107]
![图片](https://user-images.githubusercontent.com/45539918/85765681-e83c0f80-b748-11ea-9933-c41abf6c04c2.png)
可以看到console里打印了临时消息
但是上报这边只收到了好友消息和群消息
![图片](https://user-images.githubusercontent.com/45539918/85766001-381ad680-b749-11ea-8711-e78af27c2eed.png)

**Comment by MatchaC** [comment]
不好意思，昨天换了miraiOK，Jar包还是旧的，1.7.2测试了没问题

**Comment by IMNOTHD** [comment]
我也用miraiOK遇到了这个问题，请问是怎么解决的

**Comment by MatchaC** [comment]
> 
> 
> 我也用miraiOK遇到了这个问题，请问是怎么解决的

更新下HTTP API的jar包

**Comment by IMNOTHD** [comment]
> > 我也用miraiOK遇到了这个问题，请问是怎么解决的
> 
> 更新下HTTP API的jar包

我现在使用的是https://github.com/project-mirai/mirai-api-http/actions/runs/150199654中的包，依旧收不到
mirai-console-0.5.2.jar，mirai-core-qqandroid-1.0.2.jar
是不是console的core太旧的问题？
