### ISSUE TITLE
通过/resp/newFriendRequestEvent接口拒绝好友申请时设置message字段无效

### ISSUE THREAD

**Issue by MatchaC** [project-mirai/mirai-api-http#108]
![图片](https://user-images.githubusercontent.com/45539918/85840121-87efb100-b7ce-11ea-96b1-5cbba84305e9.png)
收到的回复为空值
版本1.7.2

**Comment by ryoii** [comment]
mamoe/mirai#393

**Comment by ryoii** [comment]
这个功能在mirai还没有实现，考虑日后会实现，所以http-api预留了接口
