### ISSUE TITLE
{"code":3,"msg":"Session失效或不存在"}

### ISSUE THREAD

**Issue by Fcatme** [project-mirai/mirai-api-http#109]
按照默认配置方式或者自己设置更改后再或者是直接不设置由插件随机生成 去验证就会出现Session失效或不存在。
参考了之前issues 《authKey 为数字时bug》使用authKey: '1234567890'，作为字符串处理
还是依旧提醒这个。。有点迷

**Comment by ryoii** [comment]
没有遇到这个问题，请检查程序是否有错。
比较可能的原因的请求头有误

**Comment by Fcatme** [comment]
我直接用浏览器打开 http://0.0.0.0:8080/friendList?sessionKey=1234567890

**Comment by ryoii** [comment]
我猜你把验证Key当作会话Key了，一个是`authKey`一个是`sessionKey`，留意区分

**Comment by Fcatme** [comment]
那能不能后续 所有 API 都支持GET和POST ，以及sessionKey 能够在默认设置里面直接设置好
非常适合我这样的懒狗..

**Comment by ryoii** [comment]
> 那能不能后续 所有 API 都支持GET和POST ，以及sessionKey 能够在默认设置里面直接设置好
> 非常适合我这样的懒狗..

验证key是设置好的，会话key设置好了怎么识别一个具体的bot呢。大部分接口需要复杂的消息体，使用GET请求不现实
