### ISSUE TITLE
事件接口过于玄幻了

### ISSUE THREAD

**Issue by tobycroft** [project-mirai/mirai-api-http#111]
名字 | 类型 | 说明
-- | -- | --
eventId | Long | 事件标识，响应该事件时的标识
fromId | Long | 申请人QQ号
groupId | Long | 申请人申请入群的群号
groupName | String | 申请人申请入群的群名称
nick | String | 申请人的昵称或群名片
message | String | 申请消息

我在想我同意别人加群为什么要填写本群的群名称啊……
不是只要通过这个id就行了吗？

https://github.com/project-mirai/mirai-api-http/blob/master/EventType.md

这个文档写的实在是不好理解

通过了为什么还要传群名=。=如果通过的时候要设定用户群名片我能理解，如果这里能设定群名……这就有点理解不能了

**Comment by ryoii** [comment]
首先这些字段在事件里都有，你填上不需要多大成本。
其次，设计这些字段是因为真实发包的时候确实有这些字段。
最后，你可以尝试填空值，也是有可能可以成功的

**Comment by tobycroft** [comment]
其实我发现这块的提交比较奇怪，有一部分是需要填写群名称的，还有一些就是同意eventid和groupid的，这块确实不知道为什么同一个接口有两种请求方法，另外加上文档没有返回值所以不知道接口的执行目的是什么（##打的太小了，不能区分，看起来上下相连，看着很乱

**Comment by ryoii** [comment]
我一度怀疑自己看错自己写的代码了。
文档里写的针对这种事件有两部分：
1. 第一部分是是携带了事件信息的，也就是你说的带了“群名称”的一部分，这个是由mirai返回的事件结构
2. 第二部分是响应`resp`的api，这里没有一个接口是带了所谓的“名称”的，所需要的都是重要的事件id和对应群号和QQ号的信息

请仔细阅读
