### ISSUE TITLE
[功能请求] 通过 HTTP POST 上报消息并支持筛选后上报

### ISSUE THREAD

**Issue by Nutr1t07** [project-mirai/mirai-api-http#12]
在配置文件中指定一个上报的URL，将 mirai 收到的事件以 JSON 格式表示通过 HTTP POST 上报到该地址上。

**Comment by Chenwe-i-lin** [comment]
没有必要, 已经有了 HTTP 短轮询和 websocket, 完全不需要 mirai-api-http 再为上报消息创造一种新的方式.

**Comment by Nutr1t07** [comment]
> 没有必要, 已经有了 HTTP 短轮询和 websocket

这两种通信方式确实在大多数情况下能够解决问题，但当我需要快速测试或者只需要部分使用mirai的功能(而不是完整地实现一个SDK)时，用HTTP POST上报会节省很多时间。但如您所说，这并非是一个必需的通信方式， _HTTP 短轮询和 websocket_ 在多数场景下是完全足够的。

> 完全不需要 mirai-api-http 再为上报消息创造一种新的方式

您可以将它作为一个次要的功能，并没有要求它在短期内上线。但如前所述，它并不是一个”完全不需要“的功能。

**Comment by Chenwe-i-lin** [comment]
@ryoii 我建议将这个功能置为 `To Do(Secondary)`

**Comment by copydog** [comment]
@Chenwe-i-lin POST通知 事件/消息和POST心跳，不出意外近期会上线

**Comment by Chenwe-i-lin** [comment]
求求你饶了我吧

**Comment by copydog** [comment]
@Chenwe-i-lin 没事，我来写

**Comment by Chenwe-i-lin** [comment]
心跳是怎么设计的?

**Comment by copydog** [comment]
心跳就是定时发送api-http所有使用的robot的信息发送到指定地址。

**Comment by Chenwe-i-lin** [comment]
能不能让调用 api 的这端获取这些信息?

**Comment by Tarocch1** [comment]
建议支持对数据进行筛选后上报，筛选可以使用json schema这类标准方案，也可以像cqhttp一样自己造轮子。

**Comment by copydog** [comment]
@Tarocch1 
即将支持筛选后，发送到多个postUrl
因为筛选过程有一定量的计算，我觉得应该不会同一个消息，进行多次不同的筛选后分别发送到不同postUrl。

**Comment by Tarocch1** [comment]
@copydog 只要筛选条件足够细致，这样我觉得也是完全可以接受的。
