### ISSUE TITLE
有没有办法让server默认使用utf8编码？

### ISSUE THREAD

**Issue by zYeoman** [project-mirai/mirai-api-http#121]
背景：准备在游戏mod里用，但是mod里的网络函数并不支持设置header。

代码需要改什么地方么？我可以自己改改看

**Comment by ryoii** [comment]
Close via 8add26b

**Comment by zYeoman** [comment]
> Close via [8add26b](https://github.com/project-mirai/mirai-api-http/commit/8add26bf1ece4f755a3b1a2389a8edc8afb816d1)

能在README里加上怎么build的信息么？尝试自己gradle build，结果 NoClassDefFoundError

**Comment by ryoii** [comment]
Github Action里有构建
