### ISSUE TITLE
無法獲得Bot收到的消息

### ISSUE THREAD

**Issue by BeautyYuYanli** [project-mirai/mirai-api-http#122]
當我嘗試
```
GET /fetchLatestMessage?sessionKey=8UfJvIfU&count=10 HTTP/1.1
Host: 0.0.0.0:8080
```
得到了一個空的回覆
```
{
"code": 0,
"errorMessage": "",
"data":[]
}
```
使用`fetchMessage`和`peekLatestMessage`的情況與上述相同。使用`peekMessage`則返回了`404`

**Comment by Chenwe-i-lin** [comment]
你开了websocket.

**Comment by BeautyYuYanli** [comment]
我使用的是[Talend API Tester](https://www.talend.com/)。另外，[該文檔](https://github.com/project-mirai/mirai-api-http/blob/master/API-Tester/install.md)所提供的配置文件已經`404`了

**Comment by BeautyYuYanli** [comment]
確實。
