### ISSUE TITLE
接收不到临时会话消息

### ISSUE THREAD

**Issue by southsaucedsk** [project-mirai/mirai-api-http#124]
插件本地调试可以正常接收到临时会话消息
放到服务器上后能正常接收群组消息和好友消息但是接收不到临时会话消息
两边系统都是win10
jdk版本对比 本地1.8.0_131 服务器  1.8.0_251
使用miraiOk一键开启
mirai-console-wrapper 版本1.3.0
http-api插件版本1.7.0 最新版也测试过 同样的问题
同时也发现服务器上miraiOk不能自动登录 本地可以自动登录 不确定是不是相同的原因

**Comment by ryoii** [comment]
测试无异常
