### ISSUE TITLE
回复中文的时候得到的是乱码

### ISSUE THREAD

**Issue by 851248662** [project-mirai/mirai-api-http#125]
使用的是
https://github.com/LXY1226/miraiOK
一键启动

使用的http插件的版本
{
    "code": 0,
    "errorMessage": "",
    "data": {
        "version": "v1.7.0"
    }
}

发送的请求
127.0.0.1:8080/sendFriendMessage

Content-Type application/json
charset utf-8
{
    "sessionKey": "iSrilaOQ",
    "target": 851248662,
    "messageChain": [
        { "type": "Plain", "text":"66卡了6666\n" },
        { "type": "Plain", "text":"world" }
    ]
}

但是得到的乱码
![image](https://user-images.githubusercontent.com/61673908/88372481-8e227e80-cdc8-11ea-8fd6-dc96e4c651a2.png)

**Comment by 851248662** [comment]
收到的消息是

66å¡äº6666
world

**Comment by ryoii** [comment]
#102 

善用搜索
