### ISSUE TITLE
用户入群申请 MemberJoinRequestEvent 失效

### ISSUE THREAD

**Issue by Andy-shi001** [project-mirai/mirai-api-http#128]
mirai-api-http [ws] /all?sessionKey=YourSessionKey 监听该接口，插件将推送Bot收到的事件和消息  监听失效无任何反应

**Comment by ryoii** [comment]
确认bot是管理员

**Comment by Andy-shi001** [comment]
只有超级管理员收到验证信息,机器人bot是管理员，收不到任何信息，MemberJoinRequestEvent也监控不到

**Comment by Andy-shi001** [comment]
![image](https://user-images.githubusercontent.com/68884928/89383134-8cdd4400-d72e-11ea-8818-890a1d4cfddd.png)
试了多次，机器人是管理员，申请入群，还是监听不到，还有什么处理方式可以解决？
