### ISSUE TITLE
[功能请求] 更加完善的 demo 和快速使用方法？

### ISSUE THREAD

**Issue by StringKe** [project-mirai/mirai-api-http#129]
http api 更快速的使用方式

使用 swagger 可以生成 openapi 的配置文件

通过这个配置文件可以导入大部分的测试工具接口调试工具 比如 postman apifox paw 等等

甚至还可以使用 [openapi-generator](https://github.com/OpenAPITools/openapi-generator) 这样的项目直接生成对应语言需要的 httpapi 代码封装

**Comment by daofeng2015** [comment]
readme中不是有吗？
