### ISSUE TITLE
成员被踢出群 MemberLeaveEventKick 和 成员主动离群MemberLeaveEventQuit监听不到

### ISSUE THREAD

**Issue by Andy-shi001** [project-mirai/mirai-api-http#130]
![image](https://user-images.githubusercontent.com/68884928/88996088-e43e7700-d31e-11ea-9dcd-9e8d7e929e8c.png)
使用Websocket  
监听该接口，插件将推送Bot收到的事件 [ws] /event?sessionKey=YourSessionKey
监听该接口，插件将推送Bot收到的事件和消息 [ws] /all?sessionKey=YourSessionKey
成员主动退群后监听不到事件

**Comment by Andy-shi001** [comment]
![image](https://user-images.githubusercontent.com/68884928/89005164-625a4800-d336-11ea-91e8-21f9988d1b4d.png)  重新开启会更新 mirai-core-qqandroid-1.1.3.jar，退群事件失效

**Comment by Andy-shi001** [comment]
![image](https://user-images.githubusercontent.com/68884928/89005308-afd6b500-d336-11ea-923c-abf88322d8d8.png)

**Comment by Andy-shi001** [comment]
![image](https://user-images.githubusercontent.com/68884928/89013455-7f971280-d346-11ea-938f-e0e3eec81a5f.png)

**Comment by ryoii** [comment]
应该是 `mirai-core` 的问题，请将 issue 迁移到 `mirai-core` 仓库

**Comment by Andy-shi001** [comment]
> issue 迁移到 `mirai-core` 仓库

之前是可以监控到，现在退群监控不到，现在mirai-core不是不维护了吗？那怎么弄
