### ISSUE TITLE
QQ群中以下信息目前获取不到

### ISSUE THREAD

**Issue by apuded** [project-mirai/mirai-api-http#134]
QQ群中无法获取某个发言用户的以下资料：
nickname：QQ网名（非群名片）
level：群中等级（如：冒泡）
性别
年龄
地区

翻看了下mirai-api-http文档，好像目前版本并不支持这些基本信息（原来在酷q中能获取到）。
如果说法有误，请纠正，谢谢。

**Comment by ryoii** [comment]
你是对的
