### ISSUE TITLE
获取不到入群公告更改的事件 GroupEntranceAnnouncementChangeEvent

### ISSUE THREAD

**Issue by xian18** [project-mirai/mirai-api-http#139]
由其他管理修改入群公告后 没有触发 GroupEntranceAnnouncementChangeEvent 这个事件.
只收到了一个GroupMessage 事件, 其中的 messageChain 有App类型的消息,包含部分与公告有关的消息.
`
{
    "app":"com.tencent.mannounce",
    "config":{
        "ctime":1597929078,
        "forward":0,
        "token":"106bae0b19c3588586297b**********"
    },
    "desc":"群公告",
    "extra":{
        "app_type":1,
        "appid":1101236949
    },
    "meta":{
        "mannounce":{
            "cr":0,
            "encode":1,
            "fid":"e5de892b0000000076763e**********",
            "gc":"730455781",
            "sign":"992904f19a19f19419a422**********",
            "text":"77yf77yf77yf",
            "title":"576k5YWs5ZGK",
            "tw":1,
            "uin":"1010******"
        }
    },
    "prompt":"[群公告]？？？",
    "ver":"1.0.0.43",
    "view":"main"
}
`

**Comment by ryoii** [comment]
提供各软件版本号

**Comment by xian18** [comment]
使用 Mirai-N启动.
mirai-console-wapper-1.3.0
mirai-console-0.5.2
mirai-core-qqandroid-1.2.2
mirai-api-http-v1.8.0
也收不到其他人更改群名称的事件

**Comment by ryoii** [comment]
事件在Console里面都是有日志的，如果没有显示日志，就是 `mirai-core` 的  bug。麻烦确认一下

**Comment by xian18** [comment]
![此处应有图片](https://raw.githubusercontent.com/xian18/First/master/sendpix3.jpg)
这个截图?我没看出来啥事件.

**Comment by xian18** [comment]
![此处为截图](https://raw.githubusercontent.com/xian18/First/c30387baa7be6ceb7cb9ae35a42207790f2f262e/sendpix3.jpg)
发公告的截图就这些.我没看出来,不知道有没有事件

**Comment by ryoii** [comment]
建议在 mirai-core 中重开 issue，这个应该是那边的问题
