### ISSUE TITLE
踢群人员后，报错！！

### ISSUE THREAD

**Issue by Andy-shi001** [project-mirai/mirai-api-http#140]
![image](https://user-images.githubusercontent.com/68884928/91028221-bd2e4900-e62f-11ea-91d9-d2e3a75bcbf5.png)

**Comment by Andy-shi001** [comment]
![image](https://user-images.githubusercontent.com/68884928/91153532-ea8ffb00-e6f2-11ea-8ada-704f19317376.png)

**Comment by ryoii** [comment]
这个issue麻烦开到mira主仓库，是core的问题。
携带core版本号
