### ISSUE TITLE
messageId为-1 ， 发不出群消息

### ISSUE THREAD

**Issue by zhuting233** [project-mirai/mirai-api-http#141]
{"code":0,"msg":"success","messageId":-1}

**Comment by z924263634** [comment]
可以分享一下jar包吗，我的打包一直有问题

**Comment by ryoii** [comment]
提供各软件版本号

**Comment by lydrainbowcat** [comment]
1.7.4 + core 1.1.3 + console 0.5.2
遇到了同样的问题

**Comment by ryoii** [comment]
先更新到最新

**Comment by tonyfcw** [comment]
我也遇到了相同的问题，目前通过验证返回值，messageID为-1时重新发送的方式解决的
出现的场合比较随机，有时候5条消息里面1条有这个情况

**Comment by zer0e** [comment]
我也遇到了这种情况，我以为是长度问题，但是测试之后发现好像就是特定的信息发不出去，尝试多少次都发不出去。

**Comment by zer0e** [comment]
我也遇到了这种情况，测试之后发现好像就是特定的信息发不出去，尝试多少次都发不出去。
目前确定就是中文问题，转成bytes发送可以。

**Comment by ryoii** [comment]
应该是 core 造成的，确实存在发不出消息的问题。留意 mirai core 的相关issue

**Comment by Brioal** [comment]
> 我也遇到了这种情况，测试之后发现好像就是特定的信息发不出去，尝试多少次都发不出去。
> 目前确定就是中文问题，转成bytes发送可以。

你好，转成bytes是指的啥操作能说一下吗，没找到文档

**Comment by zer0e** [comment]
> > 我也遇到了这种情况，测试之后发现好像就是特定的信息发不出去，尝试多少次都发不出去。
> > 目前确定就是中文问题，转成bytes发送可以。
> 
> 你好，转成bytes是指的啥操作能说一下吗，没找到文档

str.encode()，时间太长不记得了，应该是把中文转义了。

**Comment by JiuLER** [comment]
请问现在有解决方案了吗，，，
