### ISSUE TITLE
修改群设置anonymousChat不允许匿名聊天 无效！

### ISSUE THREAD

**Issue by Andy-shi001** [project-mirai/mirai-api-http#142]
![image](https://user-images.githubusercontent.com/68884928/91380799-71aab380-e858-11ea-8f53-48e140e5a6dd.png)
![image](https://user-images.githubusercontent.com/68884928/91380942-c3533e00-e858-11ea-82f3-076b4b296004.png)

**Comment by z924263634** [comment]
可以分享一下jar包吗，我的打包一直有问题

**Comment by ryoii** [comment]
提供各软件版本号

**Comment by ryoii** [comment]
mirai-core 里有类似issue
