### ISSUE TITLE
发不出群消息

### ISSUE THREAD

**Issue by Ren-Pen** [project-mirai/mirai-api-http#144]
大概运行了半天，突然就无法发送群消息了，返回的messageId为-1
但是可以正常的接收消息
这种情况出现了两次，都是在长时间（大概有半天以上）后出现的
在miraiOK的控制台上显示有[BOT xxx] Group(xxx) <- xxx 的，就是群里没有收到消息
每次在重启miraiOK后会恢复正常

运行的版本：
mirai-core-qqandroid-1.2.2
mirai-console-0.5.2
mirai-api-http-v1.8.0

**Comment by ryoii** [comment]
关注#141
