### ISSUE TITLE
无法在消息中任意位置使用表情

### ISSUE THREAD

**Issue by Williamsunsir** [project-mirai/mirai-api-http#147]
举个例子：
感谢您使用本服务群[玫瑰]
![image](https://user-images.githubusercontent.com/48049042/91787680-00467880-ec3d-11ea-939a-f9503154257f.png)
然后就变成了图中所示

**Comment by ryoii** [comment]
带上版本号，提供原消息

**Comment by Williamsunsir** [comment]
v1.7.4 
我看到文档中提供另一种方式，在消息链中添加表情这种方法
但是，我需要在消息中的任意位置插入一个表情，有些不方便，以下是原始消息：

@$_1Q84 
------------------
标题: 
下载地址：http://new66.net/s/qXLi5K

感谢您使用本服务群[玫瑰]

**Comment by ryoii** [comment]
从来没有通过模板字符串插入表情的方式
你可以按顺序写入每一种消息类型或者自行实现模板解析

**Comment by Williamsunsir** [comment]
好的，了解
