### ISSUE TITLE
提示图片上传成功并生成imageId但是图裂/无限加载/404

### ISSUE THREAD

**Issue by wywzxxz** [project-mirai/mirai-api-http#149]
这是引发错误的最小代码：
```
import aiohttp
from io import BytesIO,StringIO
async def uploadImage(path):
    clt=aiohttp.ClientSession()
    with open(path,"rb") as f:
        response = await clt.post("http://127.0.0.1:9011/uploadImage",
                     data={"sessionKey":sessionKey,"type":"friend","img":BytesIO(f.read())}
                     )     
    res=await response.json()
    await clt.close()
    return res
a=await uploadImage("test.png")
print(a)
```
运行结果：

> {'imageId': '/18446744072954363817-178843023-C8D021B4AC7FDABBB4942B5FD489A126', 'url': 'http://c2cpicdw.qpic.cn/offpic_new/3539779497//18446744072954363817-178843023-C8D021B4AC7FDABBB4942B5FD489A126/0?term=2', 'path': '/mnt/wuyuewan/odtest/eftnn/mirai/plugins/MiraiAPIHTTP/images/img'}

对应服务端结果：
![image](https://user-images.githubusercontent.com/5335612/92083815-20bb3200-edf9-11ea-8d3c-76df77461eb6.png)

问题：
直接使用该ImageId发送图片，显示图裂或者无限载入
浏览器直接访问url（例如：http://c2cpicdw.qpic.cn/offpic_new/3539779497//18446744072954363817-178843023-C8D021B4AC7FDABBB4942B5FD489A126/0?term=2）显示404
![image](https://user-images.githubusercontent.com/5335612/92084997-c91dc600-edfa-11ea-9595-603e4fe7cad7.png)
![image](https://user-images.githubusercontent.com/5335612/92085034-d20e9780-edfa-11ea-83c5-454d29439062.png)

尝试定位问题得到的一些结论：
- [X] 手动可以正常发图
- [X] 使用已有ImageId(来自发送的消息)可以正常发图 
- [X] 使用已有ImageId可以拼凑出浏览器可以访问的url
- [X] 服务端`MiraiAPIHTTP/images/img`这个图片缓存是正常的，加上图片后缀就能正常浏览
- [X] 大小格式无关，10K还是1M、png还是jpeg的图片结果都一样

再往下...再往下，救救孩子，孩子不会JAVA……
![image](https://user-images.githubusercontent.com/5335612/92084588-3715bd80-edfa-11ea-8415-fd048ec192ba.png)

>miraiOK启动
>mirai-api-http：1.7.3 & 1.7.4
>mirai-console：0.5.2
>mirai-core-qqandroid：1.0.3

**Comment by Executor-Cheng** [comment]
我用自己的sdk测了下v1.7.4的api, 没发现啥问题
建议你用个fd啥的把请求内容贴出来看看
![1](https://user-images.githubusercontent.com/27953325/92091777-cd021600-ee03-11ea-987f-cff624420cfa.png)

**Comment by wywzxxz** [comment]
抓包和进java对我来说有点难……
不过我注意到另外一个时期：我获得的imageId似乎不大对劲
我手动生成的、以及2楼截图中显示的imageId第一位应当是QQ号,例如：
> /**872637398**-4048454786-CA7E04E7AC5BCC77C71B30B5803CA565/0?term=2
 
/**<QQ号>**-4048454786-CA7E04E7AC5BCC77C71B30B5803CA565/0?term=2
而我得到的ImageId第一位特别长，显然不可能是QQ号
>/18446744072954363817-3979934208-C8D021B4AC7FDABBB4942B5FD489A126

因此我测试了下不同的type参数，发现三个type分别为：
friend:'/18446744072954363817-3979934208-C8D021B4AC7FDABBB4942B5FD489A126'
temp  :'/18446744072954363817-2433088883-C8D021B4AC7FDABBB4942B5FD489A126'
group :'{C8D021B4-AC7F-DABB-B494-2B5FD489A126}.mirai'

其中，group消息发送成功了：
![image](https://user-images.githubusercontent.com/5335612/92102029-967ec800-ee10-11ea-94d4-c1600497ea8b.png)
所以看样子，可能因为什么原因Friend type生成了本应当是temp type的ImageId……

我本来是怎么想的，但是又试了一下Friend图片上传，结果突然发现发出去了，而且也是类似temp的ImageId……
>http://c2cpicdw.qpic.cn/offpic_new/3539779497//18446744072954363817-1225786086-BDDAF2C8E6800191F7FC37C07E3D955D/0?term=2

所以问题解决了……虽然我也不知道到底发生了什么……
![image](https://user-images.githubusercontent.com/5335612/92102595-64219a80-ee11-11ea-8788-cc8fe8a99faf.png)
谢谢啦～

**Comment by yooziki** [comment]
我也遇见了同样的问题，但是看见你的描述我还是不太明白最后是如何去解决它的
请问可以更详细的讲解一下吗，十分感谢！

**Comment by wywzxxz** [comment]
> 我也遇见了同样的问题，但是看见你的描述我还是不太明白最后是如何去解决它的
> 请问可以更详细的讲解一下吗，十分感谢！

Hi！总结成一句话，我没动它它自己好了……
