### ISSUE TITLE
当数据请求量大时,使用websocket获取消息有延迟问题,而且会随着时间递增

### ISSUE THREAD

**Issue by liushaocong** [project-mirai/mirai-api-http#153]
<img width="398" alt="屏幕快照 2020-09-08 上午10 12 05" src="https://user-images.githubusercontent.com/29514866/92426202-e7e5d900-f1bb-11ea-9796-4c2704488f7c.png">
刚刚挂了大概十几分钟，本地的时间是2020-09-08 10:12分,接收到的消息时间戳是1599530854,对应的时间是2020-09-08 10:07:34,相差了5分钟，而且挂的时间越长,延迟会越来越大

**Comment by ryoii** [comment]
没有收到类似的反馈，考虑SDK的问题
