### ISSUE TITLE
[功能请求]图片消息的path可不可以支持绝对路径

### ISSUE THREAD

**Issue by fyr233** [project-mirai/mirai-api-http#172]
https://github.com/fyr233/mirai-api-http/blob/master/MessageType.md#image

**Comment by HoshinoTented** [comment]
图片信息首先要通过 `/uploadImage` 上传到 MiraiApiHttp 的图片目录，随后再通过相对路径发送

**Comment by Hieuzest** [comment]
原本就支持（file:///）
~~再通过相对路径发送~~再通过imageId发送
