### ISSUE TITLE
console中显示发送成功 但是qq群并没有收到信息

### ISSUE THREAD

**Issue by ddgth** [project-mirai/mirai-api-http#175]
console中显示发送成功 但是qq群并没有收到信息 messageId=-1
mirai-console-1.0-M4.jar
mirai-console-pure-1.0-M4.jar
mirai-core-qqandroid-1.3.0.jar
mirai-api-http-v1.8.3

**Comment by Karlatemp** [comment]
发送内容是什么，使用的账号可能进入了风控，请尝试等会再发送一次

**Comment by ddgth** [comment]
> 发送内容是什么，使用的账号可能进入了风控，请尝试等会再发送一次

感谢回复 大概率是被风控了  我是用国外小鸡登录的 挂了半天陆续收到消息了
