### ISSUE TITLE
建议加入对Mirai码的支持

### ISSUE THREAD

**Issue by drsanwujiang** [project-mirai/mirai-api-http#177]
```
{
    "sessionKey": "Session",
    "target": 12345678,
    "messageChain": [
        {
            "type": "Plain",
            "text": "不太行[mirai:face:123]"
        }
    ]
}
```
直接在Plain Message里使用并没有效果

**Comment by HoshinoTented** [comment]
read [this](https://github.com/project-mirai/mirai-api-http/blob/master/MessageType.md#face)

**Comment by drsanwujiang** [comment]
> read [this](https://github.com/project-mirai/mirai-api-http/blob/master/MessageType.md#face)

消息链中使用确实没问题，但是不能在PlainText中用的话，感觉没什么意义？

**Comment by HoshinoTented** [comment]
PlainText 意为 **纯** 文本，其中所有内容都会被当作原生字符串，没有特殊的意思。
因此在 PlainText 中用 mirai code 是违背 PlainText 的设计目标的。

**Comment by drsanwujiang** [comment]
> PlainText 意为 **纯** 文本，其中所有内容都会被当作原生字符串，没有特殊的意思。
> 因此在 PlainText 中用 mirai code 是违背 PlainText 的设计目标的。

但是 Mirai 码是字符串，这么看来目前在 Mirai API HTTP 里并没有能使用 Mirai 码的地方？

**Comment by HoshinoTented** [comment]
目前没有实现这种功能

**Comment by drsanwujiang** [comment]
> 目前没有实现这种功能

好的，感谢回复！

**Comment by ryoii** [comment]
Mirai码消息作为一种独立的消息类型，与现有消息类型区分

**Comment by Wybxc** [comment]
可以把 mirai-core 的 `MiraiCode.deserializeFromMiraiCode` 这些也做成 API，这样用起来方便一点
