### ISSUE TITLE
仅能收到一次 BotInvitedJoinGroupRequestEvent 事件

### ISSUE THREAD

**Issue by vivien8261** [project-mirai/mirai-api-http#179]
mirai-console 和 mirai-api-http 均为最新版本。使用的是 miraiOK 一键包。

每次重启 console 并登陆后，貌似不单只 BotInvitedJoinGroupRequestEvent，请求类事件都只能收到一次，并且收到后任何请求类事件都不会再触发。

顺便说一个特殊情况，被 QQ 好友强制拉进群和通过拉好友建群的方式都不会触发 BotJoinGroupEvent。

上述问题不一定是 mirai-api-http 的问题，也许是 console 导致的，因为 console 在控制台输出的 log 里也没有出现相应的记录。
因为我不是 JVM 开发者所以没去研究 console，抱歉。

希望能解答上述情况，谢谢！^_^

**Comment by HoshinoTented** [comment]
@ryoii 元芳，你怎么看

**Comment by vivien8261** [comment]
上面描述有误，不是 MemberJoinEvent 而是 BotJoinGroupEvent，已修改

**Comment by ryoii** [comment]
控制台没有日志数据，基本可以认为是 core 的问题，建议将 issue 开到 core 项目下
RequestEvent 只触发一次是正常的，触发多次才是不正常吧

**Comment by vivien8261** [comment]
> 控制台没有日志数据，基本可以认为是 core 的问题，建议将 issue 开到 core 项目下
> RequestEvent 只触发一次是正常的，触发多次才是不正常吧

可能我没有表述清楚，问题的场景是：用户A邀请了机器人进群，机器人同意后，用户B、用户C邀请机器人时，机器人已经没办法收到请求了，也就是这个问题不是针对单个用户的，而是机器人在每次重启的生命周期内只能收到一次请求

**Comment by ryoii** [comment]
留意 core 的相关 issue
