### ISSUE TITLE
能不能在码云上也部署一个

### ISSUE THREAD

**Issue by worst001** [project-mirai/mirai-api-http#180]
console、qqandroid、console-terminal单独下载最新的包需要翻墙，可能是我vpn搭的不好，速度非常慢。

**Comment by HoshinoTented** [comment]
可以使用 [mirai-console-loader](https://github.com/iTXTech/mirai-console-loader)

**Comment by HoshinoTented** [comment]
I afraid not.

**Comment by worst001** [comment]
其实粮食自己留一份比较好，不怕一万就怕万一。
