### ISSUE TITLE
在Centos7x64环境下，部署会出现中文全变问号

### ISSUE THREAD

**Issue by Superexboom** [project-mirai/mirai-api-http#181]
环境 Centos7 x64
使用最新的miraiok开启
尝试更换过另一台也是跑centos7的主机，依旧乱码
在自己的电脑上用win的miraiok开，无乱码现象
不明是linux下的问题还是miraiok的问题

最开始运行时无乱码，到了http声明模块状态的时候，中文就开始变成问号了
后续能够正常登陆，但是所有q群的消息 只要是中文的就变成问号了
也无法响应中文指令，英文指令可以响应
望开发者关注下 谢谢

**Comment by ryoii** [comment]
检查 centos 系统十分安装的中文语言包，编码乱码不会出现全问号的乱码，缺少字体比较合理

**Comment by Superexboom** [comment]
这点忘记在描述中写上了，已经全部看过了，改成中文utf-8或者GBK，都是一样的乱码，至于字体我已经把电脑上中文字体都搬过去了，依旧问号

**Comment by Karlatemp** [comment]
请认真检查, `CentOS Linux release 8.2.2004 (Core) ` 并没有问题
![0](https://user-images.githubusercontent.com/30070303/94356501-ed9b5400-00c1-11eb-8fd2-99e433e22418.png)
![1](https://user-images.githubusercontent.com/30070303/94356502-effdae00-00c1-11eb-9477-9f061602d66b.png)

**Comment by Superexboom** [comment]
> 请认真检查, `CentOS Linux release 8.2.2004 (Core) ` 并没有问题
> ![0](https://user-images.githubusercontent.com/30070303/94356501-ed9b5400-00c1-11eb-8fd2-99e433e22418.png)
> ![1](https://user-images.githubusercontent.com/30070303/94356502-effdae00-00c1-11eb-9477-9f061602d66b.png)

挺坏的，能否提供下当前所安装的字体列表？我想对照下看看我是否还有遗漏的

**Comment by Karlatemp** [comment]
center OS 8，安装语言为中文，未安装额外字体





---原始邮件---
发件人: "Superexboom"<notifications@github.com&gt;
发送时间: 2020年9月27日(周日) 下午2:28
收件人: "project-mirai/mirai-api-http"<mirai-api-http@noreply.github.com&gt;;
抄送: "Comment"<comment@noreply.github.com&gt;;"Karlatemp"<karlatemp@vip.qq.com&gt;;
主题: Re: [project-mirai/mirai-api-http] 在Centos7x64环境下，部署会出现中文全变问号 (#181)




  
请认真检查, CentOS Linux release 8.2.2004 (Core)  并没有问题
 
 
  
挺坏的，能否提供下当前所安装的字体列表？我想对照下看看我是否还有遗漏的

**Comment by Superexboom** [comment]
![QQ截图20200927144352](https://user-images.githubusercontent.com/54000348/94357987-280bed80-00d0-11eb-8eb1-753158c3f7a6.jpg)
我群内也有个人装的也是centos 8， 但是他也出现了中文全变问号的问题
然后为了避免遗漏 这次我把所有的字体文件都丢上去装了
结果依旧如上，到声明这步，就开始全变问号了

**Comment by Karlatemp** [comment]
![Z](https://user-images.githubusercontent.com/30070303/94362423-be9ad780-00ed-11eb-80ad-b5722528fcbe.png)
请确认是否存在 -Dfile.encoding 之类的参数. 并且尝试直接启动console, 不借助任何工具

**Comment by Karlatemp** [comment]
ssh也没有任何问题
![97C](https://user-images.githubusercontent.com/30070303/94362487-379a2f00-00ee-11eb-99d7-670e73be02d7.png)

**Comment by Superexboom** [comment]
再确认下环境上的区别， 都是当前最新的miraiok吗？
本人lib版本:
mirai-console-1.0-M4
mirai-console-pure-1.0-M4
mirai-core-qqandroid-1.2.3

**Comment by Karlatemp** [comment]
```
[karlatemp@kasuku mirai]$ ls libs
mirai-console-1.0-M4.jar  mirai-console-pure-1.0-M4.jar  mirai-core-qqandroid-1.2.3.jar
````
并没有使用Mirai-OK, 而是直接命令行启动

**Comment by Superexboom** [comment]
![QQ截图20200927190956](https://user-images.githubusercontent.com/54000348/94363493-0c670e00-00f5-11eb-804f-df8699d2b333.jpg)
这次不使用miraiok开，乱码的不是问号 反而是不可识别的了

**Comment by Superexboom** [comment]
好了，改回去en_US.UTF-8就正常显示了，谢谢各位！
已能正常使用了
