### ISSUE TITLE
transferTo这个异常是缺少依赖包吗

### ISSUE THREAD

**Issue by worst001** [project-mirai/mirai-api-http#183]
不太会java和kotlin，但是这个项目我非常喜欢。我在配置了jdk和maven后，已经运行了console生成了plugin文件夹，现在想把mirai-api-http的jar包加进去，但在编译的时侯抛了如下异常，如何解决这个问题。

` mirai-api-http (master) ✗ ./gradlew

> Configure project :mirai-api-http
e: /Users/hanwenhao/Github/mirai-api-http/mirai-api-http/build.gradle.kts:152:30: Unresolved reference: transferTo

FAILURE: Build failed with an exception.

* Where:
Build file '/Users/hanwenhao/Github/mirai-api-http/mirai-api-http/build.gradle.kts' line: 152

* What went wrong:
Script compilation error:

  Line 152:                             .transferTo(File("$testConsoleDir/plugins/${it.name}").apply { createNewFile() }
                                         ^ Unresolved reference: transferTo`

**Comment by Itsusinn** [comment]
transferTo是java9还是10以后的特性来着

**Comment by HoshinoTented** [comment]
请使用 jdk11

**Comment by worst001** [comment]
> 请使用 jdk11

谢谢已经成功
