### ISSUE TITLE
功能请求：戳一戳

### ISSUE THREAD

**Issue by purofle** [project-mirai/mirai-api-http#189]

**Comment by HoshinoTented** [comment]
![image](https://user-images.githubusercontent.com/25280943/95306177-a4b17f80-08b9-11eb-8ec0-6201d92943d4.png)

**Comment by HoshinoTented** [comment]
如果是双击头像的戳一戳，目前还没加

**Comment by purofle** [comment]
> 如果是双击头像的戳一戳，目前还没加

就是这个（

**Comment by ForeverOpp** [comment]
[9月就加了吧](https://github.com/project-mirai/mirai-api-http/blob/master/docs/MessageType.md#poke)

**Comment by zmdyy0318** [comment]
同请求戳一戳

**Comment by crab-in-the-northeast** [comment]
铜球

**Comment by Doctor-Yin** [comment]
将于1.9.9加入

**Comment by crab-in-the-northeast** [comment]
> 将于1.9.9加入

好耶！
