### ISSUE TITLE
文件消息接收不到

### ISSUE THREAD

**Issue by Williamsunsir** [project-mirai/mirai-api-http#193]
文件消息接收不到
返回的消息为：
{'type': 'GroupRecallEvent', 'authorId': 3318xxxx, 'messageId': 8745, 'time': 26820, 'group': {'id': 34286xxx, 'name': '-----', 'permission': 'MEMBER'}, 'operator': {'id': 3318xxxx, 'memberName': 'xxx', 'permission': 'MEMBER', 'group': {'id': 34286xxxx, 'name': '-----', 'permission': 'MEMBER'}}}

**Comment by ryoii** [comment]
没有支持文件消息

**Comment by Williamsunsir** [comment]
感谢
