### ISSUE TITLE
阅读文档时配置文件中的 `destinations` 这个配置项有点没明白

### ISSUE THREAD

**Issue by XSun771** [project-mirai/mirai-api-http#195]
首先感谢作者的工作。

文档中关于  setting.yml 的设置，对消息上报下的上报URLs  `destinations`  有些困惑：
（1）如果 `enableWebsocket` 已经设置为 `true`，则是否还需要设置 `destinations` 为 `['/message?sessionKey=YourSessionKey']` ？
（2）如果 `enableWebsocket`  设置为 false，即不开启 websocket，但在 `destinations`  中有有效的值比如 `['/miral/message']` ，那么 mirai-api-http 一旦接收到合适的消息，会立刻自动使用 HTTP 协议向这个 url 提交 HTTP 报文？

谢谢

**Comment by HoshinoTented** [comment]
第一个问题我不知道。
第二个问题：有效的值一般是有效的服务器地址（至少一般不会发到本地），当 mirai-api-http (mah) 收到 **事件** 后，会根据配置文件中的配置决定是否上报（消息也算是一种事件）

**Comment by XSun771** [comment]
> 第一个问题我不知道。
> 第二个问题：有效的值一般是有效的服务器地址（至少一般不会发到本地），当 mirai-api-http (mah) 收到 **事件** 后，会根据配置文件中的配置决定是否上报（消息也算是一种事件）

感谢你的回答。

第一个问题你也不知道是什么情况，你不是作者吗。是我问题没有表达清楚吗？
第二个问题：如果mirai和后端的java web程序运行在同一主机上，java web 程序监听 'localhost:8080/message`，那这里 destinations 该填写 `http://localhost:8080/message` 吗？这样填写之后，mirai 收到消息会立刻通过 http 报文将消息内容和相关信息上报给 `/message` ？

就是这个上报机制该如何配置能否在文档里更进一步说明一下？

谢谢

**Comment by HoshinoTented** [comment]
第一个问题：我不是主要作者。
第二个问题：是的。

**Comment by ryoii** [comment]
这个问题取决于你的使用场景，websocket服务和上报服务是两个独立的模块
对于问题一，websocket不论是否开启，如果需要使用到上报服务，`destinations` 就是必选的，内容为消息上报的地址。

如果单纯在本地进行跨进程通信，建议只使用websocket功能，而关闭上报服务。上报服务是一方面是作为没有反向websocket的补充，另一方面是对没有主动通信功能系统的一种妥协处理

**Comment by XSun771** [comment]
> 第一个问题：我不是主要作者。
> 第二个问题：是的。



> 这个问题取决于你的使用场景，websocket服务和上报服务是两个独立的模块
> 对于问题一，websocket不论是否开启，如果需要使用到上报服务，`destinations` 就是必选的，内容为消息上报的地址。
> 
> 如果单纯在本地进行跨进程通信，建议只使用websocket功能，而关闭上报服务。上报服务是一方面是作为没有反向websocket的补充，另一方面是对没有主动通信功能系统的一种妥协处理

感谢两位解答。我试了下事件上报，成功用 java 程序收到和解析了消息。

但 websocket 模块虽然启动，监听 `/message` 却并没有收到任何信息。请问启动 websocket 模块的话，是 mirai 起到一个 websocket 服务端的作用？是在之前的获取 sessionKey 的过程中建立起来的 websocket ？

我这边 Java 程序监听 `/message` 不够，必须要监听 `/message?sessionKey=my-sessionKey` ？可是这个 my-sessionKey 要 Java 程序运行起来才能获得，Spring web 程序开发的话一般是基于注解在运行前指定好要监听的接口的地址，运行后直接监听。如果是这么操作的话我不知道该怎么弄。两位有相关经验吗？

谢谢

**Comment by XSun771** [comment]
> 第一个问题：我不是主要作者。
> 第二个问题：是的。



> 这个问题取决于你的使用场景，websocket服务和上报服务是两个独立的模块
> 对于问题一，websocket不论是否开启，如果需要使用到上报服务，`destinations` 就是必选的，内容为消息上报的地址。
> 
> 如果单纯在本地进行跨进程通信，建议只使用websocket功能，而关闭上报服务。上报服务是一方面是作为没有反向websocket的补充，另一方面是对没有主动通信功能系统的一种妥协处理

感谢两位解答。我试了下事件上报，成功用 java 程序收到和解析了消息。

但 websocket 模块虽然启动，监听 `/message` 却并没有收到任何信息。请问启动 websocket 模块的话，是 mirai 起到一个 websocket 服务端的作用？是在之前的获取 sessionKey 的过程中建立起来的 websocket ？

我这边 Java 程序监听 `/message` 不够，必须要监听 `/message?sessionKey=my-sessionKey` ？可是这个 my-sessionKey 要 Java 程序运行起来才能获得，Spring web 程序开发的话一般是基于注解在运行前指定好要监听的接口的地址，运行后直接监听。如果是这么操作的话我不知道该怎么弄。两位有相关经验吗？

谢谢

**Comment by ryoii** [comment]
拦截器和延迟注入，必要的话可以介入bean的构造流程再注入到容器。这已经属于Spring的问题了
