### ISSUE TITLE
mirai-api-http 中上报服务应为默认关闭

### ISSUE THREAD

**Issue by ryoii** [project-mirai/mirai-api-http#196]
mirai-api-http 中上报服务应为默认关闭，现为默认开启。心跳服务同。

net/mamoe/mirai/api/http/config/Setting.kt:39

net/mamoe/mirai/api/http/config/Setting.kt:60

**Comment by HoshinoTented** [comment]
那你倒是改啊

**Comment by Karlatemp** [comment]
那你倒是改啊
