### ISSUE TITLE
sendGroupMessage 接口发不出消息，返回“指定对象不存在”

### ISSUE THREAD

**Issue by changechenhao** [project-mirai/mirai-api-http#197]
auth、verify都成功了，但sendGroupMessage 接口总数返回：
`{"code":5,"msg":"指定对象不存在"}`
换群号发，或者换成QQ好友接口发也都发不出去，都返回上述错误

**Comment by ryoii** [comment]
请提供发送内容

**Comment by changechenhao** [comment]
@ryoii 发送内容很简单，例如：“test1”

**Comment by HoshinoTented** [comment]
发送内容指的是：你发送的 HTTP 请求的内容，而不是消息内容

**Comment by changechenhao** [comment]
问题解决了。新建的QQ号，必须得先数据验证码，然后根据返回的url手机扫码登录，后续在登录就不会有这个问题了

**Comment by 1135890950** [comment]
> 问题解决了。新建的QQ号，必须得先数据验证码，然后根据返回的url手机扫码登录，后续在登录就不会有这个问题了

大佬，我也遇到了这个问题，不过我的QQ号不是新建的，我就按正常流程登录，验证，和你一样的提示，你这个是怎么搞的？

**Comment by cl-ei** [comment]
> 

同问，我也遇到这个问题，怎么解决？

**Comment by Ljzd-PRO** [comment]
@cl-ei @1135890950 我是登陆以后会弹窗，里面有一个链接，把链接复制到浏览器打开，会看到滑动验证，拉一下滑动条验证一下然关闭弹窗就可以了。之后我记得还会有个弹窗要求输入短信验证码，输入以后按要求操作就可以了
