### ISSUE TITLE
fetchMessage 无法获取到机器人自己发出去的消息

### ISSUE THREAD

**Issue by HertzHz** [project-mirai/mirai-api-http#204]
如题

**Comment by HertzHz** [comment]
而且 fetchMessage 也没有 messageId，无法对消息进行撤回

**Comment by ryoii** [comment]
bot发的消息不会添加到缓存中，fetchMessage是获取不到的。否则很容易导致bot处理自己的消息导致各种死循环。
撤回消息时使用的messageId可以通过发送消息接口的返回值撤回。撤回其他人发送的消息可以通过message中source对象的messageId撤回

**Comment by HertzHz** [comment]
source的messageId好像不通用还是咋的，和doc里的messageId差的有点大（个位数，看起来是个递增计数器），撤回给了个错误码5
bot发的消息现在是完全没办法获取到吗？

**Comment by ryoii** [comment]
Bot自己发过什么消息自己是知道的吧，为什么还要依赖这个来获取bot发过的消息

**Comment by HertzHz** [comment]
Bot 人类同号就有这种需求
