### ISSUE TITLE
自动审批和匿名聊天设置失效

### ISSUE THREAD

**Issue by 2659494057** [project-mirai/mirai-api-http#209]
返回成功状态码，实际没有生效

**Comment by ryoii** [comment]
这两个设置在 `mirai core` 中是不可变的，也就是并没有实现修改的协议

你可以阅读本仓库的源码 `mirai-api-http/mirai-api-http/src/main/kotlin/net/mamoe/mirai/api/http/route/GroupManageRouteModule.kt:L98:L99
