### ISSUE TITLE
上报失败

### ISSUE THREAD

**Issue by lun324** [project-mirai/mirai-api-http#210]
2020-11-09 12:38:47 E/MiraiApiHttp: 上报https失败: Client request(http://localhost/https) invalid: 403 Forbidden

mirai-console-1.0-M4
mirai-console-terminal-1.0-RC-dev-28
mirai-core-qqandroid-1.2.3

设置应该没有错吧
![image](https://user-images.githubusercontent.com/9657304/98500971-dcc92b00-2288-11eb-88de-fb4805597ad9.png)

**Comment by lun324** [comment]
![image](https://user-images.githubusercontent.com/9657304/98501420-1fd7ce00-228a-11eb-94cc-ccfc96472c65.png)

**Comment by HoshinoTented** [comment]
尝试在目标地址的前面加上 `http://`？

**Comment by HoshinoTented** [comment]
我什么都不懂，我是垃圾 @ryoii

**Comment by HoshinoTented** [comment]
试试：`destinations: ["api.sddd2d. .... /report"]`？
我不是很懂 yaml 的格式。

**Comment by ryoii** [comment]
鉴于长时间没有回复，关闭此`issue`
