### ISSUE TITLE
使用path参数发送图片或语音时，实际引用路径与文档不符

### ISSUE THREAD

**Issue by siooooooon** [project-mirai/mirai-api-http#211]
文档路径：plugins/MiraiAPIHTTP/images ✗

实际路径：data/MiraiApiHttp/images ✓

语音同上

**Comment by ryoii** [comment]
感谢发现这个问题，这个变更是 `console`  升级后将 `plugin` 目录和 `data` 目录区分导致的。使用不同版本的 `console` 会产生不同的表现，请留意。
