### ISSUE TITLE
群员进入事件(MemberJoinEvent)没法接收

### ISSUE THREAD

**Issue by kamaellee** [project-mirai/mirai-api-http#213]
通过Talend API Tester测试过，群员退出事件(MemberLeaveEvent)可以接收,但群员进入事件没法接收。

求修复，大大辛苦了。

**Comment by kamaellee** [comment]
环境补充：
mirai-api-http-v1.8.4
mirai-console-1.0-M4
mirai-console-terminal-1.0-RC-dev-28
mirai-core-qqandroid-1.2.3

**Comment by kamaellee** [comment]
测试后附加：
转换成 mirai-console-pure-1.0-M4 后问题解决，不知道terminal什么问题了。
但群里有兄弟说隔一段时间后还是会收不到，重启才能收到，晚点测试后补充

**Comment by ryoii** [comment]
这属于 `mirai-core` 的问题，`mirai` 仓库 `issue` 列表可以搜索到类似问题
