### ISSUE TITLE
Mirai-api-http 2.0 提案征集

### ISSUE THREAD

**Issue by ryoii** [project-mirai/mirai-api-http#215]
`mirai-console` 1.0.0版本发布在即，`mirai-api-http` 为了适配新版 `mirai-console` 在做大量兼容的同时，也同时进行基础功能的重写。

`mirai-api-http` 2.0 期望解决随 `mirai-core` 一直升级以来导致的一些不合理的设计，并引入更规范、更高效的接口设计。特此征集提案。

> 随后1.x 版本的`mirai-api-http` 不会再升级兼容更新版本的 `mirai-console`，将停留在 `1.0.0-M1` 的版本支持

**Comment by HoshinoTented** [comment]
好，很有精神！

**Comment by Karlatemp** [comment]
好，很有精神！

**Comment by drsanwujiang** [comment]
好，很有精神！

**Comment by KawaiiZapic** [comment]
~~可以先照着`go-cqhttp`把合理的API全给实现了  
再把反向ws给安排上~~

**Comment by ryoii** [comment]
反向ws可以有，但是啥合理的API需求？

**Comment by KawaiiZapic** [comment]
> 反向ws可以有，但是啥合理的API需求？

合理的API需求指的是`go-cqhttp`已经实现并且可以在这个项目里也能实现并且确实有意义的, 就像消息合并转发之类的.  
具体哪些合理还得靠开发者自己估摸了.  
  
我想表达的意思是可以照`go-cqhttp`已经实现的API为模板去拓展自己的API,里面很多API都是这个项目使用者(至少是我)所需要的.

**Comment by HoshinoTented** [comment]
数据的结构希望能和 core 的保持一致

**Comment by ryoii** [comment]
> 数据的结构希望能和 core 的保持一致

就消息和事件而言，大部分一致吧

**Comment by stepheny** [comment]
是否可以考虑使用JSON-RPC封装包括认证、校验的所有api调用？
若可行的话，是否可以考虑进一步扩大websocket的功能？
比如通过ws调用认证与会话成功后，可将对应权限与ws连接绑定，客户端发向服务端的文本帧都视为api调用。通过api调用设置当前会话是否通过该连接通知消息和或事件。（也许可以增加事件类型的分类过滤，但似乎并不必要）
对于小体积的多媒体内容是否可以使用二进制帧跟随对应请求的文本帧发送上传？（对于可能超过ws单帧大小的文件可以引入分片机制）

**Comment by KawaiiZapic** [comment]
想到了就提一句.  
在新的MiraiConsole里已经实现了很多有关权限和指令的API,可以在mah里添加一些新的接口去调用这些API.  
具体不知道,但是增查删改权限应该会有吧(大概

**Comment by HoshinoTented** [comment]
> 想到了就提一句.
> 在新的MiraiConsole里已经实现了很多有关权限和指令的API,可以在mah里添加一些新的接口去调用这些API.
> 具体不知道,但是增查删改权限应该会有吧(大概

感觉这已经超越 mah 所管理的范畴了，如果需要，个人觉得不如搞个 mcah

**Comment by KawaiiZapic** [comment]
> > 想到了就提一句.
> > 在新的MiraiConsole里已经实现了很多有关权限和指令的API,可以在mah里添加一些新的接口去调用这些API.
> > 具体不知道,但是增查删改权限应该会有吧(大概
> 
> 感觉这已经超越 mah 所管理的范畴了，如果需要，个人觉得不如搞个 mcah

mah已经实现了一部分command的功能,我认为再把权限之类的一些api整合进来是有必要的.
或者直接把权限和指令部分剥离出mah再像你所说的弄一个mcah

**Comment by GreyElaina** [comment]
你能把 core 能用的功能都做出来我就感恩戴德了。。。

**Comment by HoshinoTented** [comment]
你能把 core 能用的功能都做出来我就感恩戴德了。。。

**Comment by Karlatemp** [comment]
你能把 core 能用的功能都做出来我就感恩戴德了。。。

**Comment by sywee** [comment]
想问一下，mirai-api-http 如果发送群消息时@全体成员？感谢

**Comment by zmdyy0318** [comment]
支持mirai-console-loader加载。每次更新手动下载好麻烦啊

**Comment by PeratX** [comment]
> 支持mirai-console-loader自动下载。每次更新手动下载好麻烦啊。

已经支持了。

**Comment by StageGuard** [comment]
z? 什么时候更新

**Comment by ryoii** [comment]
写好的时候更新

**Comment by CharlieYu4994** [comment]
很想知道，改完会和现在的 API 差距很大嘛

**Comment by ryoii** [comment]
> 很想知道，改完会和现在的 API 差距很大嘛

可大可不大，计划实现多种样式的接口类型。其中会保留旧接口的适配器。

**Comment by CharlieYu4994** [comment]
> > 很想知道，改完会和现在的 API 差距很大嘛
> 
> 可大可不大，计划实现多种样式的接口类型。其中会保留旧接口的适配器。

那太好了ฅ^•ﻌ•^ฅ

**Comment by BlueGlassBlock** [comment]
能否使用类似于Base64一类的格式上传小体积的多媒体内容，以避免每次上传临时图片（由程序生成的）都需要手动跟踪、删除文件？

**Comment by xiyuesaves** [comment]
请问下能否支持商城表情?或者是支持的只是我没找到?

**Comment by Minepig** [comment]
请求支持消息类型：**合并转发**、**商城表情**、音乐分享、链接分享、短视频、群文件（不是接收群文件，就给一个群文件的消息类型，用于标识这条消息是群文件）
请求支持API：**增加/删除群管理员**、发送群内拍一拍（双击头像）
请求支持事件：收到群内拍一拍（双击头像）
请求支持其他内容：支持amr格式以外的语音文件

**Comment by Minepig** [comment]
> 请求支持消息类型：**合并转发**、**商城表情**、音乐分享、链接分享、短视频、群文件（不是接收群文件，就给一个群文件的消息类型，用于标识这条消息是群文件）
> 请求支持API：**增加/删除群管理员**、发送群内拍一拍（双击头像）
> 请求支持事件：收到群内拍一拍（双击头像）
> 请求支持其他内容：支持amr格式以外的语音文件

消息类型这一块总之最好把mirai产生的各种类型的mirai码都支持一下，要不然后端记录到的消息常常和mirai前端不一致

**Comment by Drincann** [comment]
希望 `GET /memberList` 的元素和 `GET /memberInfo` 能具有相似的返回结构。

目前前者的结构

```ts
interface MemberInfo {
    id: number;
    name: string;
    permission: string;
}
```

而后者的结构

```ts
interface MemberInfo {
    name: string;
    title: string;
}
```

做类型声明的时候感觉有点别扭。

**Comment by Sunbread** [comment]
请求支持获取群成员的入群时间和最后发言时间。

**Comment by HoshinoTented** [comment]
> 希望 `GET /memberList` 的元素和 `GET /memberInfo` 能具有相似的返回结构。
> 
> 目前前者的结构
> 
> ```ts
> interface MemberInfo {
>     id: number;
>     name: string;
>     permission: string;
> }
> ```
> 
> 而后者的结构
> 
> ```ts
> interface MemberInfo {
>     name: string;
>     title: string;
> }
> ```
> 
> 做类型声明的时候感觉有点别扭。

memberList 的元素应该不是 Info

**Comment by Asyfish** [comment]
希望支持配置**事件上报时是否监听返回内容并解析**，两个服务器都在自己手中的时候应该没有啥安全问题，可以不要session，用单次链接完成上报-回复的过程，节省了开销，响应也更快。

**Comment by VirFunc** [comment]
最近刚开始用mirai，在搓request和response的时候发现几个问题
1.  request的数据传递方式
现有api中大部分的都将sessionKey，target等信息放在json里发送，但是又有一部分api将这些信息放在了url里。例如[撤回](https://github.com/project-mirai/mirai-api-http/blob/master/docs/API.md#%E6%92%A4%E5%9B%9E%E6%B6%88%E6%81%AF)和[获取群员资料](https://github.com/project-mirai/mirai-api-http/blob/master/docs/API.md#%E8%8E%B7%E5%8F%96%E7%BE%A4%E5%91%98%E8%B5%84%E6%96%99)
2. 统一response中status code和msg信息
一部分api的响应中包含code和msg，另一部分却不包含。

个人认为这两点的设计应该更统一 一点，不知道各位大佬怎么想
|･ω･` )希望有大佬看见了踢我一下

**Comment by Drincann** [comment]
> 最近刚开始用mirai，在搓request和response的时候发现几个问题
> 
> 1. request的数据传递方式
>    现有api中大部分的都将sessionKey，target等信息放在json里发送，但是又有一部分api将这些信息放在了url里。例如[撤回](https://github.com/project-mirai/mirai-api-http/blob/master/docs/API.md#%E6%92%A4%E5%9B%9E%E6%B6%88%E6%81%AF)和[获取群员资料](https://github.com/project-mirai/mirai-api-http/blob/master/docs/API.md#%E8%8E%B7%E5%8F%96%E7%BE%A4%E5%91%98%E8%B5%84%E6%96%99)
> 2. 统一response中status code和msg信息
>    一部分api的响应中包含code和msg，另一部分却不包含。
> 
> 个人认为这两点的设计应该更统一 一点，不知道各位大佬怎么想
> |･ω･` )希望有大佬看见了踢我一下

放 url 里的是 GET

**Comment by VirFunc** [comment]
@Drincann 啊确实，是我没有仔细看

**Comment by xwh1108** [comment]
希望增加登陆验证相关api,方便进行多账号的可视化管理(控制台虽好,但是门槛略高)

**Comment by ryoii** [comment]
> 希望增加登陆验证相关api,方便进行多账号的可视化管理(控制台虽好,但是门槛略高)

从插件角度来实现这个不太合适，而且涉及很多 `多阶段提交` 的问题，接口的表达能力有限。感觉你比较想要的是一个能提供 http 接口的 console 前端

**Comment by xwh1108** [comment]
> > 希望增加登陆验证相关api,方便进行多账号的可视化管理(控制台虽好,但是门槛略高)
> 
> 从插件角度来实现这个不太合适，而且涉及很多 `多阶段提交` 的问题，接口的表达能力有限。感觉你比较想要的是一个能提供 http 接口的 console 前端

确实是这么回事,mirai本身的console也没办法做到和前端交互,除非根据core自己去写

**Comment by MaerdDaed** [comment]
能否支持webhook根据事件类型上报到不同url，如果能支持的话，可以搭配云函数 serverless等工具使开发更加简便，不用每次修改某类型的响应就重新部署整个应用

**Comment by xpnew** [comment]
> 请求支持消息类型：**合并转发**、**商城表情**、音乐分享、链接分享、短视频、群文件（不是接收群文件，就给一个群文件的消息类型，用于标识这条消息是群文件）
> 请求支持API：**增加/删除群管理员**、发送群内拍一拍（双击头像）
> 请求支持事件：收到群内拍一拍（双击头像）
> 请求支持其他内容：支持amr格式以外的语音文件

我就是想要QQ音乐分享这个功能，才找进来的。
然后，顺便我建议，如果不能【单独提供一个专门的音乐分享的“消息类型”】，那就给出一个【发送自定义消息】的类型，让我们直接发送原生的消息出去也行。（PS：我是用c#的，没看过 mirai的KT源代码，也就不知道原生的消息是什么格式）

**Comment by xpnew** [comment]
> 想问一下，mirai-api-http 如果发送群消息时@全体成员？感谢

你可以看看消息类型参考：https://github.com/project-mirai/mirai-api-http/blob/master/docs/MessageType.md
【@全体】这个是其中一种特殊的消息类型。
一开始我也有这个问题，好一顿翻文档才看找到在这里。
