### ISSUE TITLE
令 verify 接口可以维持 Session 存活

### ISSUE THREAD

**Issue by drsanwujiang** [project-mirai/mirai-api-http#217]
我通过每五分钟使用 /verify 来维持 Session 存活，但是 Sesssion 还是会在意料之外的情况下被回收。
这是不是意味着 /verify 并不能维持 Session？

**Comment by ryoii** [comment]
/verify不能，你可以通过/fetch

**Comment by drsanwujiang** [comment]
> /verify不能，你可以通过/fetch

了解了，那考虑给 /verify 增加这个功能吗？毕竟再次认证也算使用嘛
