### ISSUE TITLE
[bug]uploadImage错误

### ISSUE THREAD

**Issue by I-love-study** [project-mirai/mirai-api-http#221]
在几乎同一时间使用python的graia进行uploadImage请求
（不同的两个账号发送两个不同的图片）
可能会出现返回同一图片的链接的情况
mirai-console在此期间并没有任何报错

**Comment by ryoii** [comment]
是否使用了 console 的多账号登录

**Comment by I-love-study** [comment]
> 是否使用了 console 的多账号登录

是的

**Comment by ryoii** [comment]
一般是core的问题，尝试使用新版本core，如果还有此类问题，请reopen
