### ISSUE TITLE
突然群消息较长的消息发不了，两个服务器都出现这样的问题

### ISSUE THREAD

**Issue by Brioal** [project-mirai/mirai-api-http#225]
jar包版本
mirai-console:1.0-M4
mirai-console-pure:1.0-M4
mirai-core-qqandroid:1.2.3

偶尔能长消息发送成功，大多数情况发送成功但是`messageId=-1`，收不到消息有没有大佬知道的，我的两台服务器都出现这样的问题了

**Comment by ryoii** [comment]
尝试继续增长一点消息长度，可能刚好碰到阈值
