### ISSUE TITLE
验证session时提示bot不存在

### ISSUE THREAD

**Issue by moheng233** [project-mirai/mirai-api-http#230]
![image](https://user-images.githubusercontent.com/57742561/103068988-5dee3e80-45f9-11eb-99cb-1f5b9ff8e4fe.png)
![image](https://user-images.githubusercontent.com/57742561/103069019-6f374b00-45f9-11eb-8469-133286106a2d.png)

插件版本是1.9.2

其他版本
![image](https://user-images.githubusercontent.com/57742561/103069060-870ecf00-45f9-11eb-9454-636e2bdce614.png)

日志没有报错

**Comment by moheng233** [comment]
啊这，重新登陆一下就好了。
但神奇的是，登陆就管一下
释放之前的，再重新验证就会又提示不存在

**Comment by ryoii** [comment]
目前不负责登录，先在console完成登录在进行mah的验证
