### ISSUE TITLE
fetchMessage方法无法获取新消息

### ISSUE THREAD

**Issue by zmdyy0318** [project-mirai/mirai-api-http#232]
1、core版本：M2、http版本1.9.3
2、测试环境：API-Tester、cpp-template
3、复现流程：
--------------API-Tester-1----------
①core登陆
②获取sessionkey并验证
③通过iPhone发送给core的QQ信息
④调用fetchMessage方法
⑤返回为空
--------------API-Tester-2----------
①core登陆
②获取sessionkey并验证
③通过iPhone发送给core的QQ信息
④调用countMessage方法
⑤调用fetchMessage方法
⑥有返回，但没有code字段
{"data":[{"type":"GroupMessage","messageChain":[{"type":"Source","id":1765,"time":1609233707},{"type":"Plain","text":"321313"}],"sender":{"id":XXXXXXX,"memberName":"XXXXXXX","permission":"OWNER","group":{"id":XXXXXX,"name":"XXXX","permission":"ADMINISTRATOR"}}}]}
--------------cpp-template-1----------
①core登陆
②获取sessionkey并验证
③通过iPhone发送给core的QQ信息
④使用usehttp或usewebsocket方式
⑤返回持续为空
--------------cpp-template-2----------
①core登陆
②获取sessionkey并验证
③通过iPhone发送给core的QQ信息
④使用usehttp
⑤调用countMessage方法
⑥调用fetchMessage方法
⑦有返回，但没有code字段
{"data":[{"type":"GroupMessage","messageChain":[{"type":"Source","id":1765,"time":1609233707},{"type":"Plain","text":"321313"}],"sender":{"id":XXXXXXX,"memberName":"XXXXXXX","permission":"OWNER","group":{"id":XXXXXX,"name":"XXXX","permission":"ADMINISTRATOR"}}}]}

**Comment by ryoii** [comment]
我没有复现获取消息空的情况，猜测是 `mirai-core` 一直存在的登录后一段较短时间内的消息没有触发事件的问题

返回值没有 `code` 字段经确认是 序列化库更新后出现的问题，忽略了所有默认值，将在稍后发布一个新版本。

对于 `issue` 中出现的问题，如果在等待一段时间后（约半分钟到一分钟）再发消息仍无法获取，请 reopen 该 isuue

**Comment by zmdyy0318** [comment]
1.9.4同样环境一切正常

**Comment by zmdyy0318** [comment]
反馈问题，websocket获取消息持续为空。
测试环境Debian10（本地C++连接外网服务器mirai-api-http）、windows（本地C++连接本地mirai-api-http）
①core登陆
②获取sessionkey并验证
③通过iPhone发送给core的QQ信息
④使用usewebsocket方式
⑤等待几分钟，返回持续为空（http方式一切正常几乎无延迟）
不知道如何reopen，以艾特方式代替，麻烦啦。 @ryoii
