### ISSUE TITLE
申请加群事件问题: 申请者无法收到拒绝加群的理由

### ISSUE THREAD

**Issue by MoeClub** [project-mirai/mirai-api-http#233]
通过手机客户端可以自己填写拒绝理由,申请者都能收到拒绝理由.

通过 `[POST] /resp/memberJoinRequestEvent` 响应并校验申请信息
当拒绝申请时, 自定义响应的 `message` 字段值, 申请者收到的拒绝信息总是为空.

**Comment by ryoii** [comment]
一般是 `core` 的协议出问题，你可以到 `core` 下 issue 下搜索相关问题
