### ISSUE TITLE
sendFriendMessage发送的messageChain被累加

### ISSUE THREAD

**Issue by chaserance** [project-mirai/mirai-api-http#234]
1. Context:
    - mirai-console-loader版本：1.0.3
    - mirai-core版本：2.0-M2
    - mirai-api-http版本: 1.9.5
    - 测试platform: Postman

2. Reproduce steps:
    1. mirai-console-loader启动
    2. 通过/auth 获取authKey
    3. 通过/verify 验证authKey并绑定QQ
    4. 调用/sendFriendMessage,
    5. 对象QQ收到被累加的消息
    
Request body:
```JSON
            {
                "sessionKey": "{{authKey}}",
                "target": 1234567,
                "messageChain": [
                    { "type": "Plain", "text": "1\n" },
                    { "type": "Plain", "text": "2\n" },
                    { "type": "Plain", "text": "3\n" },
                    { "type": "Plain", "text": "4" }
                ]
            }
```
对象QQ收到消息：
1
1
2
1
2
3
1
2
3
4

**Comment by Karlatemp** [comment]
Use `mirai-core 2.0-M2-1`

**Comment by chaserance** [comment]
> Use `mirai-core 2.0-M2-1`

谢谢 请问mirai-core-all也release了对应版本吗？mcl启动需要这个包，但貌似没法找到

**Comment by chaserance** [comment]
mirai-core-all 2.0-M2-1已经发布 更新后issue resolved, 谢谢
