### ISSUE TITLE
获取不到信息和事件

### ISSUE THREAD

**Issue by zmyzy** [project-mirai/mirai-api-http#236]
版本
Running MiraiConsole v2.0-M2-1-dev-1, built on 2020-12-29 12:05:33.
Frontend Terminal: version 2.0-M2-1-dev-1, provided by Mamoe Technologies

Permission Service: Built In Permission Service

Plugins: net.mamoe.mirai-api-http v1.9.5

http访问参数：http://127.0.0.1:8080/peekLatestMessage?sessionKey=gW4l31LQ&count=10

访回数据：{"code":0,"errorMessage":"","data":[]}
![image](https://user-images.githubusercontent.com/49664384/104082548-f9c2b000-5271-11eb-931a-40cdef2b3de2.png)

**Comment by ryoii** [comment]
回退版本测试没有复现，请检查自己的代码，或升级新版本。
若还有问题，请重新打开`issue`
