### ISSUE TITLE
请问 上报的 destinations:[] 怎么写?

### ISSUE THREAD

**Issue by wandefou** [project-mirai/mirai-api-http#238]
settings.yml

report: 
  enable: true
  groupMessage: 
    report: true
  friendMessage: 
    report: true
  tempMessage: 
    report: true
  eventMessage: 
    report: true
  destinations: [0.0.0.0:9528]   #  <----------   这里怎么写?   
  extraHeaders: {}

**Comment by wandefou** [comment]
destinations: [0.0.0.0,9528] # <---------- 加个逗号,额

**Comment by ryoii** [comment]
填需要上报到的接口，多个地址参考  `yaml` 文件的数组写法

**Comment by wandefou** [comment]
好的  谢谢

**Comment by ywyself** [comment]
```yaml
 # 上报URL
 destinations:
     - /receive
```
上报到http://localhost/receive,  好像不能指定域名

**Comment by ryoii** [comment]
> ```yaml
>  # 上报URL
>  destinations:
>      - /receive
> ```
> 
> 上报到http://localhost/receive, 好像不能指定域名

没有理解，是指指定了域名不生效？还是不指定域名也能生效，还是目前不论怎么写都不能生效

**Comment by ywyself** [comment]
> > ```yaml
> >  # 上报URL
> >  destinations:
> >      - /receive
> > ```
> > 
> > 
> > 上报到http://localhost/receive, 好像不能指定域名
> 
> 没有理解，是指指定了域名不生效？还是不指定域名也能生效，还是目前不论怎么写都不能生效


是不能写域名,  只能写路径,  上报的时候,  只会上报到http://localhost:80 下

**Comment by ryoii** [comment]
```
 # 上报URL
 destinations:
     - 'http://localhost/receive'
```

字符串里带了冒号，引号包围就好了

**Comment by ryoii** [comment]
长时间未回复，予以关闭。
还有其他问题，直接原 issue 下回复或 reopen
