### ISSUE TITLE
带有引用回复的消息未上报

### ISSUE THREAD

**Issue by Clansty** [project-mirai/mirai-api-http#240]
使用 WebSocket 获取消息上报，所有包含引用回复的消息均未上报

**Comment by Clansty** [comment]
通过 fetchMessage 获取会报错 指定对象不存在

**Comment by ryoii** [comment]
请提供版本号

**Comment by Clansty** [comment]
Mirai 2.0.0
Http-Api 1.9.6

**Comment by ryoii** [comment]
尝试退回 1.9.6 对应的 `core` 版本，可能升级 `2.0.0` 导致部分不兼容

**Comment by Clansty** [comment]
> 我试了1.9.6搭2.0-RC-dev-8, 2.0-RC, 2.0-M2-2都是console的log里显示有，但使用http-api的应用收不到quote

我也是这个情况，整条消息都收不到

**Comment by ryoii** [comment]
引用回复的序列化出错

**Comment by nios34** [comment]
同样的问题也出现在 HTTP 的上报上。所有引用的消息都不会被上报。
