### ISSUE TITLE
mcl下载http插件失败

### ISSUE THREAD

**Issue by zmdyy0318** [project-mirai/mirai-api-http#241]
步骤：
./mcl --update-package net.mamoe:mirai-api-http --channel stable --type plugin
./mcl
显示：
11:01:09 [INFO] Mirai Console Loader version 1.0.3-6e34f43
 11:01:09 [INFO] https://github.com/iTXTech/mirai-console-loader
 11:01:09 [INFO] This program is licensed under GNU AGPL v3
 11:01:09 [DEBUG] Loading script: updater.js
 11:01:10 [DEBUG] Loading script: config.js
 11:01:10 [DEBUG] Loading script: repo.js
 11:01:10 [DEBUG] Loading script: boot.js
 11:01:10 [INFO] Verifying "net.mamoe:mirai-console" version 2.0.0
 11:01:14 [INFO] Verifying "net.mamoe:mirai-console-terminal" version 2.0.0
 11:01:21 [INFO] Verifying "net.mamoe:mirai-core-all" version 2.0.0
 11:01:24 [INFO] Verifying "net.mamoe:mirai-api-http" version 1.9.6
 11:01:24 [INFO] "net.mamoe:mirai-api-http:1.9.6" is corrupted. Start downloading...
 11:01:25 [ERROR] Cannot download package "net.mamoe:mirai-api-http".
 11:01:25 [WARNING] The local file "net.mamoe:mirai-api-http" is still corrupted, please check the network.
这是我mcl的config
{
  "js_optimization_level": -1,
  "mirai_repo": "https://gitee.com/peratx/mirai-repo/raw/master",
  "maven_repo": "https://maven.aliyun.com/repository/public",
  "packages": [
    {
      "id": "net.mamoe:mirai-console",
      "channel": "stable",
      "version": "2.0.0",
      "type": "libs"
    },
    {
      "id": "net.mamoe:mirai-console-terminal",
      "channel": "stable",
      "version": "2.0.0",
      "type": "libs"
    },
    {
      "id": "net.mamoe:mirai-core-all",
      "channel": "stable",
      "version": "2.0.0",
      "type": "libs"
    },
    {
      "id": "net.mamoe:mirai-api-http",
      "channel": "stable",
      "version": "1.9.6",
      "type": "plugins"
    }
  ],
  "disabled_scripts": [],
  "proxy": "",
  "log_level": 0,
  "script_props": {}
}
猜测问题：
https://maven.aliyun.com/repository/public仓库中没有http插件。
查看mcl源码，updater.js会尝试获取链接，例如
https://maven.aliyun.com/repository/public/net/mamoe/mirai-core-all/2.0.0/mirai-core-all-2.0.0-all.jar
https://maven.aliyun.com/repository/public/net/mamoe/mirai-core-all/2.0.0/mirai-core-all-2.0.0.mirai.jar
https://maven.aliyun.com/repository/public/net/mamoe/mirai-core-all/2.0.0/mirai-core-all-2.0.0.jar
第一个链接可以成功下载；
但http的链接
https://maven.aliyun.com/repository/public/net/mamoe/mirai-api-http/1.9.6/mirai-api-http-1.9.6-all.jar
https://maven.aliyun.com/repository/public/net/mamoe/mirai-api-http/1.9.6/mirai-api-http-1.9.6.mirai.jar
https://maven.aliyun.com/repository/public/net/mamoe/mirai-api-http/1.9.6/mirai-api-http-1.9.6.jar
三个链接均无法下载。
https://maven.aliyun.com/mvn/search手动搜索mirai-api-http也为空。

**Comment by PeratX** [comment]
应该检查一下是否已经加入JCenter @Karlatemp

**Comment by PeratX** [comment]
暂时可以使用：https://dl.bintray.com/him188moe/mirai 作为Maven Repo

**Comment by Him188** [comment]
现在在 JCenter 了

**Comment by zmdyy0318** [comment]
测试已解决

**Comment by 1848450844** [comment]
Package "net.mamoe:mirai-api-http" has been updated.

你好当[安装mirai-api-http插件](https://www.theresa3rd.cn/#/miraiInstall?id=%e5%ae%89%e8%a3%85mirai-api-http%e6%8f%92%e4%bb%b6)的最后一个操作无法实现，如何操作
