### ISSUE TITLE
[已解決]跟#149一样遇到提示图片上传成功并生成imageId但是图裂/无限加载/404

### ISSUE THREAD

**Issue by LoS-Light** [project-mirai/mirai-api-http#244]
各版本如下
net.mamoe:mirai-console-v2.0.0
net.mamoe:mirai-console-terminal-v2.0.0
net.mamoe:mirai-core-all-v2.1.0
mirai-api-http-v1.9.6

跟这位大佬遇到的状况完全一样
#149 

目前我这边测试發现:
在两个群A和B
A群70人 發送会图裂
B群5人 發送图没有问题 不会图裂

无任何报错
且生成的messageId也都可以自动撤回
图裂原因不明

**Comment by ryoii** [comment]
既然能够发送成功，应该就不是接口的问题，考虑将`issue`转到[mirai](https://github.com/mamoe/mirai/issues)仓库

**Comment by LoS-Light** [comment]
> 既然能够发送成功，应该就不是接口的问题，考虑将`issue`转到[mirai](https://github.com/mamoe/mirai/issues)仓库

谢谢您的回覆，晚点我再测试一次，如果还是不行，我再转到那里。

**Comment by PluginsKers** [comment]
blob对象不知道可不可以。

**Comment by LoS-Light** [comment]
> 既然能够发送成功，应该就不是接口的问题，考虑将`issue`转到[mirai](https://github.com/mamoe/mirai/issues)仓库
> blob对象不知道可不可以。

已解决。
经过昨晚的各种测试后，發现只要图片还未首先经过上传到服务器，而直接使用
[POST] /sendGroupMessage
将图片的url或是path包进MessageChain的讯息，
图片将会在某些群组高机率的图裂。

但是如果先将图片经由
[POST] /uploadImage
上传后取得的messageId或是url，
再将它用于
[POST] /sendGroupMessage
的MessageChain裡的话，
就不会發生图裂了。

至于为何这样可以，原因不明。
总之这样的方法是可行的。

但是發图频率过快，还是会有几张图片图裂的状况發生就是了。

我先不急着关闭这issue，给其他也遇到这问题的大佬们参考，
后续我还有新的發现的话，还会上来补充，
如果其它大佬有更好的解法，也欢迎留言讨论，
过一阵子我将会关闭这issue，
或是交由管理员您来决定。
谢谢。
