### ISSUE TITLE
带有回复的消息中被引用的消息缺失时间戳

### ISSUE THREAD

**Issue by OasisAkari** [project-mirai/mirai-api-http#246]

**Comment by PluginsKers** [comment]
你是win？

**Comment by OasisAkari** [comment]
> 你是win？

linux和win都一样

**Comment by PluginsKers** [comment]
我在/auth请求（服务的第一步）被迫终止。
你的相关版本是？

**Comment by OasisAkari** [comment]
> 我在/auth请求（服务的第一步）被迫终止。
> 你的相关版本是？

mirai-core 2.1.1
mirai-api-http 1.9.7

测试被引用消息包含时间戳的版本大概是
mirai-core1.3.3
mirai-api-http 1.9.0

**Comment by ryoii** [comment]
引用的消息目前丢失了 `MessageSource` ，这是 `core` 变更导致的。时间戳没记错应该是从 `MessageSource` 里获取的。我想复现查看结果，可是我在2.1.0的版本中获取不到消息。我测试完毕后再给予回复

**Comment by ryoii** [comment]
时间戳确实来自于 `MessageSource`, 自新版本，core 取消了引用回复中的 `MessageSource`
