### ISSUE TITLE
示例程序session.ConnectAsync时发生错误

### ISSUE THREAD

**Issue by aion1998** [project-mirai/mirai-api-http#247]
![image](https://user-images.githubusercontent.com/19725014/106092597-912c6c00-6169-11eb-94fc-0bcf1ddf9b92.png)

具体发生错误地点在下图红线所画区域

![image](https://user-images.githubusercontent.com/19725014/106092642-abfee080-6169-11eb-88a6-dba3ce5f29af.png)

编辑器：VS2019
使用时区：
![image](https://user-images.githubusercontent.com/19725014/106092695-cafd7280-6169-11eb-983d-40a9d4f40d2f.png)
电脑配置：
![image](https://user-images.githubusercontent.com/19725014/106092728-df416f80-6169-11eb-92b1-bbb9fdfa9fa7.png)

**Comment by ryoii** [comment]
请将 `issue` 提到正确的 sdk 仓库中，sdk的使用问题和本仓库的插件无关

**Comment by aion1998** [comment]
> 请将 `issue` 提到正确的 sdk 仓库中，sdk的使用问题和本仓库的插件无关
。。。看错了，不好意思
