### ISSUE TITLE
通过 WebSocket 监听事件时返回 {"code":10,"msg":"无操作权限"}

### ISSUE THREAD

**Issue by GAOSILIHAI** [project-mirai/mirai-api-http#248]
```js
const ws = new WebSocket('ws://localhost:8080/message?sessionKey=' + sessionKey);

ws.on('message', (data) => {
    console.log(data);
})
```
> {"code":10,"msg":"无操作权限"}

我看了 [mirai-console](https://github.com/mamoe/mirai-console) 的关于权限的 [文档](https://github.com/mamoe/mirai-console/blob/master/docs/Permissions.md)
请问被许可人 ID 是什么？我需要从哪里得到这个 ID，我需要对哪个用户授予什么权限？
非常感谢！

**Comment by ryoii** [comment]
使用 websocket 前先开启 websocket 通信功能，默认是关闭的

**Comment by GAOSILIHAI** [comment]
> 使用 websocket 前先开启 websocket 通信功能，默认是关闭的


刚翻到，原来需要针对每个 session 进行设置

[文档 -> 修改指定Session的配置](https://github.com/project-mirai/mirai-api-http/blob/master/docs/API.md#%E4%BF%AE%E6%94%B9%E6%8C%87%E5%AE%9Asession%E7%9A%84%E9%85%8D%E7%BD%AE)

感谢

**Comment by ryoii** [comment]
配置文件内可以开启全局配置
