### ISSUE TITLE
1.9.7上报失败

### ISSUE THREAD

**Issue by 2659494057** [project-mirai/mirai-api-http#250]
有时候上报成功，有时候上报失败，失败居多
失败时返回unexpected end of stream on

**Comment by ryoii** [comment]
多种可以能导致这个错误

#### 远程服务器不支持连接

排查远程服务器是否有意外关闭连接的情况出现

#### 远程服务器不支持长连接

可能是长连接被远程服务器关闭导致的连接不可用

尝试在配置文件中添加额外的 Header `Connection: Close` 强制关闭长连接

**Comment by ryoii** [comment]
参考#243
