### ISSUE TITLE
事件广播问题

### ISSUE THREAD

**Issue by SAGIRI-kawaii** [project-mirai/mirai-api-http#251]
在测试代码时发现有一部分事件没有被广播，未广播事件列表如下：
bot权限改变：BotGroupPermissionChangeEvent，
群组内撤回：GroupRecallEvent，
坦白说状态改变：GroupAllowConfessTalkEvent，
允许群员邀请好友加群：GroupAllowMemberInviteEvent，

环境：
mirai-console-2.0-RC
mirai-core-all-2.1.0
mirai-api-http-v1.9.6

**Comment by ryoii** [comment]
留意控制台内是否有对应事件的日志出现

**Comment by SAGIRI-kawaii** [comment]
> 留意控制台内是否有对应事件的日志出现

反复测试确认没有出现，其他事件有出现以Event：开头的消息

**Comment by ryoii** [comment]
没有出现建议携带日志将 `issue` 转到 [mamoe/mirai](https://github.com/mamoe/mirai) 仓库

如果控制台内没有出现对应事件的日志，说明事件确实没有触发，插件也没有监听到事件的发生

**Comment by SAGIRI-kawaii** [comment]
将手表协议更换为手机协议后已解决，忘记改回来了
