### ISSUE TITLE
bot 被挤下线后重新登陆，当前 session 并未失效，但无法 sendMessage

### ISSUE THREAD

**Issue by GAOSILIHAI** [project-mirai/mirai-api-http#253]
向插件服务端创建一个 `session`，并 `verify `到一个已登录的 qq，`ws`监听 `BotOfflineEventForce `bot 被挤下线事件。

当事件触发后向服务端发送` /login `指令重新登陆，登陆返回后调用 `POST sendFriendMessage`，此时会出错

![image](https://user-images.githubusercontent.com/53897259/106252969-d75cfa80-6251-11eb-99fc-9b6f5aeabbf9.png)

> status 500
> message 'network is dead therefore can't send any packet'

但是此时若调用 `GET config`则可以正常返回，可见该 `session `并未失效。

![image](https://user-images.githubusercontent.com/53897259/106253009-e0e66280-6251-11eb-8805-b5291a55144f.png)

请问这种情况正常吗？我是否应该在 bot 下线并再次登陆后重新创建 session？

非常感谢！

**Comment by ryoii** [comment]
如果重新登录是指 除自动重连 以外的方式进行登录，这是正常的现象。session 是绑定到 bot 示例上而非 qq 号上。当 bot 重新登录后，它已经不是同一个示例，因此 session 确实会失效。

但是我认为 将 session 绑定到 qq 号上或许是一个更好的选择，有待考虑

**Comment by GAOSILIHAI** [comment]
> 如果重新登录是指 除自动重连 以外的方式进行登录，这是正常的现象。session 是绑定到 bot 示例上而非 qq 号上。当 bot 重新登录后，它已经不是同一个示例，因此 session 确实会失效。
> 
> 但是我认为 将 session 绑定到 qq 号上或许是一个更好的选择，有待考虑

明白了，谢谢！
