### ISSUE TITLE
WebSocket 连接被忽略的问题

### ISSUE THREAD

**Issue by Drincann** [project-mirai/mirai-api-http#255]
若没有任何事件发生，服务端将会在几分钟内忽略该 WebSocket 连接。

**忽略**指该连接没有发生 error close 等事件，状态仍然是 OPEN，但不会收到任何消息。

经过测试，定时发送 ping 包将会维持该连接，但文档中好像没提到这一点。

**Comment by ryoii** [comment]
没有收掉消息是指控制台显示了消息日志但没有收到ws的推送，还是都没有记录

改情况发生的时间节点一般在启动多久之后出现

**Comment by GAOSILIHAI** [comment]
> 没有收掉消息是指控制台显示了消息日志但没有收到ws的推送，还是都没有记录
> 
> 该情况发生的时间节点一般在启动多久之后出现

没有收到消息指控制台显示了消息日志但没有收到 ws 的推送，这种情况一般发生在 5 分钟内（未收到任何新消息的情况下）。

我尝试向服务端发送 ping 时会立刻收到 pong，然后就猜测服务端做了心跳，只不过没写在文档上。

于是我便尝试每分钟向服务端发送 ping，此后再也没有出现这种问题。

**Comment by ryoii** [comment]
据我了解，代码里没有 `ping -> pong` 的消息处理，仅有作为接收线程阻塞作用的一个 `echo` 功能

**Comment by GAOSILIHAI** [comment]
> 据我了解，代码里没有 `ping -> pong` 的消息处理，仅有作为接收线程阻塞作用的一个 `echo` 功能


```js
const axios = require('axios').default;

const qq = 1019933576;
const authKey = 'authKey';
const baseUrl = 'http://example:port';

// 认证和绑定 bot
let {
    data: { session: sessionKey },
} = await axios.post(`${baseUrl}/auth`, { authKey });
await axios.post(`${baseUrl}/verify`, { sessionKey, qq });

// 建立 ws 连接
const WebSocket = require('ws');
const ws = new WebSocket(`ws://gaolihai.cool:6666/all?sessionKey=${sessionKey}`);
ws.on('open', () => {
    // 每秒发送 ping
    const interval = setInterval(ws.ping, 1000);
    ws.on('close', (code, reason) => {
        clearInterval(interval);
    })
});
ws.on('pong', (data) => {
    // 收到 pong 后 log pong
    console.log('pong');
});
```
这是我的测试代码，成功创建会话并建立连接后，控制台的确会不断地 log 'pong'。

**Comment by GreyElaina** [comment]
经过使用 `aiohttp` 的相关封装, 现在, Graia 默认每 30s 向 mirai-api-http 服务端发送一封 `ping` 消息, 解决了相关问题 [GraiaProject/Application#84](https://github.com/GraiaProject/Application/issues/84)

建议在 `mirai-api-http` 的 2,0 版本发布前, 将该方式写入文档并要求作为规范实现.

**Comment by ryoii** [comment]
13分钟无消息，测试无问题，检查 ws client 是否有无响应 timeout 设置
