### ISSUE TITLE
mirai是否支持接收群文件上传的消息

### ISSUE THREAD

**Issue by HungryBunny-wei** [project-mirai/mirai-api-http#260]
![image](https://user-images.githubusercontent.com/28952169/106359254-736b2c80-634c-11eb-963b-83c30e1c73c8.png)
当从文件管理器移动文件到输入框发送图片
![image](https://user-images.githubusercontent.com/28952169/106359262-87169300-634c-11eb-950c-e91b72b26c89.png)
结果是这种有上传状态的图片,实际应该是上传到群文件里面了.

但是groupMessage事件没有对应消息类型
![image](https://user-images.githubusercontent.com/28952169/106359317-f9877300-634c-11eb-9868-296caf740639.png)

这个issue可能是要提交到mirai库?

**Comment by ryoii** [comment]
不支持， mirai 已有相关 issue，可以搜索并关注

**Comment by ryoii** [comment]
不支持， mirai 已有相关 issue，可以搜索并关注
