### ISSUE TITLE
websocket未知条件触发后,就会一条消息重复两次上报

### ISSUE THREAD

**Issue by y1meng** [project-mirai/mirai-api-http#262]
是我的问题吗?还是bug

**Comment by drinkal** [comment]
> 是我的问题吗?还是bug

可以复现吗，贴代码看看？

**Comment by ryoii** [comment]
特定事件被上报两次还是所有事件都被上报两次

**Comment by y1meng** [comment]
![image](https://user-images.githubusercontent.com/45099938/106442045-c7455500-64b5-11eb-9bd6-7bc7a8f728e2.png)
![image](https://user-images.githubusercontent.com/45099938/106442144-e6dc7d80-64b5-11eb-9190-3fa0122fbd28.png)
我还不能复现,遇见的是群消息重复上报,如果没有人出现这种情况的话,我觉得是我写的代码太烂导致的😂

**Comment by y1meng** [comment]
已经找到原因,是自己导致的.
