### ISSUE TITLE
[GET] /memberList 接口返回的结构冗余

### ISSUE THREAD

**Issue by drinkal** [project-mirai/mirai-api-http#263]
[/docs/API.md#获取群成员列表](https://github.com/project-mirai/mirai-api-http/blob/master/docs/API.md#%E8%8E%B7%E5%8F%96%E7%BE%A4%E6%88%90%E5%91%98%E5%88%97%E8%A1%A8)

请求中包含了欲获取成员列表的群号，但返回中每个成员均包含一个多余的`group`字段

```json
[
  {
    "id":1234567890,
    "memberName":"",
    "permission":"MEMBER",
    "group":{
        "id":12345,
        "name":"群名1",
        "permission": "MEMBER"
    }
  },

]
```

是因为 Mirai 接口就包含了这些信息吗？

**Comment by ryoii** [comment]
顺手写上的而已
