### ISSUE TITLE
memberInfo查询和memberList不一致

### ISSUE THREAD

**Issue by HungryBunny-wei** [project-mirai/mirai-api-http#266]
![image](https://user-images.githubusercontent.com/28952169/106692683-e526cd00-660f-11eb-88d4-3dd634dd328d.png)

群成员如果没有设置群昵称的时候,memberInfo获取的信息是空的, memberList就能获取到qq名称

但是原本没设置名称的设置了在删掉就一致

"net.mamoe:mirai-console" version 2.2.2
 "net.mamoe:mirai-console-terminal" version 2.2.2
"net.mamoe:mirai-core-all" version 2.2.2

"mirai-api-http" version 1.9.7

**Comment by drinkal** [comment]
我尝试让一个新号加入群，未设置群名片。
取到的 memberInfo 和 memberList 中，此人的 name 不为空，但均为另一个群中的名片。

> "net.mamoe:mirai-console" version 2.2.2
> "net.mamoe:mirai-console-terminal" version 2.2.2
> "net.mamoe:mirai-core-all" version 2.2.2
> "net.mamoe:mirai-api-http" version 1.9.6
