### ISSUE TITLE
hello，事件上报好像不传参数？

### ISSUE THREAD

**Issue by AsukaMikoto** [project-mirai/mirai-api-http#274]
我发现事件上报里面，填入了服务端开的API接口地址，配置文件里面事件上报的开关也开了，但是服务端程序上始终抓不到parameter的参数，这是为什么呢？

**Comment by ryoii** [comment]
是事件没有还是仅是参数抓不到

**Comment by AsukaMikoto** [comment]
额，是有事件，能看到请求了。
参数列表空

**Comment by ryoii** [comment]
上报没有参数啊，如果你是指上报过程中配置的自定义内容，那个应该是填到了请求头里

**Comment by AsukaMikoto** [comment]
额 那有个问题，我看原文是这样写的
“当MiraiApiHttp收到新的消息（事件，群消息，好友消息），都可以给指定地址发送包含该消息的POST请求。”
这个包含该消息的post请求
消息也是在头里面吗

**Comment by ryoii** [comment]
消息在body里

**Comment by AsukaMikoto** [comment]
好的 谢谢
