### ISSUE TITLE
好友列表为空

### ISSUE THREAD

**Issue by jupitersh** [project-mirai/mirai-api-http#276]
[GET] /friendList?sessionKey=YourSessionKey获取好友列表时返回的是 [] 空列表，也无法用[POST] /sendFriendMessage发送好友消息，提示发送消息目标不存在(指定对象不存在)。
但是用[GET] /groupList?sessionKey=YourSessionKey获取群列表没有问题，[POST] /sendGroupMessage发送群消息是没有问题的。

**Comment by Executor-Cheng** [comment]
把mirai三件套更新到2.4-RC试试吧, +mirai-api-httpv1.9.8
早上试了没问题

**Comment by jupitersh** [comment]
我的版本是这样的

Running MiraiConsole v2.4-M1, built on 2021-02-07 06:45:39.
Frontend Terminal: version 2.4-M1, provided by Mamoe Technologies

Permission Service: Built In Permission Service

Plugins: net.mamoe.mirai-api-http v1.9.8

**Comment by jupitersh** [comment]
更新到2.4RC就可以了，感谢
