### ISSUE TITLE
上传群语音音质问题

### ISSUE THREAD

**Issue by ZhaoZuohong** [project-mirai/mirai-api-http#278]
在Mirai的Repo的Issue里讨论过这个问题，目前使用HTTP通道上传silk格式的语音，会被压缩成amr格式，解决办法是使用highway通道传输语音，此功能已经在mirai的2.2.0-dev-bdh-1版本实现。详见issue:[https://github.com/mamoe/mirai/issues/577](https://github.com/mamoe/mirai/issues/577)
现在mirai-api-http上传语音还是会被压缩，希望能改进一下。

**Comment by Him188** [comment]
它应该是 https://github.com/mamoe/mirai/issues/940 的问题

**Comment by djkcyl** [comment]
> 它应该是 [mamoe/mirai#940](https://github.com/mamoe/mirai/issues/940) 的问题

如果使用FFmpeg进行转码的话需要转成什么格式呢

**Comment by Him188** [comment]
> > 它应该是 [mamoe/mirai#940](https://github.com/mamoe/mirai/issues/940) 的问题
> 
> 如果使用FFmpeg进行转码的话需要转成什么格式呢

silk v3

**Comment by djkcyl** [comment]
> > > 它应该是 [mamoe/mirai#940](https://github.com/mamoe/mirai/issues/940) 的问题
> > 
> > 
> > 如果使用FFmpeg进行转码的话需要转成什么格式呢
> 
> silk v3

具体的话要带什么参数呢

**Comment by ZhaoZuohong** [comment]
> > > 它应该是 [mamoe/mirai#940](https://github.com/mamoe/mirai/issues/940) 的问题
> > 
> > 
> > 如果使用FFmpeg进行转码的话需要转成什么格式呢
> 
> silk v3

标准的Silk V3行吗，腾讯的Silk V3好像有点改动

**Comment by djkcyl** [comment]
> > > > 它应该是 [mamoe/mirai#940](https://github.com/mamoe/mirai/issues/940) 的问题
> > > 
> > > 
> > > 如果使用FFmpeg进行转码的话需要转成什么格式呢
> > 
> > 
> > silk v3
> 
> 标准的Silk V3行吗，腾讯的Silk V3好像有点改动

https://github.com/I-love-study/graiax-silkcoder 我找到了一个这个库
