### ISSUE TITLE
获取到的好友列表里的备注（remark）全为空

### ISSUE THREAD

**Issue by finale-z** [project-mirai/mirai-api-http#279]
操作系统: Armbian 21.02.1 Buster
mirai-core 版本: 2.4-RC
mirai-api-http 版本: 1.9.8

**Comment by milkice233** [comment]
据反馈使用 CQHTTP 协议的 Mirai 客户端似乎备注是没问题的，可能是 mirai-api-http 的问题？

**Comment by GreyElaina** [comment]
![image](https://user-images.githubusercontent.com/31543961/110228628-8f5e8100-7f3d-11eb-9e71-c92b50d1eebd.png)

**Comment by Doctor-Yin** [comment]
将于1.9.9版本修复

**Comment by Doctor-Yin** [comment]
#288

**Comment by Doctor-Yin** [comment]
Duplicate of #288
