### ISSUE TITLE
尝试发送好友消息时报错没有注册 IgnoreEvent 类

### ISSUE THREAD

**Issue by WindLeaf233** [project-mirai/mirai-api-http#281]
Python 在 requests /sendFriendMessage 后得到如下内容:
```Plain
Class 'IgnoreEventDTO' is not registered for polymorphic serialization in the scope of 'EventDTO'.
Mark the base class as 'sealed' or register the serializer explicitly.
```

mcl 显示的报错 pastebin:
[2021-02-22 16:15:55 E/net.mamoe.mirai-api-http: kotlinx.serialization.Serializat - Pastebin.com](https://pastebin.com/UCg2ZpzN)

SessionKey 等都是正常的

mirai-api-http 版本: 1.9.8 (latest)
mirai-core-all 版本: 2.4.0
mirai-console-terminal 版本: 2.4.0
mirai-console 版本: 2.4.0
用的 mirai-console-loader: 1.0.5

**Comment by HoshinoTented** [comment]
将在未来版本修复

**Comment by HoshinoTented** [comment]
大概，这代码我看不懂

**Comment by HoshinoTented** [comment]
未能成功复现

**Comment by HoshinoTented** [comment]
是否确定是仅 sendFriendMessage？
这个异常目前发现是只在 peekMessage 的时候才会触发

**Comment by WindLeaf233** [comment]
> 是否确定是仅 sendFriendMessage？
> 这个异常目前发现是只在 peekMessage 的时候才会触发

我似乎是在 peekMessage 的同时 sendFriendMessage 才触发的这个，不过现在已经解决了，感谢回复。

**Comment by ryoii** [comment]
peekMessage等会操作到缓存队列的接口，在 `mah 2.0` 很有可能被移除
