### ISSUE TITLE
修改群成员资料时无操作权限但更改成功

### ISSUE THREAD

**Issue by WindLeaf233** [project-mirai/mirai-api-http#282]
我尝试 post /memberInfo 修改群里一位群成员的群名片, 机器人是管理员, 群成员是普通成员
发出了如下的请求:
```
{
    "sessionKey": "SessionKey",
    "target": xxxx,
    "memberId": xxxx,
    "info": {
        "name": "Hello World",
        "specialTitle": ""
    }
}
```
mirai-api-http 抛出了: code 10 无操作权限
但是实际上在群里已经更改成功了, 这是 bug 吗?

**Comment by WindLeaf233** [comment]
机器人更改自己的群名片也是这样

**Comment by WindLeaf233** [comment]
mirai-api-http: 1.9.8
mirai-core-all: 2.4.0
mirai-console-terminal: 2.4.0
mirai-console: 2.4.0
mirai-console-loader: 1.0.5

**Comment by ryoii** [comment]
因为填写了specialTitle字段，群头衔是群主才有的权限。群信息不是原子操作，没有事务回滚。情况就是群名片修改成功的，报错的是群头衔，不是bug

**Comment by WindLeaf233** [comment]
> 因为填写了specialTitle字段，群头衔是群主才有的权限。群信息不是原子操作，没有事务回滚。情况就是群名片修改成功的，报错的是群头衔，不是bug

明白了, 感谢
