### ISSUE TITLE
支持群员邀请群外进群

### ISSUE THREAD

**Issue by a55509432** [project-mirai/mirai-api-http#284]
![image](https://user-images.githubusercontent.com/5822725/111251052-734b9580-8649-11eb-86d8-1c8a4fc05551.png)

**Comment by karakoo** [comment]
欢迎加入催更大军

**Comment by StefanChang** [comment]
httpapi 邀请加入群聊的接口是什么？麻烦大佬指点下

**Comment by Him188** [comment]
> httpapi 邀请加入群聊的接口是什么？麻烦大佬指点下

不能邀请他人加入自己的群，只能处理来自他人的申请

**Comment by Drincann** [comment]
> httpapi 邀请加入群聊的接口是什么？麻烦大佬指点下

这种接口有点敏感吧

**Comment by a55509432** [comment]
> > httpapi 邀请加入群聊的接口是什么？麻烦大佬指点下
> 
> 不能邀请他人加入自己的群，只能处理来自他人的申请

是 core已经可以解释这个事件了，有了邀请人信息那些字段，但是对于api来说，因为日久失修~很多core的新功能，http-api都没有，其他插件还依赖htpp-api的协议，比如python版本的，这样就有点迷了

**Comment by ryoii** [comment]
`/resp/botInvitedJoinGroupRequestEvent` 印象中还是有的吧，如果这个接口有bug，请 reopen 该 issue，暂时关闭
