### ISSUE TITLE
接受不到用户添加好友和删除好友的消息

### ISSUE THREAD

**Issue by osanllyer** [project-mirai/mirai-api-http#286]
在mirai-console的日志中可以清楚看到已经打印了

2021-03-17 17:47:28 V/Bot.xxxxxxxx: Event: FriendAddEvent(friend=Friend(12345234234))
2021-03-17 17:47:39 V/Bot.xxxxxxxx: 美丽如风(12345234234) -> 你好

但是mirai-api-http中监听不到这个事件
请问是什么原因？

**Comment by HoshinoTented** [comment]
mah 将这个事件忽略掉了

**Comment by ryoii** [comment]
> mah 将这个事件忽略掉了

那你添加进去

**Comment by HoshinoTented** [comment]
> > mah 将这个事件忽略掉了
> 
> 那你添加进去

？

**Comment by HoshinoTented** [comment]
fixed in #287

**Comment by Karlatemp** [comment]
你不能等 pr 合了之后再 close 吗

**Comment by Him188** [comment]
@HoshinoTented 可以在 PR 里 link 一个 issue, PR merge 后就会自动 close 并保留引用

**Comment by HoshinoTented** [comment]
好的，我是傻逼
