### ISSUE TITLE
支持使用号与密码进行登录

### ISSUE THREAD

**Issue by steve02081504** [project-mirai/mirai-api-http#298]
https://github.com/cyanray/mirai-cpp/issues/90
以上？

**Comment by Doctor-Yin** [comment]
是否可以吧详细问题复制过来

**Comment by Drincann** [comment]
> [cyanray/mirai-cpp#90](https://github.com/cyanray/mirai-cpp/issues/90)
> 以上？

意义不大，因为登录通常需要手动验证，远程登录比较鸡肋，而且已有 api sendCommand 实现

**Comment by GreyElaina** [comment]
我记得我去年用 python-mirai v3 用 sendCommand 发 login, 爆了个 "该指令只能在控制台使用"

**Comment by ryoii** [comment]
支持从通过 command 相关接口给 console 发送指令，能否实现功能依赖 console 实现
