### ISSUE TITLE
支持发送XML消息

### ISSUE THREAD

**Issue by jupitersh** [project-mirai/mirai-api-http#299]
QQ卡片消息

**Comment by jupitersh** [comment]
突然发现支持的 失误

**Comment by Drincann** [comment]
话说 qq 的这种 xml、json 卡片消息，有相关格式规范的介绍文档吗？

**Comment by jupitersh** [comment]
> 话说 qq 的这种 xml、json 卡片消息，有相关格式规范的介绍文档吗？

刚刚试了 似乎发送不了

**Comment by karakoo** [comment]
> > 话说 qq 的这种 xml、json 卡片消息，有相关格式规范的介绍文档吗？
> 
> 刚刚试了 似乎发送不了

经测试，是可以发送的
请自行检查Json/XML消息格式是否正确或者自己的bot是否被风控

**Comment by Drincann** [comment]
> > > 话说 qq 的这种 xml、json 卡片消息，有相关格式规范的介绍文档吗？
> > 
> > 
> > 刚刚试了 似乎发送不了
> 
> 经测试，是可以发送的
> 请自行检查Json/XML消息格式是否正确或者自己的bot是否被风控

有 Json/XML 消息的相关资料吗？

**Comment by karakoo** [comment]
> > > > 话说 qq 的这种 xml、json 卡片消息，有相关格式规范的介绍文档吗？
> > > 
> > > 
> > > 刚刚试了 似乎发送不了
> > 
> > 经测试，是可以发送的
> > 请自行检查Json/XML消息格式是否正确或者自己的bot是否被风控
> 
> 有 Json/XML 消息的相关资料吗？

百度

**Comment by Drincann** [comment]
@karakoo 你似乎在以一种俯视的态度指责我。

我只是想问一问有没有这种消息规范的介绍文档，这种资料我确实没有找到，大多是零碎的低水平的只言片语。

mirai 社区个个都是人才，说话又好听，所以在这碰碰运气。

**Comment by karakoo** [comment]
> @karakoo 你似乎在以一种俯视的态度指责我。
> 
> 我只是想问一问有没有这种消息规范的介绍文档，这种资料我确实没有找到，大多是零碎的低水平的只言片语。
> 
> mirai 社区个个都是人才，说话又好听，所以在这碰碰运气。

并没有高高在上，网上这方面的资料都很零碎或者已经过时，大多开发者都是自己摸爬滚打出来的，并且没有统一的规范。
所以只能靠自己百度

**Comment by jupitersh** [comment]
我发送xml后，没有报错，但是没有收到消息，是被风控了吗

**Comment by karakoo** [comment]
> 我发送xml后，没有报错，但是没有收到消息，是被风控了吗

你可以试试将小程序的分享消息的Json/XML代码发送出去试试看，发不出去就是被风控了，如果发得出去，那就有可能XML格式有问题，或者该XML格式被封禁了（有的XML消息以前可以发，现在没法发了）
