### ISSUE TITLE
关于文件上传 API 的一点点迷惑

### ISSUE THREAD

**Issue by GreyElaina** [project-mirai/mirai-api-http#303]
mah 目前有了由 @Doctor-Yin 贡献的初步文件操作 API, 但是这个上传文件的 endpoint 有点迷惑.

> [POST] /uploadFileAndSend

虽然确实有给对面发信息提示有文件接受, 但我认为直接 `uploadFile` 可能更好点.

**Comment by Him188** [comment]
mirai-core 内是这样设计的, 之后有可能还会提供 `uploadImage` 获得 `FileMessage` 而不发送

**Comment by Doctor-Yin** [comment]
试过uploadFile，但是他报错

**Comment by Him188** [comment]
> 试过uploadFile，但是他报错

报的是什么错

**Comment by GreyElaina** [comment]
> mirai-core 内是这样设计的, 之后有可能还会提供 `uploadImage` 获得 `FileMessage` 而不发送

hmm? 那 tx 这种操作有点迷惑...

嗯...或许可以考虑改成获取 query 参数? 比如这样

> /uploadFile?sendmsg=false

**Comment by Doctor-Yin** [comment]
忘了....
