### ISSUE TITLE
文件上传API 返回“参数格式错误”

### ISSUE THREAD

**Issue by yeheigcy** [project-mirai/mirai-api-http#305]
![image](https://user-images.githubusercontent.com/23069540/113806771-83145080-9795-11eb-9817-580aa107fd11.png)

这里是不是缺了个 target

**Comment by yeheigcy** [comment]
![image](https://user-images.githubusercontent.com/23069540/113809462-bc02f400-979a-11eb-835e-e6d100a93e9a.png)

加上target后可以成功调用，但是返回“无操作权限”
群已开启 允许全体成员上传群文件

**Comment by yeheigcy** [comment]
如果 path 只传文件名，第一次调用会返回404，群文件会创建一个该文件名的文件夹
![image](https://user-images.githubusercontent.com/23069540/113809863-9aeed300-979b-11eb-943d-e1e420451c65.png)
![image](https://user-images.githubusercontent.com/23069540/113809881-a641fe80-979b-11eb-8857-33c8af77bda3.png)
再次调用可以成功上传文件
![image](https://user-images.githubusercontent.com/23069540/113809963-d5587000-979b-11eb-8a98-1fcef3f26bd5.png)
![image](https://user-images.githubusercontent.com/23069540/113810000-e6a17c80-979b-11eb-896b-a13ce14df346.png)

**Comment by Doctor-Yin** [comment]
创建文件夹要管理员权限的

**Comment by Doctor-Yin** [comment]
我应该少写根目录判断了
