### ISSUE TITLE
文件上传并发送(uploadFileAndSend) 响应 404 Not Found

### ISSUE THREAD

**Issue by cyanray** [project-mirai/mirai-api-http#306]
按照文档提示发送请求，响应 404 NotFound

![QQ截图20210407121707](https://user-images.githubusercontent.com/13616289/113809849-975b4c00-979b-11eb-85e3-d45b2a0c1d2a.png)

虽然响应 404，但是依然创建了一个名为 test.png 的文件夹，该文件夹为空。（可能是我的 path 填写有误或者 mah 没有正确地创建不存在的文件夹？）

保留这个文件夹，再次提交同样的请求，就能把文件上传到根目录。

![QQ截图20210407102914](https://user-images.githubusercontent.com/13616289/113809850-97f3e280-979b-11eb-8d00-3d9ae173cdae.png)

如上图所示，我对 test、 test.png、c.pdf 都提交了两次才成功。第一次只会创建文件夹，而且响应 404（响应内容空白）。当同名文件夹存在时，文件才会被上传，有正确的 200 响应。

**Comment by Doctor-Yin** [comment]
path为根目录时只写文件名就可以了

**Comment by Doctor-Yin** [comment]
否则会去创建文件夹

**Comment by Doctor-Yin** [comment]
我的问题，少写穿根目录文件的判定了
