### ISSUE TITLE
每次发布的时候 注明 所支持的 mirai 版本

### ISSUE THREAD

**Issue by gitlsl** [project-mirai/mirai-api-http#312]
有个建议：
  跟 mirai 版本号保持一致   或者  注明 所支持的 mirai 版本 ， 这样用户一看就知道了~

**Comment by Him188** [comment]
一般是建议使用最新版。以后插件中心做好后会带版本号发布

**Comment by ryoii** [comment]
除了最新几个包不是我发的，我的release log里都标注的core的依赖版本
