### ISSUE TITLE
[建议] 能否给文件消息添加 url 成员

### ISSUE THREAD

**Issue by Excaive** [project-mirai/mirai-api-http#313]
目前图片和语音可以直接获取 url ，而文件需要通过 groupFileInfo 才能得到 url

**Comment by Him188** [comment]
文件列表从服务器拉下来默认是没有 URL 的, 要单独发一个包去查询, 所以就没有带 URL. 而根据经验, 发包频繁会被服务器拒绝. 所以就没有默认带 URL 了.

**Comment by Doctor-Yin** [comment]
你是上传文件，不是下载文件啊，感觉这是想把QQ群当成云盘的意思了
