### ISSUE TITLE
能否提供"path 到 id "或"path 到 fileInfo 的接口"？

### ISSUE THREAD

**Issue by Drincann** [project-mirai/mirai-api-http#317]
感觉目前文件操作的 api 有些麻烦。

如果需要通过路径直接操作文件或目录，则需要：
- 首先处理路径字符串，分离目录、文件名（可能还是个目录）
- 遍历返回的数组，拿到 id
- 执行文件操作

此外还要额外处理给定的路径是目录还是文件的问题

**Comment by Him188** [comment]
服务器允许目录和文件重名，也允许存在名称相同的多个文件。因此移动操作需要用 id 完成才能精确

**Comment by Him188** [comment]
可以考虑加一个通过 path 进行不精确操作的方式

**Comment by Doctor-Yin** [comment]
> 感觉目前文件操作的 api 有些麻烦。
> 
> 如果需要通过路径直接操作文件或目录，则需要：
> 
> * 首先处理路径字符串，分离目录、文件名（可能还是个目录）
> * 遍历返回的数组，拿到 id
> * 执行文件操作
> 
> 此外还要额外处理给定的路径是目录还是文件的问题

是不是文件名的返回不需要带path，我忘记我咋写的了

**Comment by Drincann** [comment]
> 是不是文件名的返回不需要带path，我忘记我咋写的了

没看懂你在说什么。。

**Comment by Doctor-Yin** [comment]
> > 是不是文件名的返回不需要带path，我忘记我咋写的了
> 
> 没看懂你在说什么。。

需要模糊移动功能对吧，我没理解错的话

**Comment by Drincann** [comment]
> 需要模糊移动功能对吧，我没理解错的话

需要根据 path 拿到 id（可能是多个） 进行后续操作的能力。

目前想要操作具体文件/目录必须遍历上层 dir，而且面对很多文件的目录时请求效率非常差。

不太清楚 mah 的实现是否存在更细粒度的接口来优化效率。

**Comment by Him188** [comment]
> > 需要模糊移动功能对吧，我没理解错的话
> 
> 需要根据 path 拿到 id（可能是多个） 进行后续操作的能力。
> 
> 目前想要操作具体文件/目录必须遍历上层 dir，而且面对很多文件的目录时请求效率非常差。
> 
> 不太清楚 mah 的实现是否存在更细粒度的接口来优化效率。

服务器允许目录和文件重名，也允许存在名称相同的多个文件。因此移动操作需要用 id 完成才能精确

如果要提供基于 path 的，操作时也是在 mirai-core 遍历一次找 path 然后也不能确定目标文件是哪个

可以加一个操作全部 path matching 的目标

**Comment by Drincann** [comment]
> > > 需要模糊移动功能对吧，我没理解错的话
> > 
> > 
> > 需要根据 path 拿到 id（可能是多个） 进行后续操作的能力。
> > 目前想要操作具体文件/目录必须遍历上层 dir，而且面对很多文件的目录时请求效率非常差。
> > 不太清楚 mah 的实现是否存在更细粒度的接口来优化效率。
> 
> 服务器允许目录和文件重名，也允许存在名称相同的多个文件。因此移动操作需要用 id 完成才能精确
> 
> 如果要提供基于 path 的，操作时也是在 mirai-core 遍历一次找 path 然后也不能确定目标文件是哪个
> 
> 可以加一个操作全部 path matching 的目标

明白了，那还是让调用者负责实现吧

操作全部的应该没有什么必要性

**Comment by Him188** [comment]
也可以提供一个如果 path 能精确 match 就操作, 不能就返回失败的接口. 但这样似乎用户还是要处理失败的情况, 所以不如就只支持 ID 了. 但用户通常自己也不知道同名 path 的文件有什么区别.....

**Comment by ryoii** [comment]
支持不保证准确性的 path 参数
