### ISSUE TITLE
WS:/event 群名片改动事件不提供Operator

### ISSUE THREAD

**Issue by forpleuvoir** [project-mirai/mirai-api-http#319]
![image](https://user-images.githubusercontent.com/38557552/115149917-ca091c80-a098-11eb-8a6a-f4b53f43222a.png)
![image](https://user-images.githubusercontent.com/38557552/115149946-ddb48300-a098-11eb-8861-df9f124d8df1.png)

**Comment by Him188** [comment]
这个事件好像服务器就没有提供 operator

**Comment by ryoii** [comment]
大概是之后从core中被移除了

**Comment by ryoii** [comment]
确实已经移除了，新接口将同步移除这个字段
