### ISSUE TITLE
关于文档的两点建议

### ISSUE THREAD

**Issue by XSun771** [project-mirai/mirai-api-http#323]
首先感谢作者的工作。

1. 插件还支持多账号登录吗？我在项目README和api.md中用“多账号”为关键字搜索，没有相关的内容。如果还支持的话能否补充一下配置文件设置方法以及实际操作方法？

2. 关于配置文件中的host和port配置项，我一开始是理解为事件上报的程序所在的IP和监听的端口，能不能再详细点说是mirai-api-http所在的IP和监听的端口？上报里的，能否进一步说明其规范？

另外关于destinations配置项，如果想让事件发给 http://localhost:8081/report 的话，那么 destinations 配置项应该写 http://localhost:8081/report 对吗？

谢谢！

**Comment by Him188** [comment]
2.0 重构进行中，@ryoii

**Comment by Drincann** [comment]
多账号登录是 mirai-console 的工作，准确说来，mirai-api-http 负责的是多账号绑定，绑定即将 /auth 得到的 session /verify 到一个已登录的 qq 号的过程

**Comment by XSun771** [comment]
> 多账号登录是 mirai-console 的工作，准确说来，mirai-api-http 负责的是多账号绑定，绑定即将 /auth 得到的 session /verify 到一个已登录的 qq 号的过程

谢谢解答。随便问下消息类型里的FlashImage是那种5秒后自动销毁的闪照么？

**Comment by Him188** [comment]
> > 多账号登录是 mirai-console 的工作，准确说来，mirai-api-http 负责的是多账号绑定，绑定即将 /auth 得到的 session /verify 到一个已登录的 qq 号的过程
> 
> 谢谢解答。随便问下消息类型里的FlashImage是那种5秒后自动销毁的闪照么？

是的
