### ISSUE TITLE
如何通过API进行登录?

### ISSUE THREAD

**Issue by xwh1108** [project-mirai/mirai-api-http#325]
已经参考过 https://github.com/project-mirai/mirai-login-solver-selenium 
命令行模式下可以进行相关交互,那api模式呢,有没有后续的考虑计划?

**Comment by Him188** [comment]
没有

**Comment by xwh1108** [comment]
> 没有

那必须在命令行模式下进行验证码登录后才可以使用后续API吗?

**Comment by Him188** [comment]
> > 没有
> 
> 那必须在命令行模式下进行验证码登录后才可以使用后续API吗?

目前来说是的

**Comment by xwh1108** [comment]
> > > 没有
> > 
> > 
> > 那必须在命令行模式下进行验证码登录后才可以使用后续API吗?
> 
> 目前来说是的

🙏感谢解答,最后问一下后续真的没有开发计划吗QAQ

**Comment by Him188** [comment]
处理验证码只能本地处理，那么就没有做 HTTP API 的必要了

**Comment by xwh1108** [comment]
> 处理验证码只能本地处理，那么就没有做 HTTP API 的必要了

但是如果我需要用HTTP API 进行 /login 然后出现了验证码相关提示 同时也在本地完成了验证 无法继续进行交互
这就很尴尬了

**Comment by Karlatemp** [comment]
`/login` 这种敏感操作是不太应该使用 api 调用的，从安全性来说应该不允许 API 调用 `/login` 的

**Comment by xwh1108** [comment]
> `/login`这种敏感操作是不太应该使用api调用的，从安全性来说应该中断API调用`/login`的

在大多数应用层面,可能我更需要API来完成这个操作,而不是登上命令行来完成这个操作😊因为如果我有多个bot需要动态管理,只能去集成Mirai而Http插件不能使用

**Comment by Him188** [comment]
可以在 MAH 2 考虑 @ryoii

**Comment by xwh1108** [comment]
感谢解答😊
