### ISSUE TITLE
电脑版连续发送两次图片后出现 message is empty 错误

### ISSUE THREAD

**Issue by langyo** [project-mirai/mirai-api-http#326]
[这是日志](https://gist.github.com/langyo/ebbcb384e92628d728d2dd66425db42f)

引自 https://github.com/mamoe/mirai/issues/1209

当 mirai-api-http 连续接收到两次单独的图片消息时，就会发生这个错误，而且很容易复现、能够反复复现——只要随便发两个不同的图片就行了

使用电脑版 QQ，手机版 QQ 没有问题

使用的客户端是 [mirai-ts](https://github.com/YunYouJun/mirai-ts)

![image](https://user-images.githubusercontent.com/23103705/116226429-8ba0eb00-a785-11eb-9ef8-41b9481eae09.png)

![image](https://user-images.githubusercontent.com/23103705/116226475-978cad00-a785-11eb-8eb8-f5fc3d5c8afd.png)

@sandtechnology @Him188

**Comment by Him188** [comment]
@ryoii mah 2 怎么样？

**Comment by ryoii** [comment]
从请求参数上看，你确实传了空字符串，
```json
{
  "messageChain": [{"type": "plain", "text": ""}]
}
```

Mirai core的源码中有限制
```kotlin
override suspend fun sendMessage(message: Message): MessageReceipt<Group> {
        require(!message.isContentEmpty()) { "message is empty" }
        check(!isBotMuted) { throw BotIsBeingMutedException(this) }
```

检查是否 `mirai-ts` 在发送两次图片后自动发送了一次这样的空字符串消息
