### ISSUE TITLE
事件上报导致消息丢失

### ISSUE THREAD

**Issue by Asyfish** [project-mirai/mirai-api-http#327]
version 1.10.0
具体表现为：
开启事件上报情况下，bot短时间内接收大量消息时，上报时会丢失部分消息；如果同时链接了ws，ws client收到的消息也会丢失同一部分；mcl控制台也会丢失这一部分消息；关闭上报就正常了。
PC客户端收到的消息是正常的，所以确认消息已经发送成功。

**Comment by ryoii** [comment]
mcl控制台也丢失了，应该是 `core` 没有解到这个包 @Him188

**Comment by Him188** [comment]
私聊消息确实会丢

**Comment by Asyfish** [comment]
> 私聊消息确实会丢

请问有修复的计划吗，不行我就搭ws中间件了
