### ISSUE TITLE
一直报"上报http失败: Client request(http://localhost/http) invalid: 404 Not Found"

### ISSUE THREAD

**Issue by Sunosay** [project-mirai/mirai-api-http#328]
不好意思刚接触不太懂.已经在config\net.mamoe.mirai-api-http\setting中配置了路径,但是一直报错.
![image](https://user-images.githubusercontent.com/59289264/116554278-96967f80-a92d-11eb-8742-2db8af4ae867.png)

那个路径就是启了一个普普通通的web项目

**Comment by ryoii** [comment]
报啥错麻烦发一下

**Comment by Sunosay** [comment]
> 报啥错麻烦发一下

 E/net.mamoe.mirai-api-http: 上报http失败: Failed to connect to localhost/127.0.0.1:80
啥也没动 今天重启换了个报错=-=

**Comment by Asyfish** [comment]
yml格式问题，网址要加引号

**Comment by Sunosay** [comment]
> yml格式问题，网址要加引号

谢谢老哥 整好了
