### ISSUE TITLE
某些消息接受不到

### ISSUE THREAD

**Issue by dalaoshus** [project-mirai/mirai-api-http#330]
[土匪你好包子] 这句话在群里发送，mirai控制台不会显示，并且通过api接口也发不出去。

**Comment by Him188** [comment]
mirai-core 问题，试试更新 2.6.3

**Comment by dalaoshus** [comment]
> mirai-core问题，试试更新2.6.3

更新后还是一样

**Comment by Him188** [comment]
发不出去的返回是什么, 是错误还是成功

提供控制台日志

**Comment by dalaoshus** [comment]
> 发不出去的返回是什么，是错误还是成功
> 
> 提供控制台日志

机器人发这条信息，控制台是正常的，返回已经发出去了。
但群里没有那条信息。

**Comment by dalaoshus** [comment]
> 发不出去的返回是什么，是错误还是成功
> 
> 提供控制台日志

貌似日志里面没有记录
![Uploading IMG_20210504_142750.jpg…]()

**Comment by ryoii** [comment]
控制台无消息一般是风险控制或者 mirai core 的处理异常。先尝试在 mirai core 解决，我先关闭 issue，还有问题再重新打开
