### ISSUE TITLE
支持其他设备消息 (OtherClientMessageEvent)

### ISSUE THREAD

**Issue by Creedowl** [project-mirai/mirai-api-http#331]
例如我mirai采用ANDROID_PAD协议登录，在windows端向“我的PAD”发送消息，在mirai-console里面可以看到对应的消息，但mirai-api-http收不到这个消息。
此外也希望能添加功能向其他设备发送消息，我想要实现一个向自己推送消息的功能

**Comment by ryoii** [comment]
安排
