### ISSUE TITLE
能否给群中上传文件添加一个判断的返回值

### ISSUE THREAD

**Issue by DongShaoNB** [project-mirai/mirai-api-http#333]
在群内上传文件ws返回
{'type': 'GroupMessage', 'messageChain': [{'type': 'Source', 'id': xxx, 'time': xxx}], 'sender': {'id': xxx, 'memberName': 'xxx', 'permission': 'OWNER', 'group': {'id': xx, 'name': 'xx', 'permission': 'ADMINISTRATOR'}}}
建议在返回的数据中加上type: UploadFile这种方便判断，例如:
{'type': 'GroupMessage', 'messageChain': [{'type': 'Source', 'id': xxx, 'time': xxx}, {'type': 'UploadFile', 'text': '1'}], 'sender': {'id': xxx, 'memberName': 'xxx', 'permission': 'OWNER', 'group': {'id': xx, 'name': 'xx', 'permission': 'ADMINISTRATOR'}}}

**Comment by ryoii** [comment]
群文件上传的消息卡片也会出发消息事件？@Him188

**Comment by ryoii** [comment]
现在版本似乎Bot上传文件时不会触发消息事件
