### ISSUE TITLE
希望增加获取漫游消息的功能

### ISSUE THREAD

**Issue by Blackbytes-max** [project-mirai/mirai-api-http#338]
因为我在试着用mirai-api-http制作一个QQ客户端，所以如果好友在mirai启动前发了消息，mirai启动后却接收收不到会是个很麻烦的问题。所以希望增加获取漫游消息的功能

**Comment by aion1998** [comment]
..建议自己存数据库吧

**Comment by Blackbytes-max** [comment]
mirai启动后收到的消息确实可以用插件备份到数据库，但如果是在mirai启动前有未读消息，通过mirai-api-http获取不到这部分消息。

**Comment by Him188** [comment]
需要等待 core 支持: https://github.com/mamoe/mirai/issues/1265
