### ISSUE TITLE
发送转发消息提示格式错误，对照API对了很久，不知道错在哪了，同样分享歌曲也是一样的问题

### ISSUE THREAD

**Issue by duan649953543** [project-mirai/mirai-api-http#344]
r = requests.post(sendGroupMessage_url, json={
            "sessionKey": session,
            "target": group_id,
            "messageChain":
                [{
                    "type": "Forward",
                    "title": "群聊的聊天记录",
                    "brief": "[聊天记录]",
                    "source": "聊天记录",
                    "summary": "查看 3 条转发消息",
                    "nodeList": [
                        {
                            "senderId": 1141337272,
                            "time": 1436428326,
                            "senderName": "热夏",
                            "messageChain": [
                                {"type": "Image", "path": "001.jpg"}
                            ]
                        },
                        {
                            "senderId": 1141337272,
                            "time": 1436428327,
                            "senderName": "热夏",
                            "messageChain": [
                                {"type": "Image", "path": "001.jpg"}
                            ]
                        }
                    ]
                }]

**Comment by ryoii** [comment]
你发上来的 json 格式都已经不对了

**Comment by duan649953543** [comment]
![image](https://user-images.githubusercontent.com/61350318/118347301-c8862380-b574-11eb-96df-ac2cde715b47.png)

**Comment by duan649953543** [comment]
> 你发上来的 json 格式都已经不对了

![image](https://user-images.githubusercontent.com/61350318/118347309-d8056c80-b574-11eb-9d35-6b29246e989f.png)

**Comment by ryoii** [comment]
具体报错信息是什么

**Comment by duan649953543** [comment]
> 具体报错信息是什么

![image](https://user-images.githubusercontent.com/61350318/118347436-ebfd9e00-b575-11eb-840c-3cf4c3652f46.png)

**Comment by ryoii** [comment]
印象中新版本不是这样的消息提示，你是不是用的是 1.x 版本，1.x 没有转发消息

**Comment by duan649953543** [comment]
> 印象中新版本不是这样的消息提示，你是不是用的是 1.x 版本，1.x 没有转发消息

![image](https://user-images.githubusercontent.com/61350318/118347627-43e8d480-b577-11eb-8c8f-46447459d261.png)
是这个版本

**Comment by duan649953543** [comment]
> 印象中新版本不是这样的消息提示，你是不是用的是 1.x 版本，1.x 没有转发消息

噢 我更新一下试试

**Comment by Doctor-Yin** [comment]
好像是1.11才有的

**Comment by duan649953543** [comment]
> 印象中新版本不是这样的消息提示，你是不是用的是 1.x 版本，1.x 没有转发消息

谢谢大哥

**Comment by duan649953543** [comment]
> 好像是1.11才有的

恩恩
