### ISSUE TITLE
注册指令为什么要关掉

### ISSUE THREAD

**Issue by SomeoneDeng** [project-mirai/mirai-api-http#350]
<img width="1643" alt="QQ20210522-002741@2x" src="https://user-images.githubusercontent.com/16154699/119169598-c8b28180-ba94-11eb-8dcf-f68e4081be4b.png">
是由什么原因吗

**Comment by ryoii** [comment]
因为 `console` 的指令系统在 2.0 的时候进行过一次很大的升级，之后一直没有进行适配。指令相关的接口使用的是旧的 API，不禁用也是报错
