### ISSUE TITLE
WebSocket 多次推送同一个事件（或消息）

### ISSUE THREAD

**Issue by cyanray** [project-mirai/mirai-api-http#356]
## 表现
如果有新的消息或者事件，ws 会重复推送多次，重复次数和 bind 账号后的 Session 数有关。

## 复现步骤
1. 使用 http api， verify、bind 若干个 session；
2. 通过 `ws://localhost:8080/all?verifyKey=VerifyKey&sessionKey=fbQwfQiC` 复用上一个步骤的某一个 Session 获取消息和事件；
3. 如果有新事件(或新消息)，mah 会重复推送该事件(或消息)若干次，次数等同于 bind 账号后的 Session 个数。

**Comment by ryoii** [comment]
你怎么好像绕过了一个奇怪的bug，目前 http 生成的 session 应该是不能在 ws 里使用的

**Comment by Simon-Chenzw** [comment]
> 你怎么好像绕过了一个奇怪的bug，目前 http 生成的 session 应该是不能在 ws 里使用的

在不使用http的情况下也会出现多次发送的现象
与 `"ws://127.0.0.1:12345/all?verifyKey=key&qq=12345"`
链接，断开，再次链接，就可复现复读现象

我使用的链接代码
```python
import websockets
import asyncio
import logging

logging.basicConfig(level=0)

async def main():
    # pylint: disable=no-member
    async with websockets.connect(  # type: ignore
            "ws://127.0.0.1:12345/all?verifyKey=key&qq=12345"
    ) as ws:
        for i in range(5):
            print(await ws.recv())
        await ws.close()

asyncio.run(main())
```

**Comment by STDSuperman** [comment]
同求解决方案，一直给我推重复消息很多条

**Comment by Simon-Chenzw** [comment]
在建立websocket持续链接的情况下，使用http进行verify、release多次之后，也会产生大量复读

**Comment by STDSuperman** [comment]
你现在有解决方案了么，我这边准备用hash的方式去重了。。。

**Comment by Simon-Chenzw** [comment]
> 你现在有解决方案了么，我这边准备用hash的方式去重了。。。

如果是消息的话，可以按照Source id的方式过滤
事件我打算直接ban掉，只用message channel

**Comment by STDSuperman** [comment]
> > 你现在有解决方案了么，我这边准备用hash的方式去重了。。。
> 
> 如果是消息的话，可以按照Source id的方式过滤
> 事件我打算直接ban掉，只用message channel

我这边目前主要监听的message通道，暂时没有涉及事件，一劳永逸估计还是加个hash

**Comment by ryoii** [comment]
已经解决了，等我发个版

**Comment by ryoii** [comment]
已经解决了，等我发个版

**Comment by STDSuperman** [comment]
> 已经解决了，等我发个版

好的感谢，发好了麻烦告知一致版本。。
