### ISSUE TITLE
支持 Docker 无间断运行

### ISSUE THREAD

**Issue by wzxinchen** [project-mirai/mirai-api-http#364]
目前如果服务器重启或ssh断开的话，需要手动重新登录账号，希望后面可以做到自动登录账号（或者已经有了？）

**Comment by ryoii** [comment]
这个超出插件的职责了。

mirai console 支持自动登录，配置容器时设置支持 restart 就好了

**Comment by zouhy2001** [comment]
> 目前如果服务器重启或ssh断开的话，需要手动重新登录账号，希望后面可以做到自动登录账号（或者已经有了？）

配置下auto login就好了，设置每次重启时，运行mcl就OK了。
