### ISSUE TITLE
mirai-api-http-v2.0.2上传图片时返回code3:Session失效或不存在

### ISSUE THREAD

**Issue by yuejieyao** [project-mirai/mirai-api-http#365]
在正常verify和bind后,调用上传图片接口会返回
```
{
"code": 3,
"msg": "Session失效或不存在"
}
```

但是调用其他如发送群消息等接口是正常的

**Comment by cyanray** [comment]
遇到了同样的问题，无法上传图片。

**Comment by ryoii** [comment]
是否通过请求头传递的sessionKey

**Comment by yuejieyao** [comment]
> 是否通过请求头传递的sessionKey

这里是我的python代码片段, 另外使用API Tester是一样的情况,其他接口正常,上传图片就这样

`        multipart_encoder = MultipartEncoder(
            fields={
                'sessionKey': self.httpRequest.sessionKey,
                'type': image_type,
                'img': (os.path.basename(file_path),
                        open(file_path, 'rb'), 'application/octet-stream')
            },
            boundary='-----------------------------' +
            str(random.randint(1e28, 1e29 - 1))
        )

        headers = {'Content-Type': multipart_encoder.content_type}
        response = self.httpRequest.request.post(
            '%s/%s' % (self.httpRequest.host, 'uploadImage'), data=multipart_encoder, headers=headers)
        response.raise_for_status()
        return json.loads(response.text)['imageId']`

**Comment by ryoii** [comment]
看你代码里 POST Form 里没有传递 sessionKey，导致找不到对应的 session

[接口定义](https://github.com/project-mirai/mirai-api-http/blob/master/docs/adapter/HttpAdapter.md#%E5%9B%BE%E7%89%87%E6%96%87%E4%BB%B6%E4%B8%8A%E4%BC%A0)

header 传递的 sessionKey 确实丢失了，但是从 form 参数传上来的应该不受影响

**Comment by Goodjooy** [comment]
我使用1.12.0时图片上传正常

同样数据在2.0.2时显示Session不存在或者无效

**Comment by ryoii** [comment]
修复了，等明天发版

**Comment by Godmyhave** [comment]
> 修复了，等明天发版

你好，我的代码也报了这个错误。
![image](https://user-images.githubusercontent.com/59076131/134781748-a6ad4b6c-e4ee-4c2e-be70-3cdfd7dd07c8.png)
{'code': 3, 'msg': 'Session失效或不存在'}
请问是什么原因呢？
