### ISSUE TITLE
部分时候机器人无法发出群消息，但是后台显示已发送

### ISSUE THREAD

**Issue by Awoodwhale** [project-mirai/mirai-api-http#366]
不知道是不是因为我仍然在使用1.11.0的版本的缘故，部分时候机器人的消息在后台显示已发送，但是在群内无法看见。

**Comment by ryoii** [comment]
大概率是 core 的问题，尝试好友私聊能不能发

一般情况下，bot 多挂一段时间就可以发出去了

**Comment by DaGuoZhang** [comment]
考虑还有一种可能，看看会不会是机器人被腾讯风控的原因，被风控不会给你通知，但会导致消息无法正常发送至群内，私聊不影响，换个QQ试试。

**Comment by Awoodwhale** [comment]
> 大写公司核心，本色酷酷的副科雷克·卡本·卡本
> 
> 第二个程序，机器人大元香

**Comment by willhuo** [comment]
最后怎么解决的，我现在也遇到了，QQ群发消息，群收不到的情况
