### ISSUE TITLE
ws 连接一段时间后就无法收到消息

### ISSUE THREAD

**Issue by sxd1140** [project-mirai/mirai-api-http#368]
2.0.2
/all
singleMode

一开始能收到 过了几分钟就无法收到通知

console里能看到mirai收到了消息 但是websocket这边没收到

请问我要怎么排查 ws adapter部分有调试开关或者打印什么的内容么

**Comment by ryoii** [comment]
大概是多久触发，我复现一下

**Comment by sxd1140** [comment]
10分钟必现, 替换成2.0rc2 也是一样

好像以前在本地开发的时候没有出现过这种现象

现在是部署到阿里云上去了, 外部程序是在本地跑

**Comment by sxd1140** [comment]
2.0 ws adapter现在有心跳么

**Comment by ryoii** [comment]
逻辑上没有心跳也不需要心跳

**Comment by ryoii** [comment]
![9KL_X7P_M~ DW9$3VHD5@9V](https://user-images.githubusercontent.com/28707253/122564571-17ddd900-d078-11eb-81fd-e1891a576aa8.png)

没有这个问题，网络环境复杂。大概是各种路由节点、服务防火墙对长时间无数据传输的 tcp 连接进行了主动关闭。

ws adapter 没有专门的心跳机制，通过 tcp 默认的 120 分钟 KEEPALIVE 维持长连接。你可以主动发一些无用的数据到 ws adapter 里，插件没有正确解析，也不会有任何额外的操作

**Comment by sxd1140** [comment]
嗯 现在间隔发了一段时间 没断了 谢谢
