### ISSUE TITLE
功能请求：群员头像获取

### ISSUE THREAD

**Issue by STDSuperman** [project-mirai/mirai-api-http#371]
从1.x 等到 2.x 还是没等到怎么获取群员头像或者联系人头像 QAQ。

后续是否有打算支持这项能力呢

**Comment by ryoii** [comment]
每个 qq 对象都带这个字段比较繁琐，其实QQ的头像是公开的

```
http://q1.qlogo.cn/g?b=qq&nk=${qq}&s=640
```

**Comment by STDSuperman** [comment]
> 每个 qq 对象都带这个字段比较繁琐，其实QQ的头像是公开的
> 
> ```
> http://q1.qlogo.cn/g?b=qq&nk=${qq}&s=640
> ```

哇感谢感谢
