### ISSUE TITLE
机器人是svip的状态仍无法发长语音

### ISSUE THREAD

**Issue by djkcyl** [project-mirai/mirai-api-http#376]
![image](https://user-images.githubusercontent.com/59153990/122863616-b064a980-d355-11eb-850f-3059355aec22.png)
![image](https://user-images.githubusercontent.com/59153990/122863628-b5295d80-d355-11eb-9161-f3026cf7d52a.png)
http版本号是1.10.0

**Comment by djkcyl** [comment]
而且这个音质，一言难尽（
只能发2分10秒内的，不然电脑时间都会叹号，2分钟的电脑有时候是叹号，手机不会叹号，挺奇怪的
![image](https://user-images.githubusercontent.com/59153990/122865183-882a7a00-d358-11eb-9590-24b803ae73cd.png)

**Comment by ryoii** [comment]
查看 core 版本，功能由 core 提供的

**Comment by djkcyl** [comment]
> 查看 core 版本，功能由 core 提供的

core是2.6.6

**Comment by djkcyl** [comment]
不会是因为我用的graia不支持吧

**Comment by ryoii** [comment]
大概是这个问题，可以持续关注这个 issue

https://github.com/mamoe/mirai/issues/940#issue-797649863

**Comment by djkcyl** [comment]
那长语音的问题要怎么解决呢，现在我最多发2分10秒的silkv3格式音频，而且有小概率电脑和手机都播不了，我看QQ会员的介绍写的超级会员可以发5分钟的语音来着

**Comment by ryoii** [comment]
你在core仓库里开个issue，这种问题不是api调错的造成的

**Comment by djkcyl** [comment]
> 你在core仓库里开个issue，这种问题不是api调错的造成的

好的

**Comment by djkcyl** [comment]
看来还是这边的问题
https://github.com/mamoe/mirai/issues/1367
graia发送的过程我也不知道是什么，不太看得明白

**Comment by djkcyl** [comment]
![image](https://user-images.githubusercontent.com/59153990/123502268-a99fa480-d67d-11eb-9fa6-ac1284130ee0.png)

**Comment by Karlatemp** [comment]
https://github.com/project-mirai/mirai-api-http/blob/e885371da9a31b299098aa08d721361ea9bd2b7b/mirai-api-http/src/main/kotlin/net/mamoe/mirai/api/http/adapter/internal/convertor/convertor.kt#L112-L119

**Comment by djkcyl** [comment]
> https://github.com/project-mirai/mirai-api-http/blob/e885371da9a31b299098aa08d721361ea9bd2b7b/mirai-api-http/src/main/kotlin/net/mamoe/mirai/api/http/adapter/internal/convertor/convertor.kt#L112-L119

所以说我得怎么解决这个问题呃

**Comment by ryoii** [comment]
代码中，仅通过 voiceId 发送时调用了不稳定的参数，如果你是通过 流、url、base64 发送的语音文件，在此处不影响

**Comment by I-love-study** [comment]
补充一下可能对解决该issue有帮助的一些信息

当我使用Graia发送语音(格式为Silk)的时候，我会惊奇的发现发送的Silk格式变成了amr格式，并且音质极差(5kbps)
发送的silk音频确认是silkv3:
![image](https://user-images.githubusercontent.com/39652142/126908834-11468026-d497-40de-8f3f-ff3ef1253896.png)
通过另外一个mirai接收到的语音:
![image](https://user-images.githubusercontent.com/39652142/126908461-845ab148-e6a3-428c-a90c-76e3c6eed0b8.png)
然后当我尝试发送amr的时候，无论是amr_wb还是amr_nb，都会在客户端(TIM电脑，安卓手机QQ)显示感叹号

但是当我在使用mirai社区插件[khjxiaogu/MiraiSongPlugin](https://github.com/khjxiaogu/MiraiSongPlugin)来获取音乐的时候，却可以通过其中的命令获取指定到silk和amr语音。

附上上文提及的音频文件[test.zip](https://github.com/project-mirai/mirai-api-http/files/6874322/test.zip)
当前使用的mirai版本是2.7-M2，mah版本是1.12.0

**Comment by ArcticLampyrid** [comment]
Graia似乎总是会调用`uploadVoice`然后使用`voiceId`发送
可能的原因：
`uploadVoice`中并没有提供正确的群号（mah使用的是`groups.firstOrNull()`）
https://github.com/project-mirai/mirai-api-http/blob/cdac1c4f360bd7718698ca9fabb38910fe9b4528/mirai-api-http/src/main/kotlin/net/mamoe/mirai/api/http/adapter/internal/action/message.kt#L186

注：未验证

**Comment by ArcticLampyrid** [comment]
@ryoii 

分析
----
**前置条件：Graia总是会调用`uploadVoice`然后使用`voiceId`发送**
通过 voiceId 发送时构造的 `Voice` 缺失了 `fileSize` `codec` `url` 等参数
**缺失`codec`参数（fallback to `0`）必然导致音质退化到 `amr`**
缺失 `fileSize` 或 `url` 可能导致在部分客户端显示异常

可能的改进方案
----
修改 `uploadVoice` 返回 `fileSize` `codec` 参数
构造 `Voice` 时尝试读取这些参数
下游同步修复，接收新的`VoiceDTD`

可能的缓解方案
----
下游框架添加`local_file_passthrough` ***(dangerous)*** 配置，当mah和下游处在同一机器时，使用`voice.path`发送

**Comment by Him188** [comment]
建议使用 fallback codec=1 (core 的行为), 已在 core 测试 amr 和 silk 都可正常发送

**Comment by GreyElaina** [comment]
....我大概会在 python-mirai v5 中提供修复, 比如使用 base64 流.  
v4 各种意义上都很吃力了, 我得快点推出这一代.

**Comment by ryoii** [comment]
@Him188 已修复
