### ISSUE TITLE
mirai-api-http未在mirai-repo-mirror更新版本

### ISSUE THREAD

**Issue by zafkielkurumi** [project-mirai/mirai-api-http#381]
mirai-repo-mirror 未更新2.0之后的版本

**Comment by ryoii** [comment]
上传后可能导致 1.x 的插件直接升级的 2.x 报错

**Comment by Wybxc** [comment]
> 上传后可能导致 1.x 的插件直接升级的 2.x 报错

能不能通过改名发布的方式避免版本冲突？
比如2.0版本放在一个新的名为mirai-api-http-2的包里。

**Comment by ryoii** [comment]
已更新 v2 channel
