### ISSUE TITLE
为什么现在接口文档上只有说明功能，没有说明对应的接口信息？

### ISSUE THREAD

**Issue by Andy-shi001** [project-mirai/mirai-api-http#382]
为什么现在接口文档上只有说明功能，没有说明对应的接口信息？
![image](https://user-images.githubusercontent.com/68884928/123191736-47577000-d4d4-11eb-8f47-21469c45e6fe.png)

**Comment by yuejieyao** [comment]
要不你先看这个?
https://project-mirai.github.io/mirai-api-http/API.html
我看这里还是有的,不过不是2.X的,自行配合迁移文档就行

**Comment by Andy-shi001** [comment]
> 要不你先看这个?
> https://project-mirai.github.io/mirai-api-http/API.html
> 我看这里还是有的,不过不是2.X的,自行配合迁移文档就行

好的 ，谢谢！

**Comment by Excaive** [comment]
接口信息迁移到对应的 Adapter 的文档里面去了
https://github.com/project-mirai/mirai-api-http/blob/master/docs/adapter/HttpAdapter.md

**Comment by ryoii** [comment]
在 adapter 文档里找功能，如果通用功能，下方会有超链接跳转到接口定义。不然每个 adapter 都要写一遍
