### ISSUE TITLE
如果我启用 singleMode, 我该如何得知机器人账号的 id

### ISSUE THREAD

**Issue by GreyElaina** [project-mirai/mirai-api-http#386]
RT, require `GET /sessionInfo`.

**Comment by drsanwujiang** [comment]
用 `GET /botProfile` ？

**Comment by drsanwujiang** [comment]
利用Webhook的上报功能？

https://github.com/project-mirai/mirai-api-http/blob/master/docs/adapter/WebhookAdapter.md

> webhook 不会接收主动请求, 只会接收到事件后向知道地址进行 http 上报. 但远端服务器可以通过 “响应” 进行简单的操作.
> 
> > webhook 上报的内容为消息、事件的对象 消息类型、事件类型
> > 
> > http 请求会携带配置文件中定义的请求头，以及固定的请求头 qq: xxxxxx, 以表示收到消息事件的账号

**Comment by cyanray** [comment]
确实需要一个获取bot qq的接口，session release接口要用到这个qq。
