### ISSUE TITLE
Http Adaptar 文档缺失

### ISSUE THREAD

**Issue by GreyElaina** [project-mirai/mirai-api-http#387]
RT, https://github.com/project-mirai/mirai-api-http/blob/master/docs/adapter/docs/adapter/HttpAdapter.md 无法访问。

**Comment by Drincann** [comment]
Here https://github.com/project-mirai/mirai-api-http/blob/master/docs/adapter/HttpAdapter.md

**Comment by Wybxc** [comment]
或者这里：https://project-mirai.github.io/mirai-api-http/adapter/HttpAdapter.html

**Comment by GreyElaina** [comment]
@Drincann 那建议改一下
