### ISSUE TITLE
多个Bot通过webhook接受消息，如何判断是哪个Bot收到的消息？

### ISSUE THREAD

**Issue by gj1550713314** [project-mirai/mirai-api-http#388]
多个Bot通过webhook接受消息，如何判断是哪个Bot收到的消息？

**Comment by drsanwujiang** [comment]
https://github.com/project-mirai/mirai-api-http/blob/master/docs/adapter/WebhookAdapter.md

> webhook 不会接收主动请求, 只会接收到事件后向知道地址进行 http 上报. 但远端服务器可以通过 “响应” 进行简单的操作.
> 
> > webhook 上报的内容为消息、事件的对象 消息类型、事件类型
> > 
> > http 请求会携带配置文件中定义的请求头，以及固定的请求头 qq: xxxxxx, 以表示收到消息事件的账号
