### ISSUE TITLE
有管理员权限的账户无法对文件重命名

### ISSUE THREAD

**Issue by I-love-study** [project-mirai/mirai-api-http#391]
当我尝试使用renameGroupFile的时候，虽然机器人账户拥有管理员权限
但还是会返回`{'code': 10, 'msg': '无操作权限'}`

`mirai-api-http`版本 : `1.12.0`

**Comment by ryoii** [comment]
之前是 core 的 bug，测试最新的 2.8.0 已经没有了这个问题
