### ISSUE TITLE
Reverse WebSocket 的文档需要更新

### ISSUE THREAD

**Issue by Wybxc** [project-mirai/mirai-api-http#394]
下面这一部分是直接从 WebSocket 文档复制到 Reverse WebSocket 文档的，很具有误导性。

## 创建连接
`ws adatper` 通过 websocket 主动推送消息与事件

`ws adatper` 拥有三个连接通道

`/message`: 推送消息
`/event`: 推送事件
`/all`: 推送消息及事件
```
示例: ws://localhost:8080/message?verifyKey=1234567890&qq=12345678
```

**Comment by ryoii** [comment]
已更新
