### ISSUE TITLE
运行bot时出现 __init__() got an unexpected keyword argument 'authKey'错误

### ISSUE THREAD

**Issue by De3mond** [project-mirai/mirai-api-http#395]
报错内容为：
Traceback (most recent call last):
  File "bot.py", line 14, in <module>
    connect_info=Session(
TypeError: __init__() got an unexpected keyword argument 'authKey'

**Comment by I-love-study** [comment]
1.这里是MiraiApiHttp的issue，假设你要提关于Graia-Application-Mirai的issue请到那边提
2.假设你用的是最新版的Graia-Application-Mirai，因为新版有做Mah2.0的适配，所以确切来讲是verifyKey而不是authKey
3.我强烈建议使用Application0.19.2，因为最新版并没有做完对Mah2.0的适配
