### ISSUE TITLE
/verify 接口返回400

### ISSUE THREAD

**Issue by dandan2095** [project-mirai/mirai-api-http#398]
Need some help. 
verify接口一直返回400， 麻烦帮忙看下哪里填的不对

curl -X POST 127.0.0.1:8080/verify -d '{"verifyKey":"INITKEYJfohNQTI"}'
{"code":400,"msg":"参数格式错误"}

**Comment by cicelix** [comment]
请问最后怎么解决的？

**Comment by Asyfish** [comment]
-H "Content-Type: application/json"

**Comment by zouhy2001** [comment]
注意，最新的release是1.X版本的，文档说明是针对2.x版本的

**Comment by KeyboardMan1996** [comment]
![image](https://user-images.githubusercontent.com/38783216/126030150-26da7dfc-90f3-438c-89f2-5fead8bf479f.png)

目前的release版本是1.x版本，正确的获取方式应该是这样的

**Comment by ryoii** [comment]
看来是版本错误，还有疑问再重新打开issue

**Comment by dandan2095** [comment]
的确是版本问题，http-api升级到2.x就可以了

**Comment by dandan2095** [comment]
> -H "Content-Type: application/json"

跟这个没关系呦，是http-api版本不对

**Comment by Hu-Wentao** [comment]
> 的确是版本问题，http-api升级到2.x就可以了

我使用的是MCL,为什么最新版本只能找到1.10的?

**Comment by sjx233** [comment]
> 我使用的是MCL,为什么最新版本只能找到1.10的?

#381

**Comment by Hu-Wentao** [comment]
> > 我使用的是MCL,为什么最新版本只能找到1.10的?
> 
> #381

只能通过手动下载jar包, 放到plugins路径下解决吗?
