### ISSUE TITLE
webhook 无法引用消息

### ISSUE THREAD

**Issue by nkxingxh** [project-mirai/mirai-api-http#401]
收到上报消息后返回带有quote的数据无反应

![image](https://user-images.githubusercontent.com/25559053/126032466-5acc4a52-78d6-45ff-8d01-88abbe40f8a7.png)

**Comment by nkxingxh** [comment]
mirai-api-http 版本：2.0.2

**Comment by nkxingxh** [comment]
今天又测试了一下，发现以下问题：
1. 机器人启动成功后，通过webhook适配器进行的撤回和quote无反应
2. 使用http适配器进行撤回和发送带有quote的消息，成功后再使用webhook适配器进行撤回和发送带有quote的消息，可正常执行

**Comment by ryoii** [comment]
修复了，等明天发新版
