### ISSUE TITLE
mirai-api-http-v2.1.0.mirai 的http不支持用外网IP访问

### ISSUE THREAD

**Issue by dalaoshus** [project-mirai/mirai-api-http#417]
为什么mirai-api-http-v2.1.0.mirai 的http不支持用外网IP访问了

**Comment by skyilz** [comment]
支持的呀，你可以访问 /about 试试

**Comment by dalaoshus** [comment]
> 支持的呀，你可以访问 /about 试试

不支持我试过了，在配置文件都不改的情况下，把插件换成2.0.2就可以访问，换成2.1.0就不能访问

**Comment by ryoii** [comment]
提供一下配置文件

**Comment by dalaoshus** [comment]
> 提供一下配置文件

## 配置文件中的值，全为默认值

## 启用的 adapter, 内置有 http, ws, reverse-ws, webhook
adapters:
  - http
  - webhook

## 是否开启认证流程, 若为 true 则建立连接时需要验证 verifyKey
## 建议公网连接时开启
enableVerify: true
verifyKey: 1754881660

## 开启一些调式信息
debug: false

## 是否开启单 session 模式, 若为 true，则自动创建 session 绑定 console 中登录的 bot
## 开启后，接口中任何 sessionKey 不需要传递参数
## 若 console 中有多个 bot 登录，则行为未定义
## 确保 console 中只有一个 bot 登陆时启用
singleMode: false

## 历史消息的缓存大小
## 同时，也是 http adapter 的消息队列容量
cacheSize: 4096

## adapter 的单独配置，键名与 adapters 项配置相同
adapterSettings:
  ## 详情看 http adapter 使用说明 配置
  http:
    host: localhost
    port: 9999
    cors: [*]
  
  webhook:
    ## 回调(上报)地址
    destinations: 
    - 'http://1.15.157.111/Mirai/Accept.php'

    extraHeaders:
      Authorization: 'bearer SV*(&*(SH@ID^G'

**Comment by dalaoshus** [comment]
> 提供一下配置文件

就算默认生成的那个，配置文件端口8080也不行

**Comment by ryoii** [comment]
`2.2.0` 没有对http的链接方式做什么改动，比较怀疑 `2.0.2` 可用但 `2.2.0` 不可用的说法

通过配置文件大概判断出是监听的 ip 有问题

localhost 表示的是回环地址，只能通过本机访问。通过非本机的 ip 访问应该将 server 监听的 ip 修改为具体的网卡 ip 或者 `0.0.0.0`

**Comment by dalaoshus** [comment]
> `2.1.0`没有对http链接的方式改变，比较`2.0.2`可能但`2.1.0`不可用的说法
> 
> 通过配置文件大概判断出是监听的ip有问题
> 
> localhost 表示是回环地址，只能通过本机访问。 通过非本机的ip访问应该将服务器监听的ip修改为具体的网卡ip或者 `0.0.0.0`

改成0.0.0.0可以了，不过在我上午更新的时候，测试过，在不更改配置文件的情况下，只更改插件2.0.2可以通过外网IP访问，2.1.0则不行。
我之前的一直在用localhost。

**Comment by ryoii** [comment]
按道理 localhost 是不行的，有兴趣你可以研究一下 localhost 可以的原因

**Comment by SakuraYuki** [comment]
配置文件改为0.0.0.0，使用127.0.0.1或者localhost访问就可以了，外网通过IP+端口访问

**Comment by BlackBird-BB** [comment]
可以做个nginx 端口转发
