### ISSUE TITLE
使用HttpAdapter时enableVerify和singleMode意料外的行为

### ISSUE THREAD

**Issue by ProgramRipper** [project-mirai/mirai-api-http#420]
版本：`2.1.0`
根据默认设置中的注释，enableVerify`为 true 则建立连接时需要验证 verifyKey`，singleMode`为 true，接口中任何 sessionKey 不需要传递参数`
然而，会出现以下两种情况：

- `enableVerify: true` `singleMode: true`时，所有api无需经过verifyKey的验证即可访问。
- `enableVerify: false` `singleMode: false`时，api访问需要sessionKey，但是`/verify`api被禁用，无法获得可用的sessionKey。

我不清楚这两个设置是否就是如此设计，但是我认为[setting.yml 模板](https://github.com/project-mirai/mirai-api-http/tree/master/docs#settingyml-%E6%A8%A1%E6%9D%BF)中的注释没有解释清楚这些行为。

**Comment by ProgramRipper** [comment]
顺便一提`/peekMessage`404了……设置全默认

**Comment by ryoii** [comment]
这是因为你只用了 `http adapter`, 再看看 websocket 的两个你就知道是什么意思了。如果你写过调试过插件，你就知道这个两个到底有什么用

`/peekMessage` 被之前PR的时候写成的是 `/peakMessage`

**Comment by ProgramRipper** [comment]
> 这是因为你只用了 `http adapter`, 再看看 websocket 的两个你就知道是什么意思了。如果你写过调试过插件，你就知道这个两个到底有什么用

我看过websocket的文档，只是不能理解在**仅**使用`HttpAdapter`时的行为（如果我没有看过的话，我就不会添加`使用HttpAdapter时`这个限定词了）。也就是说`HttpAdapter`不能正常的使用这两个设置项？

> `/peekMessage` 被之前PR的时候写成的是 `/peakMessage`

这是bug吗？还是api迁移？如果是前者的话，什么时候会修复？如果是后者的话，`/peekLatestMessage`是否也会迁移？

**Comment by Asyfish** [comment]
一个sessionKey对应一个Bot上下文，插件无法确定（或没有判断）Bot是否是单例，所以当 `singleMode: false`时设置`enableVerify: false`显然是不合理的，免验证且非单例情况下api就不知道该调用哪个上下文了。
其实个人觉得/verify改为/apply可能更合理一点，即/apply**始终**返回一个新的sessionKey，enableVerify只决定在调用/apply时是否需要提交参数verifyKey，确保多Bot时也可以免验证。

**Comment by ProgramRipper** [comment]
> 其实个人觉得/verify改为/apply可能更合理一点，即/apply始终返回一个新的sessionKey，enableVerify只决定在调用/apply时是否需要提交参数verifyKey，确保多Bot时也可以免验证。

同意，`sessionKey`的主要目的应该是区分上下文，即使不需要鉴权（`enableVerify: false`），也应该能够获得区分账号/上下文的`sessionKey`。

其次，如果说

> - enableVerify: true singleMode: true时，所有api无需经过verifyKey的验证即可访问。

这一效果只是为了调试时方便的话，应该在`singleMode`中加入`仅用于开发调试`的警示，否则`enableVerify: true` `singleMode: true`时很容易让人误以为可以安全地开放公网连接（`enableVerify处提示“建议公网连接时开启”，但singleMode: true时根本不能保证安全`）。

**Comment by Asyfish** [comment]
> enableVerify: true singleMode: true时，所有api无需经过verifyKey的验证即可访问。
这个应该是bug吧，测试了下，在`singleMode: true`时，`enableVerify: true`不生效。

**Comment by Asyfish** [comment]
应该是`singleMode`优先级更高，要想开放公网连接，还是 `singleMode: false`老老实实手动验证绑定吧。

**Comment by ryoii** [comment]
认证和绑定逻辑上两个步骤是分离的，任意地去组合导致设计之外的行为也是可预期的

使用中应该按照实际的需要正确的去配置这两步，一般情况下保持配置里默认的 `enableVerify: true, singleMode: false` 即可

**Comment by ryoii** [comment]
如果对未定义的行为有比较好的处理方案，可以再这个issue下继续讨论

**Comment by ryoii** [comment]
新版本的 mah 依旧优化了这个行为

在 `enableVerify: true` `singleMode: true` 时，需要通过 `verify` 接口携带 `verifyKey` 获取并初始化 `SINGLE_SESSION` 才可以使用
在 `enableVerify: false` ·singleMode: false` 时，通过无需 `verifyKey` 的 `verify` 接口获取 `sessionKey` 后续执行正常 `bind` 流程
