### ISSUE TITLE
使用base64发送图片时返回message is empty

### ISSUE THREAD

**Issue by xwh1108** [project-mirai/mirai-api-http#421]
![image](https://user-images.githubusercontent.com/35356435/126606756-cbadc860-7b2f-47c7-8ced-0119e4773a5d.png)
![image](https://user-images.githubusercontent.com/35356435/126606774-ad0341a6-7c6f-47b0-9fdf-74050057804c.png)

![image](https://user-images.githubusercontent.com/35356435/126606701-720fb854-79fd-4558-bb24-1d92cfa8d7d3.png)

**Comment by ryoii** [comment]
测试没有问题,能否复现,能否提供报错日志

**Comment by xwh1108** [comment]
> 测试没有问题,能否复现,能否提供报错日志

request:{"sessionKey":"wbPTk8lf","messageChain":[{"base64”:”图片的base64编码数据”,”time":0,"type":"Image"}],"target":"69****4674"}
response:message is empty

![image](https://user-images.githubusercontent.com/35356435/129868984-f29f0e82-3784-47bd-98ff-39d3a8edd36c.png)

**Comment by xwh1108** [comment]
图片的base64数据正常无误
![image](https://user-images.githubusercontent.com/35356435/129870836-46d16d84-301b-42c9-8b42-86faffd2f0b6.png)
![image](https://user-images.githubusercontent.com/35356435/129870891-81f83360-9841-48b9-990b-c0e3371cdc8e.png)

**Comment by xwh1108** [comment]
> 图片的base64数据正常无误
> ![image](https://user-images.githubusercontent.com/35356435/129870836-46d16d84-301b-42c9-8b42-86faffd2f0b6.png)
> ![image](https://user-images.githubusercontent.com/35356435/129870891-81f83360-9841-48b9-990b-c0e3371cdc8e.png)

去除图片标识data:image/png;base64, 仍然是message is empty

**Comment by xwh1108** [comment]
版本为:mirai-api-http-v1.12.0

**Comment by xwh1108** [comment]
目前看起来是因为1.0版本不支持base64导致的,是我的疏忽
