### ISSUE TITLE
mirai-api-http 是否可以下载群文件

### ISSUE THREAD

**Issue by nkxingxh** [project-mirai/mirai-api-http#424]
在文档里没有找到群文件下载/获取下载地址的方法

**Comment by Asyfish** [comment]
https://docs.mirai.mamoe.net/mirai-api-http/adapter/HttpAdapter.html#%E6%96%87%E4%BB%B6%E6%93%8D%E4%BD%9C

**Comment by nkxingxh** [comment]
> https://docs.mirai.mamoe.net/mirai-api-http/adapter/HttpAdapter.html#%E6%96%87%E4%BB%B6%E6%93%8D%E4%BD%9C

这个文档里面写的只能获取到文件基础信息，但无法获取到下载链接

**Comment by Asyfish** [comment]
> > https://docs.mirai.mamoe.net/mirai-api-http/adapter/HttpAdapter.html#%E6%96%87%E4%BB%B6%E6%93%8D%E4%BD%9C
> 
> 这个文档里面写的只能获取到文件基础信息，但无法获取到下载链接

core不支持返回url #313

**Comment by nkxingxh** [comment]
> > > https://docs.mirai.mamoe.net/mirai-api-http/adapter/HttpAdapter.html#%E6%96%87%E4%BB%B6%E6%93%8D%E4%BD%9C
> > 
> > 这个文档里面写的只能获取到文件基础信息，但无法获取到下载链接
> 
> core不支持返回url #313 

请问那应该如何通过mirai-api-http来获取群文件？😅

**Comment by Asyfish** [comment]
@nkxingxh 不支持
或者你可以去核心项目mirai下提交issue

**Comment by nkxingxh** [comment]
好的，感谢帮助

**Comment by ryoii** [comment]
看了下源码是有的，需要多开放一个明细接口做查询，考虑和 #370  合并
