### ISSUE TITLE
mirai权限判定错误

### ISSUE THREAD

**Issue by dalaoshus** [project-mirai/mirai-api-http#425]
每过一段时间对权限判定就会发生错误，持续很长时间了。

调用禁言api返回状态码10

![IMG_20210727_214026](https://user-images.githubusercontent.com/79201070/127164236-8401abe9-2240-4843-906e-fdef13f93a41.png)

这是截图

**Comment by dalaoshus** [comment]
我补充一下
当我取消机器人管理员权限在重新赋予管理员权限时候就好了

**Comment by ryoii** [comment]
这个是 core 的问题，已经有相关 issue 了，可以去那边关注下

**Comment by dalaoshus** [comment]
> 这个是 core 的问题，已经有相关 issue 了，可以去那边关注下

好的
