### ISSUE TITLE
[功能请求] 支持HTTPS

### ISSUE THREAD

**Issue by Cyl18** [project-mirai/mirai-api-http#427]

**Comment by ryoii** [comment]
是指 http server 启用 https 吗

**Comment by ryoii** [comment]
关键字:

+ JKS动态生成
+ HSTS 支持
+ HTTPS Redirect 支持

**Comment by Cyl18** [comment]
> 是指 http server 启用 https 吗

是的 或者自己走nginx candy之类的也行 只是我看规范里没提过https

**Comment by lyswhut** [comment]
觉得支持HTTPS的意义不大，可以挂个Nginx，客户端走HTTPS到Nginx，Nginx再反向代理到mirai-api-http就行了

**Comment by ryoii** [comment]
ktor 似乎有这个功能，可以考虑支持一下。不知道性能会不会比 nginx 高，但毕竟少一层代理

**Comment by ryoii** [comment]
ktor 官方也建议使用反向代理，生成 JKS 的密钥通用性太差，不考虑支持
