### ISSUE TITLE
创建文件夹 接口无法正常工作

### ISSUE THREAD

**Issue by AHpxChina** [project-mirai/mirai-api-http#428]
### payload:
```json
{
  "id": null,
  "target": "xx group",
  "directoryName": "test"
}
```
> 其中, `id`的值尝试过: `""`, `"/"`, `"."`, `null`, 都无法工作

### response:
```json
{
    "code": 400,
    "msg": "无效参数"
}
```

### request:

> `endpoint`: file/mkdir
> `Authorization`: session xxkey
> `Content-Type`: application/json

### reference:

https://docs.mirai.mamoe.net/mirai-api-http/api/API.html#创建文件夹
https://docs.mirai.mamoe.net/mirai-api-http/adapter/HttpAdapter.html#创建文件夹

**Comment by ryoii** [comment]
请提供一下插件版本号

**Comment by AHpxChina** [comment]
`v2.0.2`....我一直以为是自动更新的来着
