### ISSUE TITLE
发送群消息后，QQ群收不到消息

### ISSUE THREAD

**Issue by willhuo** [project-mirai/mirai-api-http#431]
用的HTTP方式发送QQ群消息，但是群内收不到。昨天晚上第一次成功测试，是能够发送的。今天下午就收不到了。
QQ可以发送好友消息，但不能发群消息。

发送群消息收到的返回结果如下，code=0是发送成功，messageid=-1没有消息，QQ好友消息都有messageid
{
    "code": 0,
    "msg": "success",
    "messageId": -1
}

MCL控制台状态，控制台都正常，没有错误日志
![image](https://user-images.githubusercontent.com/15681218/127974022-f2942825-6258-4005-9c9d-761a1f22a923.png)

**Comment by BlackBird-BB** [comment]
您好，我现在也是这个情况，已经两天了……请问您是怎么解决的？？？

**Comment by willhuo** [comment]
> 您好，我现在也是这个情况，已经两天了……请问您是怎么解决的？？？

实际上没有管，然后自己就好了，应该就是遇到了大家讨论的风控，虽然我不知道这个风控具体怎么回事
