### ISSUE TITLE
mirai-api-http-v2.2.0：无法正常调用 出现socket hang up错误

### ISSUE THREAD

**Issue by 22528850** [project-mirai/mirai-api-http#438]
openjdk:latest
mirai-console-loader:latest
mirai-api-http:latest

docker复现：https://hub.docker.com/r/22528850/mirai-console-loader

**Comment by 22528850** [comment]
mirai-api-http-v2.2.0接口调用不了，
mirai-api-http-v2.0.2是正常的，

**Comment by ryoii** [comment]
怎么调用出现异常,调用什么出现异常,有没有异常日志

**Comment by 22528850** [comment]
> 怎么调用出现异常,调用什么出现异常,有没有异常日志

就直接postman调试接口，应该都异常了吧，我只试了http的verify的接口，没有异常日志，
新开一个容器可以复现此情况的

**Comment by STDSuperman** [comment]
这个解决了吗，我也遇到了，部署到 docker 就报这个错

**Comment by STDSuperman** [comment]
![image](https://user-images.githubusercontent.com/44311619/166138158-88517639-0b20-491d-8cf2-8d16488dcc9b.png)
