### ISSUE TITLE
怎么获取加群人信息

### ISSUE THREAD

**Issue by OctoberShiyue** [project-mirai/mirai-api-http#441]
想获取加群人的等级，能获取得到吗？

**Comment by OctoberShiyue** [comment]
打算还没批准中如果等级低就不给通过

**Comment by Wybxc** [comment]
这项功能 mirai 应该是没有
可以试试第三方 API：http://cdn.maoley.cn/qq/dj.php

**Comment by OctoberShiyue** [comment]
> 这项功能 mirai 应该是没有
> 可以试试第三方 API：http://cdn.maoley.cn/qq/dj.php

能用的次数太少，用半天就用完了= =

**Comment by ryoii** [comment]
似乎有 webapi 的接口可以实现，但是需要 skey 等信息，可以提 issue 到 core 仓库

**Comment by developer-ken** [comment]
该功能似乎已经被mirai实现(Mirai.queryProfile)，目前http接口中有等效的操作吗
https://github.com/mamoe/mirai/commit/c77f94cd521062175bb6269f7b1e25edfad30438

**Comment by OctoberShiyue** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
