### ISSUE TITLE
GroupRecallEvent 中时间不正确

### ISSUE THREAD

**Issue by Wybxc** [project-mirai/mirai-api-http#442]
https://github.com/project-mirai/mirai-api-http/blob/4b239e50325daa3554877d0c634b4ad6cb79d003/mirai-api-http/src/main/kotlin/net/mamoe/mirai/api/http/adapter/internal/convertor/event.kt#L32

这里为什么要只取2个字节？

**Comment by ryoii** [comment]
Fixed
