### ISSUE TITLE
如何获得其他客户端发送的消息？

### ISSUE THREAD

**Issue by tsurumi-yizhou** [project-mirai/mirai-api-http#444]
如题，在手机上发送的消息，本地不能收到。

**Comment by ryoii** [comment]
可以，消息类型是 `OtherClientMessage`

**Comment by ryoii** [comment]
这个是指通过”我的手机“， ”我的电脑”发送的消息

如果你是指不同客户端向群里发消息，那大概是获取不到的，消息被 core 过滤掉了
