### ISSUE TITLE
现在是推荐新人上1.x还是2.x呢？

### ISSUE THREAD

**Issue by kpi311** [project-mirai/mirai-api-http#445]
如题，刚开始学习不是很清楚，默认脚本安装的是1.10，我去gitee看了[源](https://gitee.com/peratx/mirai-repo/blob/master/net/mamoe/mirai-api-http/package.json)，里面只有1.x版本的信息。但是这边文档好像都已经是2.x版本的内容了，有点迷惑，所以想请指点一二😊

**Comment by Samarium150** [comment]
MCL的更新脚本其实可以disable掉。v2.2.0和v1.12.0其实都适配了mirai-core v2.7。但毕竟开发进度已经在2.x了，我觉得还是2.x更好一点

**Comment by kpi311** [comment]
明白了，非常感谢！😊😊
