### ISSUE TITLE
部分群文件获取接口异常导致所占内存不断扩大

### ISSUE THREAD

**Issue by vikieow** [project-mirai/mirai-api-http#449]
部分群的群文件请求接口会返回500 doesn't existed 错误
也会有请求全部群文件时长过长的问题
导致整个软件所占内存越来越大

**Comment by SinoAHpx** [comment]
复议

**Comment by ryoii** [comment]
扩大的内存是否会被回收？目前支持分页，如果文件过多可以尝试一下

**Comment by ryoii** [comment]
2.11 更新了整个群文件接口，类似情况不一定会再现，如有问题，另开issue

**Comment by vikieow** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
