### ISSUE TITLE
v2.2.0 console显示接收到消息，但是fetchMessage结果为空

### ISSUE THREAD

**Issue by keke1229488344** [project-mirai/mirai-api-http#451]
调用API接口fetchMessage返回的结果一直都是
{'code': 0, 'msg': '', 'data': []}
peekLatestMessage也无法获取到消息。

"net.mamoe:mirai-console" version 2.7-RC
"net.mamoe:mirai-console-terminal" version 2.7-RC
"net.mamoe:mirai-core-all" version 2.7-RC
“net.mamoe.mirai-api-http” v2.2.0

PHP：
$sessionkey = botlogin();
sleep(5);
$info=curl_file_get_contents($url.'/fetchLatestMessage?sessionKey='.$sessionkey.'&count='.'10');
echo $info;
botlogout($sessionkey);

返回结果：{'code': 0, 'msg': '', 'data': []}

**Comment by ryoii** [comment]
能否复现

**Comment by ryoii** [comment]
长时间没有回复，暂时关闭 issue
