### ISSUE TITLE
对于file/upload接口的迷惑

### ISSUE THREAD

**Issue by SinoAHpx** [project-mirai/mirai-api-http#456]
参考的文档：https://docs.mirai.mamoe.net/mirai-api-http/adapter/HttpAdapter.html#%E7%BE%A4%E6%96%87%E4%BB%B6%E4%B8%8A%E4%BC%A0

不知道，如何指示把文件上传到哪个群，文档也没有写明。

如果按照文档提供的参数(C#代码)：

```cs
var result = await url
    .WithHeader("Authorization", $"session {MiraiBot.Instance.HttpSessionKey}")
    .PostMultipartAsync(x => x
        .AddString("type", "group")
        .AddString("path", uploadPath)
        // .AddString("target", target)
        .AddFile("file", filePath));
```

则会报错：
```json
{"code":400,"msg":"无效参数"}
```

如果自行加上`target`则会报错：
```json
{"code":500,"msg":"Failed to upload file."}
```

那么我该如何使用这个接口呢？

**Comment by SinoAHpx** [comment]
uploadPath = ""

**Comment by SinoAHpx** [comment]
看来是`path`的问题。
但是这个`path`在文档里的描述是：`上传目录的id, 空串为上传到根目录`，很难不让人误解。

**此处的`path`应该包括文件夹路径和文件名**，比如：
+ `/test.xx`，就是在根目录上传一个叫`test.xx`的文件
+ `/test/test.xx`，就是在`test`目录下上传一个叫`text.xx`的文件

**Comment by SinoAHpx** [comment]
另外，在发送请求的时候应该使用`target`来指定该上传到哪个群

**Comment by ryoii** [comment]
加上target是对的。出现500错误大概是目前出现同步方面的问题。文件上传后按照目前的操作，会取一次新的文件信息返回，但是当上传成功后立马获取文件其实是失败的，所以出现了现在这个报错。

如果不出意外的话，加上target返回报错后，其实文件已经上传成功了

**Comment by ryoii** [comment]
path的描述在上一次的PR中应该是被修改过了，应该是没有覆盖完全，path止的应该上传后文件的路径而不是父级目录

**Comment by ryoii** [comment]
接下来大概率的修复方案是不指定上传上传文件的名称，而从multipart中读取，来保证接口定义的不变，姑且现在认为是出bug了吧
