### ISSUE TITLE
有没有方法获取所有已经登陆的账号

### ISSUE THREAD

**Issue by super1207** [project-mirai/mirai-api-http#459]
目前，我需要知道qq号才能对接，如果我想要一次性对接所有已经登陆的账号，这有些不方便。

**Comment by ryoii** [comment]
console应该有指令, 你 `help` 看看, 通过command相关接口看看能不能达到预期效果

**Comment by super1207** [comment]
看了下，应该没有，command只有一个获取自动登录账号的接口。并且，也不知道是否登录成功。

**Comment by CYY666666** [comment]
登录成功之后给服务器或者某一个QQ号发条消息

**Comment by ryoii** [comment]
# #459
