### ISSUE TITLE
拆分文档

### ISSUE THREAD

**Issue by copydog** [project-mirai/mirai-api-http#46]
一个文档太难长了，难得写也难得查看

**Comment by martinwang2002** [comment]
建议写个swagger 的json 文档
并且在README.md中连接到EventType.md 和 MessageType.md, 不然找不到

**Comment by BeautyYuYanli** [comment]
可以搬進wiki裏面

**Comment by KawaiiZapic** [comment]
#168 尝试对文档创建一个完整的索引,并轻微调整了一下文档的顺序与结构.  
如果有什么建议可以指出一下,可以在合并之前继续努力一下.
