### ISSUE TITLE
发送群消息带网络图片时，提示发送成功，但是群内并未受到图片

### ISSUE THREAD

**Issue by NextSeconds** [project-mirai/mirai-api-http#467]
**//发送的消息**
{"syncId":123,"command":"sendGroupMessage","content":{"sessionKey":"L7s5pzmi","group":1002593646,"messageChain":[{"type":"Image","url":"https://i0.hdslb.com/bfs/album/67fc4e6b417d9c68ef98ba71d5e79505bbad97a1.png"}]}}
**//成功反馈**
{"syncId":"123","data":{"code":0,"msg":"success","messageId":-1}}

上面的url地址用的httpapi的示例图，加载应该都没问题。
但是群内没有接到回复，这个就不截图了

按理说这个功能大家应该挺常用的，前两天自己也试过还可以正常使用，今天突然就不行了（已经试了十多次了）
下面是mirai日志的截图
![1631260540(1)](https://user-images.githubusercontent.com/35531612/132820247-74080d3d-8b93-45b2-ae53-dd355f59e46c.png)

想问问大佬这是啥情况，不稳定么，还是？

**Comment by kirafishy** [comment]
这个是mirai本身的问题 详见https://github.com/mamoe/mirai/issues/1536 最新的测试版据说已经解决了 你可以看一下

**Comment by NextSeconds** [comment]
emmmm，我刚才上面截图是重运行服务截的，貌似已经是最新版了，把日志图截完整一下。。。。(⊙﹏⊙)b

![image](https://user-images.githubusercontent.com/35531612/132826314-72cf8d1c-37e6-496e-886c-be4b3c3a3f5e.png)

**Comment by NextSeconds** [comment]
> 这个是mirai本身的问题 详见[mamoe/mirai#1536](https://github.com/mamoe/mirai/issues/1536) 最新的测试版据说已经解决了 你可以看一下

我截图的时候就已经是最新版了(⊙﹏⊙)b

**Comment by ryoii** [comment]
更新最新版后还是这个问题，有可能是消息风控，稍等几十分钟即可

**Comment by NextSeconds** [comment]
> 更新最新版后还是这个问题，有可能是消息风控，稍等几十分钟即可

三天了，还是不行。。。。(⊙﹏⊙)b

**Comment by ryoii** [comment]
确定为 core 或 风控的问题
