### ISSUE TITLE
加入群的事情会触发两次

### ISSUE THREAD

**Issue by Moyulingjiu** [project-mirai/mirai-api-http#476]
复现：
添加群邀请事件，并且添加自动通过群邀请（不确定是否为必要前提），然后添加加群事件。
![image](https://user-images.githubusercontent.com/40913925/133986327-7365d551-4503-4228-8b1d-11b416b4f85b.png)
就可以看见该事件触发了两次
第一次邀请人固定为None，第二次为正常打印。使用的YiriMirai框架，找框架主，框架主说是mah的问题。

**Comment by ryoii** [comment]
看看 console 的日志是不是本身就触发了两次事件，重复触发大概率都是 core 的问题，接口监听事件基本不可能产生两次消费。
以我之前维护 core 的经历，大概率也是服务器本来就返回了两个事件的数据包，这个都是要在 core 的内部过滤掉的

**Comment by Moyulingjiu** [comment]
![image](https://user-images.githubusercontent.com/40913925/134124005-11d30bd2-dbe9-43a2-a92b-52d753ca6e2f.png)
日志

**Comment by Moyulingjiu** [comment]
[2021-09-20.log](https://github.com/project-mirai/mirai-api-http/files/7200854/2021-09-20.log)
这是原始文件

**Comment by ryoii** [comment]
日志不完整，且我本地没有复现，后续还有问题建议提交到 core 仓库
