### ISSUE TITLE
关于好友消息撤回接口的operator

### ISSUE THREAD

**Issue by Mizushio** [project-mirai/mirai-api-http#477]
其他接口上operator使用了object类型，而唯独这个事件返回是long，是不是变成operator.id 会好点？
（本消息来自一个写了一大堆bean的笨蛋）

**Comment by ryoii** [comment]
好问题，GroupRecallEvent 返回的是 member object, FriendRecallEvent  返回的是 Friend id。Core 就是这么提供字段的。为了两个长得像的实体字段差不多，所以我同一成 `operator` ，虽然我也可以通过 id 查一遍 friend object 出来，但还是和 core 保持一致比较好
