### ISSUE TITLE
/file/upload 报错 file size

### ISSUE THREAD

**Issue by Godmyhave** [project-mirai/mirai-api-http#480]
下午还能正常使用的，晚上不行了，可能会是以错误格式上传次数多了的原因。
代码：
![image](https://user-images.githubusercontent.com/59076131/134814659-6836f89a-acd4-4849-a001-9dee414236cc.png)
![image](https://user-images.githubusercontent.com/59076131/134814605-258b796f-5620-4a3b-85c9-9e4d4a44a53e.png)
返回：
{'code': 500, 'msg': 'Failed RemoteFile.upload, result=-303, msg=param error: file size'}
控制台爆红
![image](https://user-images.githubusercontent.com/59076131/134814671-e40d9ccb-b3bb-4c33-84b2-36f9dc287cff.png)
另外会损坏本机文件
生前：
![image](https://user-images.githubusercontent.com/59076131/134814788-cbcc10e6-5d4e-4df3-a87b-c018bb8d0a53.png)
生后：
![image](https://user-images.githubusercontent.com/59076131/134814749-84608a01-246a-4e0f-bee6-0149fa53223b.png)

**Comment by nepsyn** [comment]
![](https://s3.bmp.ovh/imgs/2021/09/1bf3ee27d4052c2f.jpg)

**Comment by Godmyhave** [comment]
谢谢，是我太菜了，乱改东西
