### ISSUE TITLE
..新版本外网无法访问，且无法指定IP地址

### ISSUE THREAD

**Issue by aion1998** [project-mirai/mirai-api-http#481]

**Comment by aion1998** [comment]
![image](https://user-images.githubusercontent.com/19725014/134861386-9e96d6da-31ef-410b-a152-c7c36aaac4fe.png)
如图 配置，则启动直接报错

**Comment by aion1998** [comment]
如配置为localhost，则服务器本机可以访问，外网无法访问

**Comment by aion1998** [comment]
排除因素：防火墙等之类的服务器原因，因为旧版本也是用这一样的地址，单纯只是升级了mirai-api-http 插件版本而已

**Comment by aion1998** [comment]
## localhost正常启动情况
![image](https://user-images.githubusercontent.com/19725014/134861875-302ab232-bf84-44a0-9da9-a06ef7621b34.png)

## 内网访问
![image](https://user-images.githubusercontent.com/19725014/134861916-429f64dd-f014-4bbd-84fe-12247316cedf.png)

## 外网访问
![image](https://user-images.githubusercontent.com/19725014/134861978-64226715-852c-44fa-8e0b-bd8e7c628dd0.png)

**Comment by nepsyn** [comment]
0.0.0.0试试

**Comment by aion1998** [comment]
哎，可以了，爱你，mua~👬
