### ISSUE TITLE
发送转发消息(Forward)会变成空转发消息(nodeList=[])

### ISSUE THREAD

**Issue by cyanray** [project-mirai/mirai-api-http#482]
使用 http api 发送群聊消息：
(敏感信息用***代替)
```json
{
    "messageChain": [
        {
            "nodeList": [
                {
                    "messageChain": [
                        {
                            "text": "可恶啊",
                            "type": "Plain"
                        }
                    ],
                    "messageId": 0,
                    "senderId":***,
                    "senderName": "***",
                    "time": 1632745670
                }
            ],
            "type": "Forward"
        }
    ],
    "sessionKey": "WxuJCza2",
    "target":***
}
```
mirai 日志：
```
Group(***) <- ForwardMessage(preview=[], title=群聊的聊天记录, brief=[聊天记录], source=聊天记录, summary=查看0条转发消息, nodeList=[])
```
**mirai-core: v2.8.0-M1
mirai-api-http: v2.3.1**

经测试 mah v2.2.0 版本和 v2.3.1 版本都不能发送。

**Comment by nepsyn** [comment]
尝试将 messageId 置为 null

https://github.com/project-mirai/mirai-api-http/blob/159d74afe1f6108fa43107a41b1ec44476afc740/mirai-api-http/src/main/kotlin/net/mamoe/mirai/api/http/adapter/internal/convertor/convertor.kt#L86-L95

messageId 不为 null 的情况下似乎会从缓存中取原始消息

**Comment by cyanray** [comment]
> 尝试将 messageId 置为 null
> 
> https://github.com/project-mirai/mirai-api-http/blob/159d74afe1f6108fa43107a41b1ec44476afc740/mirai-api-http/src/main/kotlin/net/mamoe/mirai/api/http/adapter/internal/convertor/convertor.kt#L86-L95
> 
> messageId 不为 null 的情况下似乎会从缓存中取原始消息

问题解决！
