### ISSUE TITLE
2.3.2版本：群成员列表依然存在缓存数据

### ISSUE THREAD

**Issue by 158430154** [project-mirai/mirai-api-http#487]
1.新进入的成员接口返回是实时的
2.老成员离开群或者被管理员踢出群，是没有删除群成员的。导致退出了的成员依然在群成员列表的接口返回数据里面

需求：
麻烦有空的时候，考虑把退出群组的成员同步更新，或者不做缓存数据也行。

**Comment by ryoii** [comment]
群成员和好友列表在MAH是不维护的，你可以保留日志将issue开到core里

**Comment by ryoii** [comment]
后续问题为 core 维护 list 的问题
