### ISSUE TITLE
Failed posting `/file/upload` while receiving 200 OK

### ISSUE THREAD

**Issue by ryuujo1573** [project-mirai/mirai-api-http#493]
```python
resp_upload = requests.post(f"{base_url}/file/upload", headers={
    # 'Content-Type': 'multipart/form-data',
}, files={
    'sessionKey': session,   ###
    'type': 'group',
    'target': ________,
    'path': '/0_0.png',
    'file': ('0_0.png', open('0_0.png', 'rb')),
})
```

In this case, it showed: `'{"code":3,"msg":"Session失效或不存在"}'`. // Session deprecated or it does not exist
Nonetheless, I succeeded in send messages **(less than 2 chars only)** with the same procedure as this case.

```python
resp_upload = requests.post(f"{base_url}/file/upload", headers={
    # 'Content-Type': 'multipart/form-data',
    'sessionKey': session,   ###
}, files={
    'type': 'group',
    'target': 937066966,
    'path': '/0_0.png',
    'file': ('0_0.png', open('0_0.png', 'rb')),
})
```

and in this case, it showed: `'{"code":400,"msg":"无效参数"}'` // invalid argument

and and 
```python
resp_upload = requests.post(f"{base_url}/file/upload", headers={
    'Content-Type': 'multipart/form-data',  ###
    'sessionKey': session,
}, files={
    'type': 'group',
    'target': 937066966,
    'path': '/0_0.png',
    'file': ('0_0.png', open('0_0.png', 'rb')),
})
```
which told me `'{"code":500,"msg":"Failed to parse multipart: Content-Type\'s boundary parameter is missing"}'`

and and and 
```python
resp_upload = requests.post(f"{base_url}/file/upload", headers={
    'Content-Type': 'multipart/form-data',
    'boundary': '&',  ###
    'sessionKey': session,
}, files={
    'type': 'group',
    'target': 937066966,
    'path': '/0_0.png',
    'file': ('0_0.png', open('0_0.png', 'rb')),
})
```
well nothing changed.

I was bloody confused, any advice would be appreciated. tks.

**Comment by ryoii** [comment]
Which version of the plugin are you using? I can't reproduce your case with api tester.

I reviewed your code and this the third case you posted is right but it seems to fail because of a wrong multipart format. I am not familiar with python, I am not sure the correct way to send multipart request. Maybe, you could have a try to test the api with some tools with the version you are using

**Comment by ryoii** [comment]
I found some solutions that may help you. 
The most likely solution is to remove the `Content-Type` header. Your http client may not generate the ramdon boundary while setting the content type yourself.

By the way, the parameter of `path` means the directory your upload. The filename will be read from the file automatically.

**Comment by ryuujo1573** [comment]
Thanks for your hints
Soon I figured out that I should watch the actual outposting data, and I found that its my fault to put all stuffs in `files` parameter, and I got a resp of better look which is like: 
```json
{
    "code": 0,
    "msg": "",
    "data": {
        "name": "0_0.png",
        "id": "/3b0d8bc9-913c-48e8-b650-0a8931a0f035",
        "path": "/0_0.png",
        "parent": {
            "name": "",
            "id": null,
            "path": "/",
            "parent": null,
            "contact": {
                "id": 10000000,
                "name": "_____name____",
                "permission": "MEMBER"
            },
            "isFile": false,
            "isDictionary": true,
            "isDirectory": true,
            "size": 0,
            "downloadInfo": null
        },
        "contact": {
            "id": 10000000,
            "name": "_____name____",
            "permission": "MEMBER"
        },
        "isFile": true,
        "isDictionary": false,
        "isDirectory": false,
        "size": 7109,
        "downloadInfo": null
    }
}
```
and with code (the proper version I think hmmm)
```python
resp_upload = requests.post(f"{base_url}/file/upload", headers={
    # 'Content-Type': 'multipart/form-data',
    # 'boundary': '--------------------------756537252445992812314949',
    'sessionKey': session,
}, files={
    'file': open('0_0.png', 'rb'),
}, data={
    'type': 'group',
    'target': 937066966,
    'path': '',
})
```


and it worked! xdddd
thank a lot for you earliest reply

**Comment by ltiaw** [comment]
用这种上传文件可以上传，但是返回的结果是
{"code":500,"msg":"Sending FileMessage is not in support"}
上传语音用这种不行

**Comment by ryoii** [comment]
files和data分开
