### ISSUE TITLE
现在是否支持发送File类型消息？

### ISSUE THREAD

**Issue by Fripine** [project-mirai/mirai-api-http#494]

**Comment by Fripine** [comment]
接收到群聊的File类型消息后，将消息发送出去提示message is empty

**Comment by ryoii** [comment]
暂时不支持，但是可以支持，虽然我不知道 core 支不支持

**Comment by ryoii** [comment]
从收到的消息里转发应该可以实现，从已有群列表里转发或许还要再等等 mamoe/mirai#1638

**Comment by Fripine** [comment]
> 从收到的消息里转发应该可以实现，从已有群列表里转发或许还要再等等 [mamoe/mirai#1638](https://github.com/mamoe/mirai/issues/1638)

意思是目前还不行是吗？
我就做了个简单的复读机，无法复读File类型消息，mirai控制台报错

2021-11-01 15:09:57 E/MAH Access: java.lang.IllegalArgumentException: message is empty

**Comment by ryoii** [comment]
> > 从收到的消息里转发应该可以实现，从已有群列表里转发或许还要再等等 [mamoe/mirai#1638](https://github.com/mamoe/mirai/issues/1638)
> 
> 意思是目前还不行是吗？
> 我就做了个简单的复读机，无法复读File类型消息，mirai控制台报错
> 
> 2021-11-01 15:09:57 E/MAH Access: java.lang.IllegalArgumentException: message is empty

是的，不识别的消息类型被过滤了就空消息报错了

**Comment by Karlatemp** [comment]
Rejected: https://github.com/mamoe/mirai/issues/1646
