### ISSUE TITLE
关于MAH依赖的疑问

### ISSUE THREAD

**Issue by dellbeat** [project-mirai/mirai-api-http#497]
比如`v2.3.0`支持的是core的`2.7.0`版本

能否直接将core版本进行提升还是需要等待MAH支持特定版本如`2.8.0-RC`方可提升

**Comment by ryoii** [comment]
没有不兼容修改可以直接用，具体有没有二进制上的不兼容，只能试了才知道

**Comment by dellbeat** [comment]
好的了解了 谢谢
