### ISSUE TITLE
memberList方法获取群成员列表没有自己的信息

### ISSUE THREAD

**Issue by missile-xuan** [project-mirai/mirai-api-http#498]
memberList方法获取群成员列表没有自己账号的信息

**Comment by missile-xuan** [comment]
![9APE@7 UNL 6Y 9V3U @OSD](https://user-images.githubusercontent.com/38873815/140698213-87809708-e528-4e30-9282-46e5a15496f3.png)
找了下mirai 好像确实这个方法不会返回自己

botAsMember有办法获取嘛？

想拿到bot在群里的最后发言时间

**Comment by ryoii** [comment]
可以通过 `memberInfo` 的接口单独获取 bot 的群成员信息
