### ISSUE TITLE
POST /command/send 接口 404

### ISSUE THREAD

**Issue by Drincann** [project-mirai/mirai-api-http#499]
mirai-api-http v2.3.3

![image](https://user-images.githubusercontent.com/53897259/140934284-0419d646-f2c2-443e-9d73-fb0eb54edb7b.png)

![image](https://user-images.githubusercontent.com/53897259/140934311-c24fdd43-c53a-4077-b26e-b2c86a6249ca.png)

**Comment by ryoii** [comment]
[POST] `/cmd/execute`

**Comment by Drincann** [comment]
> [POST] `/cmd/execute`

文档是否存在缺失，在这里我没找到相关 api https://github.com/project-mirai/mirai-api-http/blob/master/docs/api/API.md#%E5%91%BD%E4%BB%A4console-command

**Comment by ryoii** [comment]
应该是缺了，你发的那个接口可能是 1.x 废除 command 前的接口

**Comment by Drincann** [comment]
![image](https://user-images.githubusercontent.com/53897259/141240634-68f68db5-d7b2-4238-8b1b-51d5b6041611.png)

请求参数是什么？

```ts
verifyKey: stinrg;
command: string[];
```

这个不对

**Comment by ryoii** [comment]
message[]

就是你发消息的那个消息对象，普通命令构造 `Plain Text` 就可以了。因为 console 在命令上支持其他消息类型作为参数

**Comment by Drincann** [comment]
```ts
interface {
  sessionKey: string;
  command: message[];
}
```
