### ISSUE TITLE
引用消息里如果有图片会无法显示

### ISSUE THREAD

**Issue by ssccinng** [project-mirai/mirai-api-http#502]
经过测试后推测是api-http的bug

**Comment by ssccinng** [comment]
此bug仅存在于pc端

**Comment by ryoii** [comment]
不会又只存在于PC端的问题，可否提供一个最小的复现 demo，猜测是协议的问题

**Comment by ryoii** [comment]
长时间没有反馈，暂时关闭issue

**Comment by ssccinng** [comment]
之前太忙  忘记了.. 不好意思

**Comment by ssccinng** [comment]
我是用mirai.net的包的，和作者讨论了下感觉可能不是他的问题。猜测可能是这里的问题。下图为实例。待会我测一下最新版 看看还有没有问题，有的话我提供一个简单的代码实现
![Uploading NP}([LA88W[1A8}ZZH4IT[L.png…]()
![P)CYMZC6}KEW$}URSL3O78J](https://user-images.githubusercontent.com/22047352/152752173-74e53818-0b80-4e7b-9477-bcd12e9c649d.png)

**Comment by ssccinng** [comment]
> 我是用mirai.net的包的，和作者讨论了下感觉可能不是他的问题。猜测可能是这里的问题。下图为实例。待会我测一下最新版 看看还有没有问题，有的话我提供一个简单的代码实现 ![Uploading NP}([LA88W[1A8}ZZH4ITL.png… ![P)CYMZC6}KEW$}URSL3O78J](https://user-images.githubusercontent.com/22047352/152752173-74e53818-0b80-4e7b-9477-bcd12e9c649d.png)

![NP}( LA88W 1A8}ZZH4IT L](https://user-images.githubusercontent.com/22047352/152752576-b5931142-7563-40eb-a01f-958da7fb6b1d.png)

**Comment by ssccinng** [comment]
[mahtest.zip](https://github.com/project-mirai/mirai-api-http/files/8020348/mahtest.zip)
