### ISSUE TITLE
Docker 镜像

### ISSUE THREAD

**Issue by ZhaoZuohong** [project-mirai/mirai-api-http#504]
我写了个包含 Mirai 和 mirai-api-http 的 Dockerfile，源码与使用说明在 [https://github.com/ZhaoZuohong/mirai-mah-docker](https://github.com/ZhaoZuohong/mirai-mah-docker) ，发布在 DockerHub 上：[https://hub.docker.com/r/zhaozuohong/mah](https://hub.docker.com/r/zhaozuohong/mah) 。请问有兴趣吗？

**Comment by ryoii** [comment]
挺好，可以PR到mirai主仓库或者console主仓库

**Comment by Slontia** [comment]
链接貌似 404 了，请问还在维护吗

**Comment by ZhaoZuohong** [comment]
> 链接貌似 404 了，请问还在维护吗

您好，我不再用mirai了，所以Docker镜像也不维护了

原来的Dockerfile是这样，里面的版本啥的现在都不是最新的

```dockerfile
FROM ibm-semeru-runtimes:open-17.0.2_8-jre-focal
EXPOSE 8080
WORKDIR /app
RUN apt update && apt install wget unzip
RUN wget -O mcl.zip https://github.com.cnpmjs.org/iTXTech/mirai-console-loader/releases/download/v1.2.2/mcl-1.2.2.zip && unzip mcl.zip && rm -f mcl.zip && chmod +x mcl
RUN mkdir plugins && wget -O plugins/mirai-api-http-v2.4.0.mirai.jar https://github.com.cnpmjs.org/project-mirai/mirai-api-http/releases/download/v2.4.0/mirai-api-http-v2.4.0.mirai.jar
RUN echo exit | ./mcl && rm -fr config
ENTRYPOINT ["/app/mcl"]
```

**Comment by Slontia** [comment]
原来是这样，那我参照这个 dockerfile 改一下试试看，十分感谢
