### ISSUE TITLE
自core v2.8.0起, 无法使用本项目上传群文件

### ISSUE THREAD

**Issue by Executor-Cheng** [project-mirai/mirai-api-http#507]
自core v2.8.0起, 已禁止在用户侧直接发送 `FileMessage` (mamoe/mirai#1646)

**Comment by ryoii** [comment]
暂时用低版本的 core 吧，core 修改了群文件上传的实现，某些接口适配不上了

**Comment by dellbeat** [comment]
> 暂时用低版本的 core 吧，core 修改了群文件上传的实现，某些接口适配不上了

比较奇怪的是用2.3.0MAH就可以 2.3.3就不行了

**Comment by ryoii** [comment]
2.3.0有bug，只上传没有发送。现在 core 限制了发送功能
