### ISSUE TITLE
处理添加好友事件请求时的拒绝消息丢失

### ISSUE THREAD

**Issue by dellbeat** [project-mirai/mirai-api-http#508]
接口地址为`http://127.0.0.1:2333/resp/newFriendRequestEvent`

抓包的请求报文如下
`{"sessionKey":"tMm9cYA1","eventId":EventId,"fromId":QQ,"groupId":0,"operate":1,"message":"\u665A\u70B9\u518D\u52A0\u6211"}`

返回的报文请求如下
`{"code":0,"msg":"success"}`

但是实际上在被拒绝提示中没有获取到消息

2.3.0和2.3.3均有这个问题 且在pad和phone上均可复现

**Comment by ryoii** [comment]
看了下 core 的接口，已经没有这个参数了

**Comment by dellbeat** [comment]
那我去查查core的改动再决定怎么弄吧 感谢
