### ISSUE TITLE
iPad协议无法发送戳一戳

### ISSUE THREAD

**Issue by djkcyl** [project-mirai/mirai-api-http#509]
![QUGOI0I2}52PSU2C9YKP9TV](https://user-images.githubusercontent.com/59153990/144001541-7b9057f3-7daa-44f3-aeb3-f6d9e767175e.png)
可以接受到事件但无法发送

**Comment by ryoii** [comment]
ipad本来就不能戳

**Comment by djkcyl** [comment]
> ipad本来就不能戳

草，没事了（留下贫穷的眼泪
