### ISSUE TITLE
ws推送俩次一样的信息

### ISSUE THREAD

**Issue by DongShaoNB** [project-mirai/mirai-api-http#512]
![QQ图片20211204114133.png](https://s2.loli.net/2021/12/04/1cL7jWEHqOdeMzJ.png)
![QQ图片20211204114141.png](https://s2.loli.net/2021/12/04/A7EKkNYsZbPoItU.png)
![QQ图片20211204114145.png](https://s2.loli.net/2021/12/04/4IrfWqOVvzuUhoH.png)

连接ws后群信息会推送俩次

**Comment by ryoii** [comment]
重启一下就好了，应该是开了多个session出现的问题

**Comment by DongShaoNB** [comment]
> 重启一下就好了，应该是开了多个session出现的问题

试过了，我认证流程是关闭的，开了单session模式，无论是重启服务器还是Mirai，我在非官方的群聊提问也有人遇到一样的问题，他们给的解决办法是用v2.3.1或者带上session，我用v2.3.1这个问题确实消失了(在我只降级没改动配置文件的情况下

**Comment by ryoii** [comment]
所以你现在用的版本是？

**Comment by DongShaoNB** [comment]
> 所以你现在用的版本是？

重复信息时用的是v2.3.3，换成v2.3.1就没有重复了

**Comment by ryoii** [comment]
2.3.2修复bug的时候就发现这个问题了，2.3.1应该也有这个问题才对。
目前已经修复了，但是还在 `dev` 里

解决方案是关闭单 session，多个websocket连接单独申请 session，在2.3.2的 release 有提到这一点

**Comment by DongShaoNB** [comment]
> 2.3.2修复bug的时候就发现这个问题了，2.3.1应该也有这个问题才对。 目前已经修复了，但是还在 `dev` 里
> 
> 解决方案是关闭单 session，多个websocket连接单独申请 session，在2.3.2的 release 有提到这一点

好的
