### ISSUE TITLE
Connection lost, reconnecting...

### ISSUE THREAD

**Issue by fastslow** [project-mirai/mirai-api-http#518]
![image](https://user-images.githubusercontent.com/45308679/145371220-a9f2817d-0d70-4d53-8669-2fdb2c73b6b7.png)
这个应该怎么解决呀

**Comment by ryoii** [comment]
没有影响使用都没有问题，bot掉线了而已，已经自动重连了

**Comment by fastslow** [comment]
> 没有影响使用都没有问题，bot掉线了而已，已经自动重连了

自动重连后机器人能够接收到消息，但是自己写的python代码需要重新运行才能够，实现自动回复。

**Comment by apple-pen** [comment]
> ![image](https://user-images.githubusercontent.com/45308679/145371220-a9f2817d-0d70-4d53-8669-2fdb2c73b6b7.png) 这个应该怎么解决呀

你是不是手机端mirai 安卓没有关 两边挤下线

**Comment by fastslow** [comment]
> > ![image](https://user-images.githubusercontent.com/45308679/145371220-a9f2817d-0d70-4d53-8669-2fdb2c73b6b7.png) 这个应该怎么解决呀
> 
> 你是不是手机端mirai 安卓没有关 两边挤下线

手机端没有登陆，我发现使用 http adapter 重新连接不影响使用。 ws 重新连接，我就要重新登陆和重新运行 python 代码。
