### ISSUE TITLE
關於讀取本身帳號發送的訊息

### ISSUE THREAD

**Issue by KohakuBlueleaf** [project-mirai/mirai-api-http#528]
想請問一下
mirai console中顯示SYNC的這些自己發的訊息
![image](https://user-images.githubusercontent.com/59680068/148092920-c4f333c7-6236-429c-a77a-70a2cbd2a5ef.png)
有沒有可能在api中讀取?
還是不好實作或著不建議這麼做

**Comment by ryoii** [comment]
返回有messageid，可以通过messageid查出来

**Comment by KohakuBlueleaf** [comment]
@ryoii  我指的是同個帳號 使用其他裝置發送的訊息

**Comment by ryoii** [comment]
看了眼文档，有同步消息事件，下个版本加上
