### ISSUE TITLE
红包和纯文本无法区分

### ISSUE THREAD

**Issue by 515621078** [project-mirai/mirai-api-http#540]
在接收红包消息时，显示为 
“[QQ红包]请使用新版手机QQ查收红包。”
如果在对话中打出这段文本，则无法区分是红包还是文本。

在mirai中两者的区别是
"[QQ红包]请使用新版手机QQ查收红包。[不支持的消息#-401062133]"
和
"[QQ红包]请使用新版手机QQ查收红包。"

但从mah中得到的json则无法判断...

这个可以不可以区分出来呀
谢谢 ♪(･ω･)ﾉ

**Comment by ryoii** [comment]
不太可以，mah把不能识别的消息类型都过滤了。mirai中显示“不支持的消息”也只是把不识别的消息类型打印了出来，如果mah也这样做，不出现大量无用的消息类型夹杂在接口数据里

**Comment by 515621078** [comment]
@ryoii 感谢解答

这些数据有些不仅是红包，还有其它的一些数据在特定情境下似乎会有用途。
如果实在mah的main里不能实现，能不能通过特定改动创建一个分支呢？
比如一些软件会区分 lite 版本，不知道能不能有一个不过滤的版本呐？
(･ω･)ﾉ

**Comment by ryoii** [comment]
不支持的消息没有任何特征

**Comment by 515621078** [comment]
@ryoii 好可惜，好吧谢谢 _(:зゝ∠)_
