### ISSUE TITLE
如何转发某条消息？

### ISSUE THREAD

**Issue by BohanRen** [project-mirai/mirai-api-http#547]
如题，比如一个好友转发给机器人一个“合并的聊天记录”，现在我想把这条“合并的聊天记录”原封不动的直接转发到另一个群组里面，是否可以通过消息id的方式直接转发？
我现在的实现方法是将好友消息中messageChain的Forward节点记录下来，然后再以消息的形式发出去，但是有一定概率会出现错误，错误如图。是否有更好的实现方式，比如就像手机qq中长按转发一样。谢谢大佬！
![21D0A520-EEF0-4734-A9EB-DDD29DB6E47D](https://user-images.githubusercontent.com/23572936/156006355-71fe98ea-26e9-4495-a492-5fc557e7cabd.png)
![AC0774B2F0C48C0BD9CCD0E43B02A55A](https://user-images.githubusercontent.com/23572936/156006375-eb67faa8-dec2-4b0a-975f-050bc45328ec.jpg)

**Comment by ryoii** [comment]
方法是对的。这个报错应该是复杂的消息类型需要上传服务器的时候，出现了 dns 解析失败。

检查下 bot 运行的网络，配置一个有效的 dns 服务器再做尝试。也不排除是上传的域名有问题，如果尝试过后还有问题，建议将这个 issue 链接到 mriai-core 的仓库，让 core 排查下这个域名是否支持所有地区的网络

**Comment by BohanRen** [comment]
好的，谢谢
