### ISSUE TITLE
获取QQ用户资料userProfile接口404

### ISSUE THREAD

**Issue by oiuv** [project-mirai/mirai-api-http#549]
https://github.com/project-mirai/mirai-api-http/blob/master/docs/api/API.md

这个文档我就看不明白了，API文档只给了请求的参数，没说请求的接口地址和方法啊

**Comment by oiuv** [comment]
哦，在adapter中找到了，不过 userProfile 这个接口不存在呀？

**Comment by ryoii** [comment]
[http](https://github.com/project-mirai/mirai-api-http/blob/v2.5.0/docs/adapter/HttpAdapter.md#%E8%8E%B7%E5%8F%96qq%E7%94%A8%E6%88%B7%E8%B5%84%E6%96%99)
[websocket](https://github.com/project-mirai/mirai-api-http/blob/v2.5.0/docs/adapter/WebsocketAdapter.md#%E8%8E%B7%E5%8F%96qq%E7%94%A8%E6%88%B7%E8%B5%84%E6%96%99)
