### ISSUE TITLE
无法上传群文件到指定的文件夹

### ISSUE THREAD

**Issue by LyqMrq** [project-mirai/mirai-api-http#553]
**版本信息**
core:2.11.0-M1
mah:2.5.0

**问题复现**
这个问题是最近几天才出现的，根据文档示例即可复现，/file/upload接口返回的json为{"code":500,"msg":"Failed to create folder '/文件夹名': -303 文件夹名称错误."}，同时/file/list接口无法获取文件夹的信息。

**Comment by ryoii** [comment]
抱歉近期在忙其他事情。如果有相同问题的用户或者近期还存在该问题的话，可否提供一下复现的请求参数

我猜测是因为指定的上传目录不对或者文件名携带错误了，导致程序试图创建一个根目录
