### ISSUE TITLE
XML消息类型错误

### ISSUE THREAD

**Issue by dalaoshus** [project-mirai/mirai-api-http#554]
突然发现我在群里发xml类型的消息，机器人接受到的消息类型不是xml而是Plain，反之用机器人xml类型消息发送消息会变成连接
![Screenshot_2022-03-18-18-57-50-226_com tencent mobileqq](https://user-images.githubusercontent.com/79201070/158991106-b3740225-28ea-44f6-b331-c5d236b7321d.jpg)

**Comment by dalaoshus** [comment]
控制台
![Uploading IMG_20220318_190353.jpg…]()

**Comment by dalaoshus** [comment]
![IMG_20220318_190353](https://user-images.githubusercontent.com/79201070/158992177-4855a634-2f58-4d07-92fb-36402f7021ba.jpg)
控制台

**Comment by ryoii** [comment]
我无法复现
