### ISSUE TITLE
发送群消息 有时候能发送成功，有时候发送不成功

### ISSUE THREAD

**Issue by echo-LuGuang** [project-mirai/mirai-api-http#559]
版本：
![image](https://user-images.githubusercontent.com/50095011/164874726-db4381d1-7986-4885-b17e-09ab3da51931.png)

http方法请求接口：`/sendGroupMessage`
请求内容：
```
{
    "sessionKey":"vnXzhdaX", //已绑定
    "target":828748275,  //群号
    "messageChain":[
        {
            "type":"Plain",
            "text":"你好"
        }
    ]
}
```

接口响应：
```
{
    "code": 0,
    "msg": "success",
    "messageId": -1   //主要是这里 有时候就返回-1，有时候是正数。 但是大部分情况都是-1
}
```

**Comment by echo-LuGuang** [comment]
![Snipaste_2022-04-23_12-08-52](https://user-images.githubusercontent.com/50095011/164874806-42b9228b-3c57-4a79-af0f-3ee142d9a125.png)

这是控制台的打印。 发送了那么多内容，实际上只发送成功了几个。

**Comment by ryoii** [comment]
控制台打出来了就代表提交到core了，如果发不出来多半是网络问题、风控问题或者协议问题

**Comment by echo-LuGuang** [comment]
> 控制台打出来了就代表提交到core了，如果发不出来多半是网络问题、风控问题或者协议问题

ok，谢谢
