### ISSUE TITLE
如何过滤非指令消息

### ISSUE THREAD

**Issue by maolincc** [project-mirai/mirai-api-http#560]
就是非关键词指令不进行请求

**Comment by maolincc** [comment]
大概就是这边服务了几百个群 
api请求量有点吓人

**Comment by ryoii** [comment]
没懂，这个请求是指什么请求

**Comment by nanamibotybb** [comment]
I believe that you have to customise yourself by editing the source code. However, this should not matter if you have deployed your bot and mah in the same place. Localhost HTTP doesn't bite.

**Comment by maolincc** [comment]
> 没懂，这个请求是指什么请求

比如我有一条指令叫AAA

聊天信息为BBB  不访问http 接口
聊天信息为AAA  访问http接口

**Comment by ryoii** [comment]
> > 没懂，这个请求是指什么请求
> 
> 比如我有一条指令叫AAA
> 
> 聊天信息为BBB 不访问Webhook 接口 聊天信息为AAA 访问Webhook接口
> 
> 就是说不想通过API接口阻止无关信息 在插件内阻止

这样的话要实现匹配规则，目前没有支持，如果数据量太大，考虑使用 websocket
