### ISSUE TITLE
请问返还-1是什么原因

### ISSUE THREAD

**Issue by maolincc** [project-mirai/mirai-api-http#565]
本来好好的 控制台没显示报错 也没有显示发送

运行
			 0.0.0.0:9023/sendGroupMessage
运行
			 {"sessionKey":"SunOEjW4","group":群号,"messageChain":[{"type":"Image","url":"图片地址"}]}
		
			返回
			 {"code":0,"msg":"success","messageId":-1}

发送111111可以运行
```
			 {"sessionKey":"SunOEjW4","group":群号,"messageChain":[{"type":"Plain","text":"111111"}]}
			 {"code":0,"msg":"success","messageId":8328}
```
发送1111111又不行了
```
			 {"sessionKey":"SunOEjW4","group":群号,"messageChain":[{"type":"Plain","text":"1111111"}]}
			 {"code":0,"msg":"success","messageId":-1}
```

**Comment by ryoii** [comment]
有时候协议会发不出消息，因此没有消息id
