### ISSUE TITLE
如何开放多个http端口供多个应用程序使用？

### ISSUE THREAD

**Issue by fatinghenji** [project-mirai/mirai-api-http#576]
- 可以这样做吗？
- 可以的话能提供一个实例文件吗？
- 可以不同程序使用不同的认证吗？

**Comment by ryoii** [comment]
没料想到还有这样的使用场景

**Comment by fatinghenji** [comment]
[ChatLearning](https://github.com/Nana-Miko/ChatLearning)和[Amiya-Bot](https://github.com/AmiyaBot/Amiya-Bot)都需要使用http接口

**Comment by ryoii** [comment]
从一个端口进入有影响吗

**Comment by fatinghenji** [comment]
> 从一个端口进入有影响吗

有，先启动Amiya-Bot然后启动ChatLearing会导致chatLearning收不到消息

**Comment by ryoii** [comment]
> > 从一个端口进入有影响吗
> 
> 有，先启动Amiya-Bot然后启动ChatLearing会导致chatLearning收不到消息

我测试了一下，在 ws 模式下，非 singleMode，使用不同 session 连接不会导致收不到消息，是不是这两个应用的哪一个出问题了

**Comment by fatinghenji** [comment]
不太清楚（
ChatLearing不推荐使用新版本的mirai-http

**Comment by wyapx** [comment]
非single mode，不同连接是分离的
各个连接不会互相影响
