### ISSUE TITLE
提供持久化的消息缓存

### ISSUE THREAD

**Issue by Wybxc** [project-mirai/mirai-api-http#579]
现在的消息缓存全部在内存中，重启之后就会消失。

能否考虑增加持久化缓存的可选项，将消息缓存保存到数据库中？

**Comment by cssxsh** [comment]
给我的 https://github.com/cssxsh/mirai-hibernate-plugin 写了个 http 扩展 https://github.com/cssxsh/mirai-hibernate-http

路由和返回值有待优化

**Comment by ryoii** [comment]
由第三方提供
