### ISSUE TITLE
[新功能请求] 获取当前 bot qq 号

### ISSUE THREAD

**Issue by LenorEric** [project-mirai/mirai-api-http#582]
botProfile 中可以得到 bot 的详细资料，但是不包括 qq 号，而 bot 相关 event 虽然会返回 qq 号但是不能主动触发，错过了就不能再得到。
以及似乎没看到其他方式可以提供这个信息。
这个功能可以提升某些场景下的自动化程度。
不知道 core 有没有相关接口，如果有的话可以增加这个功能吗

**Comment by sjx233** [comment]
`sessionInfo` 可以满足需求吗？

**Comment by LenorEric** [comment]
> 

听上去是可以的，但是似乎我没有在文档中找到这个指令。可能是我瞎了，方便附一下文档链接嘛

**Comment by sjx233** [comment]
是 4e7d094 加入的（好像确实缺文档

```http
GET /sessionInfo?sessionKey=YourSessionKey
```

```json
{
  "code": 0,
  "msg": "",
  "data": {
    "sessionKey": "YourSessionKey",
    "qq": {
      "id": 1234567890,
      "nickname": "",
      "remark": ""
    }
  }
}
```
