### ISSUE TITLE
[新功能请求]获取群员资料时能够获取到该成员的群称号(荣誉)

### ISSUE THREAD

**Issue by lkiuyu** [project-mirai/mirai-api-http#588]
目前好像只有群称号改变事件，没找到怎么获取群称号的方法，希望能够支持获取

**Comment by ryoii** [comment]
没有查到 core 由这样的功能支持，有的化烦请告知

**Comment by lkiuyu** [comment]
> 没有查到 core 由这样的功能支持，有的化烦请告知

这个链接里面，貌似有添加接口https://github.com/mamoe/mirai/pull/501

**Comment by ryoii** [comment]
仔细看接口，获取的是群的荣誉的列表，而不是群员的群荣誉

**Comment by 1312255201** [comment]
GroupTalkativeChangeEvent是指这个吗
