### ISSUE TITLE
语音发送失败[json.exception.type_error.302] type must be string, but is null

### ISSUE THREAD

**Issue by wly20040415** [project-mirai/mirai-api-http#589]
语音路劲、后缀完全正确，但编译之后发送失败

**Comment by ryoii** [comment]
不知道你的编译后指的是什么

有 SDK 的话提供 SDK 的报错，你自身代码的报错。包括你的请求，返回值。可能的话，提供 MAH 的日志，或者打开 MAH 的 debug 模式提供更完整的日志

**Comment by ryoii** [comment]
推测为 SDK 的序列化错误，如果问题，重新打开 issue
