### ISSUE TITLE
mirai 升级到 2.12 后群文件上传没有发送消息

### ISSUE THREAD

**Issue by nitsort** [project-mirai/mirai-api-http#594]
mirai 升级到 2.12 后群文件上传后聊天界面没有消息，文件是上传成功的。

版本：
mirai-console: v2.12.0
mirai-console-terminal: v2.12.0
mirai-core-all: v2.12.0
mcl-addon: v2.0.2
mirai-api-http: v2.5.2
bcprov-jdk15on: v1.64

**Comment by ryoii** [comment]
印象中 core 禁用了发送文件消息的接口，统一通过上传时自动发送文件消息。
如果是这样的话，代码行为上应该是正确的，但我不太确定。
稍后排查后确认下是否应该把问题提交到 core

**Comment by ryoii** [comment]
稍微测试了一下，确实是 core 的 bug

我尝试手动发送消息，会被 core 阻止

**Comment by ryoii** [comment]
mamoe/mirai#2195

**Comment by ryoii** [comment]
core `2.12.2` 已修复
