### ISSUE TITLE
文档错误：API文档内允许在好友聊天内移动文件，创建文件夹等

### ISSUE THREAD

**Issue by FurryR** [project-mirai/mirai-api-http#597]
有target，group和qq三个参数，那我应该传哪个？

**Comment by 0f-0b** [comment]
`target` 和 `group` 都表示群号，`qq` 暂时还不可用。

**Comment by FurryR** [comment]
> `target` 和 `group` 都表示群号，`qq` 暂时还不可用。

感谢。但是，仍然有一部分API的文档是错误的，比如不可能在好友聊天内新建文件夹，但`API/新建文件夹`的“请求”部分仍然有`qq`参数。

**Comment by Numendacil** [comment]
```目前仅支持群文件的操作, 所有好友文件的字段为保留字段```
文档里有说这个的来着
