### ISSUE TITLE
[接口错误]MusicShare接口

### ISSUE THREAD

**Issue by HexMikuMax** [project-mirai/mirai-api-http#599]
发送音乐卡片分享时出现
{'code': 500, 'msg': 'No enum constant net.mamoe.mirai.message.data.MusicKind.String'}
出现枚举错误🤔

**Comment by ryoii** [comment]
请求传了个什么类型啊

**Comment by HexMikuMax** [comment]
String

**Comment by HexMikuMax** [comment]
> 请求传了个什么类型啊

用的是Python json.dumps 把字典转换后传的

**Comment by ryoii** [comment]
只支持 `NeteaseCloudMusic`, `QQMusic`, `MiguMusic`, `KugouMusic`, `KuwoMusic`
