### ISSUE TITLE
反向 ws 无法独立完成鉴权

### ISSUE THREAD

**Issue by ieew** [project-mirai/mirai-api-http#610]
没有通过监权就无法在 ws 内使用 `botList` 和 `about` 和 `verify` 命令。mah统一回复 `{"code":1,"msg":"Auth Key错误"}` 

已知：
发送的 verifyKey 没有错误

**Comment by ryoii** [comment]
反向 ws 好像需要在连接上的时候就完成鉴权，我考虑下这里是不是要保持原有逻辑

**Comment by ieew** [comment]
> 反向 ws 好像需要在连接上的时候就完成鉴权，我考虑下这里是不是要保持原有逻辑

我认为这种逻辑用于正向 ws 比较合适，不应该用于反向 ws。现有逻辑让反向 ws 完全没有存在的意义了。

**Comment by BlueGlassBlock** [comment]
> 反向 ws 好像需要在连接上的时候就完成鉴权，我考虑下这里是不是要保持原有逻辑

但是连接上就鉴权现在会导致 `code 2`，因为连接时 Bot 还没完成登录，导致 `Bot.getInstanceOrNull(dto.qq)` 返回 `null`
