### ISSUE TITLE
[功能请求] 图片上传接口能否支持传入图片URL

### ISSUE THREAD

**Issue by Jadlokin-Scarlet** [project-mirai/mirai-api-http#613]
Http Adapter专有接口图片文件上传目前是传入File上传图片，这需要先把图片保存到本地再上传，服务器水管小有点慢。
但是若是直接在chain里使用type：Image的url参数，则会因为一条消息包含多张图片使得发送一条消息需要数十秒从而导致http请求超时。
希望该接口能支持URL上传图片或者另开一个通过URL上传图片的接口。

**Comment by ryoii** [comment]
通过url上传也是要下载到本地的，如果觉得直接将图片上传到本地再发送到 http 比较占 IO，我认为你可以试一下 SDK 将图片下载到本地后，使用文件路径构造 Image

**Comment by Jadlokin-Scarlet** [comment]
目前的情况是bot服务和mirai服务分开部署，不在一台服务器上，bot下载了图片后，再上传给mirai，mirai收到图片后在上传到QQ，是双倍的耗时，如果可以支持URL的话，就可以少一个上传到mirai

**Comment by Godmyhave** [comment]
是不是可以先上传，然后使用上传后返回的id发送图片。
