### ISSUE TITLE
撤回消息的文档API与实际代码层面API不一致，导致错误，麻烦作者修改/更新文档API

### ISSUE THREAD

**Issue by q2398003522** [project-mirai/mirai-api-http#614]
在[撤回消息的文档API](https://github.com/project-mirai/mirai-api-http/blob/master/docs/api/API.md#%E6%92%A4%E5%9B%9E%E6%B6%88%E6%81%AF)中写的POST格式为
```
{
  "sessionKey":"YourSession",
  "target":987654321,
  "messageId":12345
}
```
但是POST后出现错误，经过修改分析，是文档API写的不对。
我个人认为是，代码API修改了，但文档API并没有同步修改。
按照正确的调用方式，以上内容应改成
```
{
  "sessionKey":"YourSession",
  "target":12345, // target后面跟的是messageId，并且没有messageId项
}
```

**Comment by 0f-0b** [comment]
[2.6.0 起](https://github.com/project-mirai/mirai-api-http/blob/v2.6.0/CHANGELOG.md#%E5%8F%98%E6%9B%B4)确实需要同时传 `target` 和 `messageId`。

**Comment by q2398003522** [comment]
好的，谢谢
