### ISSUE TITLE
不知道按了那个组合键，控制台提示W/console: Closing input service...

### ISSUE THREAD

**Issue by chuchenyl** [project-mirai/mirai-api-http#617]
报错信息
W/console: Closing input service...
mirai-api-http版本2.6.1

**Comment by 0f-0b** [comment]
Windows 下 <kbd>Ctrl</kbd> + <kbd>Z</kbd> 或者 Linux 下 <kbd>Ctrl</kbd> + <kbd>D</kbd> 确实是关闭输入的组合键。这和 mirai-api-http 无关。
