### ISSUE TITLE
getBotList 404

### ISSUE THREAD

**Issue by maolincc** [project-mirai/mirai-api-http#626]
"version":"2.6.2"

![image](https://user-images.githubusercontent.com/99097802/190121331-04ced5bc-172b-4c3c-bcf8-317bda256198.png)
![image](https://user-images.githubusercontent.com/99097802/190121461-cad2b25c-49ca-4fca-b568-aae264569410.png)

**Comment by 0f-0b** [comment]
[2.6.2 的文档](https://github.com/project-mirai/mirai-api-http/blob/v2.6.2/docs/adapter/HttpAdapter.md#%E8%8E%B7%E5%8F%96%E7%99%BB%E5%BD%95%E8%B4%A6%E5%8F%B7)写的是 `/botList`。

**Comment by maolincc** [comment]
> [2.6.2 的文档](https://github.com/project-mirai/mirai-api-http/blob/v2.6.2/docs/adapter/HttpAdapter.md#%E8%8E%B7%E5%8F%96%E7%99%BB%E5%BD%95%E8%B4%A6%E5%8F%B7)写的是 `/botList`。

好的
