### ISSUE TITLE
接收语音消息时报错

### ISSUE THREAD

**Issue by RF-Tar-Railt** [project-mirai/mirai-api-http#638]
如图
![图片](https://user-images.githubusercontent.com/42648639/197944626-d44abfdd-dd0e-4757-8953-eabe713fe6a7.png)

经测试发现mcl端能够正常收到语音，但mah端会报错，并导致下游无法收到该消息

**Comment by cssxsh** [comment]
https://github.com/mamoe/mirai/commit/9eef7d378719476e8f9352acfe6328111d3734db

mirai 本体的问题

可以尝试更新到最新版修复
