### ISSUE TITLE
希望在消息或者获取qq好友和群成员列表的接口中能加入用户的头像在线地址信息。

### ISSUE THREAD

**Issue by wordweb** [project-mirai/mirai-api-http#644]
希望在消息或者获取qq好友和群成员列表的接口中能加入用户的头像在线地址信息。
目前的mirai-api-http所有接口都无法获取这些用户的头像信息。mirai核心库应该是支持获取的。为啥不能通过http给出来呢？希望加上。

**Comment by ryoii** [comment]
善用 issue 搜索 #371
