### ISSUE TITLE
httpapi-2.6.2 /cmd/execute 怎么获取命令行返回结果

### ISSUE THREAD

**Issue by 2354452553** [project-mirai/mirai-api-http#645]
对命令行提交指令以后怎么返回命令行返回的结果
如：/help 等

它只会返回 {"code":0,"msg":"success"}

**Comment by ryoii** [comment]
没有办法。指令不是一问一答的响应模式。指令会把结果输出到控制台，还是输出到指定群，甚至没有输出只静默处理逻辑，都是指令设计实现的逻辑。/cmd/execute 只会帮你把指令提交给 console 执行
