### ISSUE TITLE
升级到2.6.2版本，Http请求返回的内容不生效（Webhook模式）

### ISSUE THREAD

**Issue by landall** [project-mirai/mirai-api-http#649]
之前是Mirai Console 2.10 RC2 + mira api http 2.6.1强行运行（关掉了MCL自动升级），执行是正确的，webhook发来的请求，处理完返回json后，能够自动向发送信息的QQ回复消息。

升级到Mirai Console 2.13 + mirai api http 2.6.2后，所有原来执行正确的代码都失去作用了。没有看到Mirai Console报错，但是消息没法回复给发送方。

**Comment by ryoii** [comment]
参考配置文件，把 debug 模式打开，看看有没有 debug 报错内容输出。猜测是 core 升级后 ktor 依赖出现问题

**Comment by MR-XieXuan** [comment]
确实没有生效,现在我使用的是主动调用，不用 webhook 返回才正常

**Comment by landall** [comment]
但主动调用会有两个问题，
一个是需要额外的身份认证，额外的网络端口。
另一个是在速度上有问题。
回复图片似乎原来的mirai-api-http就有问题，所以看不太出来。
但回复文字的速度差异非常明显。


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "project-mirai/mirai-api-http"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年12月22日(星期四) 下午3:06
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [project-mirai/mirai-api-http] 升级到2.6.2版本，Http请求返回的内容不生效（Webhook模式） (Issue #649)





 
确实没有生效,现在我使用的是主动调用，不用 webhook 返回才正常

**Comment by MR-XieXuan** [comment]
> 但主动调用会有两个问题， 一个是需要额外的身份认证，额外的网络端口。 另一个是在速度上有问题。 回复图片似乎原来的mirai-api-http就有问题，所以看不太出来。 但回复文字的速度差异非常明显。
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "project-mirai/mirai-api-http" ***@***.***&gt;; 发送时间:&nbsp;2022年12月22日(星期四) 下午3:06 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [project-mirai/mirai-api-http] 升级到2.6.2版本，Http请求返回的内容不生效（Webhook模式） (Issue #649) 确实没有生效,现在我使用的是主动调用，不用 webhook 返回才正常 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;
是的,我看你会用 PHP ，你用的是原生PHP还是现成的框架啊

**Comment by MR-XieXuan** [comment]
现在好了吗?
