### ISSUE TITLE
希望支持emoji表情的 接受/发送

### ISSUE THREAD

**Issue by ATFGK** [project-mirai/mirai-api-http#650]
希望支持emoji表情的 接受/发送

**Comment by ryoii** [comment]
文本自持utf-8，直接发 utf-8 的 emoji 不就好了。如果是内置的表情，就是 Face 类型

**Comment by ATFGK** [comment]
> 文本自持utf-8，直接发 utf-8 的 emoji 不就好了。如果是内置的表情，就是 Face 类型

感谢帮忙~~
