### ISSUE TITLE
2.6.2发送消息返回状态码500

### ISSUE THREAD

**Issue by 2354452553** [project-mirai/mirai-api-http#651]
返回状态码500 arraycopy: last destination index 4132 out of bounds for byte[4096]

修改了cacheSize并重启还是没有用

**Comment by ryoii** [comment]
日志里有没有比较完整的堆栈报错，看起太不太像 mah 出现的错误

**Comment by 2354452553** [comment]
没有，但是我把消息分割了因为它太长了。分割了就变得好起来了。

**Comment by 2354452553** [comment]
> 日志里有没有比较完整的堆栈报错，看起太不太像 mah 出现的错误

没有，但是我把消息分割了因为它太长了。分割了就变得好起来了。

**Comment by 2354452553** [comment]
> 是 [mamoe/mirai#2309](https://github.com/mamoe/mirai/issues/2309) 吗？

是的是的就是这个
