### ISSUE TITLE
运行服务时报了aiohttp.client_exceptions.WSServerHandshakeError: 404, message='Invalid response status'，应该是哪里配置的问题？

### ISSUE THREAD

**Issue by codeofgeass** [project-mirai/mirai-api-http#656]
`aiohttp.client_exceptions.WSServerHandshakeError: 404, message='Invalid response status', url=URL('http://localhost:8080/all?qq=1935055902&verifyKey=GraiaxVerifyKey')
2022-12-12 15:07:36.870 | WARNING  | graia.ariadne.connection.ws:_:75 - Websocket reconnecting in 5s...
2022-12-12 15:07:41.871 | WARNING  | graia.ariadne.connection.ws:_:77 - Websocket reconnecting...
`

**Comment by ryoii** [comment]
是不是没有开启 ws 对应的 adapter，把配置文件发出来看看？

**Comment by codeofgeass** [comment]
> 是不是没有开启 ws 对应的 adapter，把配置文件发出来看看？
配置见下，其实有一次都成功了，然后换了个qq号又不行了、、、

adapters:
        -http
        -ws

enableVerify: true
verifyKey: GraiaxVerifyKey

debug: false

singleMode: false

cacheSize: 4096

adapterSettings:
        http:
                host: localhost
                port: 8080
                cors: ["*"]
                unreadQueueMaxSize: 100

        was:
                host: localhost
                port: 8080
                reservedSynId: -1

**Comment by codeofgeass** [comment]
> > 是不是没有开启 ws 对应的 adapter，把配置文件发出来看看？
> > 配置见下，其实有一次都成功了，然后换了个qq号又不行了、、、
> 
> adapters: -http -ws
> 
> enableVerify: true verifyKey: GraiaxVerifyKey
> 
> debug: false
> 
> singleMode: false
> 
> cacheSize: 4096
> 
> adapterSettings: http: host: localhost port: 8080 cors: ["*"] unreadQueueMaxSize: 100
> 
> ```
>     was:
>             host: localhost
>             port: 8080
>             reservedSynId: -1
> ```

顺带一提，最后的was改成了ws也没用，我直接复制的mirai官网上的yaml也没用，太奇怪了，mirai官网：
https://graiax.cn/before/install_mirai.html

**Comment by ryoii** [comment]
makrdown 排版不熟悉的话，可以直接上传配置文件，这错乱的排版我根本不知道是不是配置文件的问题

**Comment by codeofgeass** [comment]
> makrdown 排版不熟悉的话，可以直接上传配置文件，这错乱的排版我根本不知道是不是配置文件的问题

谢谢你的帮助，问题已经解决了，因为我换了一个qq号做机器人，但是qq号的环境变量没有改，改了之后启动成功了。
（虽然额度已经都用完了。。。）
