### ISSUE TITLE
请问如何使用api接口发送语音

### ISSUE THREAD

**Issue by MuBai-He** [project-mirai/mirai-api-http#657]

**Comment by ryoii** [comment]
构造 Message 的时候按照 [这个](https://github.com/project-mirai/mirai-api-http/blob/master/docs/api/MessageType.md#voice) 构造

或者通过 [这个接口](https://github.com/project-mirai/mirai-api-http/blob/master/docs/adapter/HttpAdapter.md#%E8%AF%AD%E9%9F%B3%E6%96%87%E4%BB%B6%E4%B8%8A%E4%BC%A0) 上传语音后，根据返回的参数去构造 Message

语音并不支持所有格式的音频，使用前先了解清楚

**Comment by MuBai-He** [comment]
谢谢
