### ISSUE TITLE
上传群文件报错，但实际上上传成功了

### ISSUE THREAD

**Issue by ATFGK** [project-mirai/mirai-api-http#665]
返回这个内容：
{"code":500,"msg":"Sending FileMessage is not allowed, as it may cause unexpected results. Add JVM argument `-Dmirai.message.allow.sending.file.message=true` to disable this check. Do this only for compatibility!"}

但群文件实际上传成功了，群里也收到了上传群文件成功的提示了

**Comment by ATFGK** [comment]
> 
 按照这种方法不再报错了，但是却提示了两次上传文件提示
![C`OGQUUS }@FIJ9@CISTLYT](https://user-images.githubusercontent.com/62204605/212444518-1952b01d-fe76-4f68-abdd-8a3c8d69bb0d.png)

**Comment by Apicer** [comment]
这个我也不太清楚，我这块也是这样，提了issues,也没人回复，有可能是api版本问题吧

**Comment by ATFGK** [comment]
之前我提过一个issues说上传完文件不会提示消息，然后采纳了之后现在提示两次........

**Comment by Apicer** [comment]
但是上传完文件会有返参，你看下你的返参里的parent节点是否有值，如果有值的话就跟我的应该是一样的问题，我看文档上的parent节点是为null，可能就是因为这个parent节点才导致发送两次，我也就知道这么多

**Comment by ATFGK** [comment]
> 但是上传完文件会有返参，你看下你的返参里的parent节点是否有值，如果有值的话就跟我的应该是一样的问题，我看文档上的parent节点是为null，可能就是因为这个parent节点才导致发送两次，我也就知道这么多

有值，看来是一样的

**Comment by ryoii** [comment]
那就是之前的 bug 提交反馈没有发送是误报了

**Comment by ATFGK** [comment]
之前的bug是确实存在的



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年1月14日(星期六) 晚上10:35
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [project-mirai/mirai-api-http] 上传群文件报错，但实际上上传成功了 (Issue #665)





 
那就是之前的 bug 提交反馈没有发送是误报了
