### ISSUE TITLE
v2.6.2 无法获取消息 返回500

### ISSUE THREAD

**Issue by NeetXuu** [project-mirai/mirai-api-http#669]
环境
Running MiraiConsole v2.13.2, built on 2022-12-04 17:50:53.
Frontend Terminal: version 2.13.2, provided by Mamoe Technologies
Permission Service: Built In Permission Service
Plugins: Chat Command v0.5.0, net.mamoe.mirai-api-http v2.6.2, MCL Addon v2.1.1
开启singleMode 关闭verify
获取消息相关的api全部返回以下内容
{"code":500,"msg":"Not a http session"}

**Comment by ryoii** [comment]
该问题在  2.7 被修复 #658
