### ISSUE TITLE
mirai-api-http上传群文件功能，调用一次请求，上传两个相同的文件

### ISSUE THREAD

**Issue by Apicer** [project-mirai/mirai-api-http#670]
使用mcl搭配mirai-api-http使用，java使用上传群文件功能时，http请求明明只发送了一次，但是群文件却上传了两次
mirai-api-http版本：2.7.1
mirai-core版本：2.13.2
文件上传后返参：
`{ "code":0, "msg":"", "data":{ "name":"有没有特别血腥恐怖文章？.txt", "id":"/c2737b3b-f1bd-4964-b3a5-b14f70a4b58c", "path":"/有没有特别血腥恐怖文章？.txt", "parent":{ "name":"/", "id":"/", "path":"/", "parent":null, "contact":{ "id":663903282, "name":"Mirai Robot", "permission":"MEMBER" }, "isFile":false, "isDictionary":true, "isDirectory":true, "size":0, "sha1":null, "md5":null, "uploaderId":null, "uploadTime":null, "lastModifyTime":null, "downloadInfo":null }, "contact":{ "id":663903282, "name":"Mirai Robot", "permission":"MEMBER" }, "isFile":true, "isDictionary":false, "isDirectory":false, "size":39090, "sha1":"ACAF7286F826F255B976923DF277996401229437", "md5":"F91A183B14B6A019256245477E3128B7", "uploaderId":1398783998, "uploadTime":1673318361, "lastModifyTime":1673318361, "downloadInfo":null } }`

这个是我群文件上传后返回的参数，我看文档示例parent节点为null，而我的不知道为什么有值

**Comment by ryoii** [comment]
#665

**Comment by Apicer** [comment]
@ryoii 那这个就属于是mirai-api-http的bug吗？
