### ISSUE TITLE
500 Not a http session 问题

### ISSUE THREAD

**Issue by linux-rm** [project-mirai/mirai-api-http#676]
在使用这些接口时均出现问题

![1](https://user-images.githubusercontent.com/100938047/214970151-d0c01845-d202-4d9e-9034-49daa11d698c.jpg)

但其它接口正常

![2](https://user-images.githubusercontent.com/100938047/214970224-9bb0fa92-eb26-4ff7-8a9b-d7b1838c5e96.jpg)

**Comment by linux-rm** [comment]
已知我刚 `./mcl -u` 更新

**Comment by ryoii** [comment]
2.7及以上版本已经修复
