### ISSUE TITLE
forward中的preview字段

### ISSUE THREAD

**Issue by 73desi** [project-mirai/mirai-api-http#680]
我看见别人能够实现不打开转发消息是一个内容，打开转发消息是另一个内容，我在mcl看见一个关键字：preview，这个关键字应该就是在没打开的时候展示的内容，我在api文档里面找到forword却没有这个关键字，在新的版本是会适配这个关键字么？

**Comment by cssxsh** [comment]
> 我在mcl看见

mcl (mirai-console-loader) https://github.com/iTXTech/mirai-console-loader
mirai https://github.com/mamoe/mirai/
mirai-console https://github.com/mamoe/mirai/tree/dev/mirai-console

mcl != mirai and mcl != mirai-console

**Comment by 73desi** [comment]
我想实现的是这样的效果，没展开是这样
![image](https://user-images.githubusercontent.com/69508411/217152032-db97d8a1-2200-4a85-b76d-7bb52fd5f09a.png)
展开了是这样
![image](https://user-images.githubusercontent.com/69508411/217152052-0a892fda-9f80-42f7-841f-92eaf047a711.png)
mcl的是这样
![image](https://user-images.githubusercontent.com/69508411/217152099-1ed9e5dc-faeb-480a-8d61-aaf2c0fb0d70.png)

**Comment by cssxsh** [comment]
mirai 原生的API 确实有可以自定义显示信息的功能

https://github.com/mamoe/mirai/blob/42334c42c5088ba57056fa1969ca85f9b5210f4a/mirai-core-api/src/commonMain/kotlin/message/data/ForwardMessage.kt#L31-L48

不过我估计你等不来, 负责管理 mirai-api-http 的 ryoii 很忙 没空


另外再说一遍 `mcl != mirai` and `mcl != mirai-console`

mirai 的本体实际上在 mcl 目录下 libs 文件夹,你可以打开看看

至于为什么强调不同, 
是因为总有人在提交问题的时候, 把 mcl 的版本信息当作 mirai 的提交, 给问题诊断带来问题
2.13.0 开始出现的大 logo 就是为了强调这是 Mirai Console 不是 MCL

还有就是

从 `2023-02-07 12:22:37 I/main: Starting mirai-console...` 
开始就是 Mirai Console 本身的日志了, 这些日志同时也会存在 logs 文件夹
而在前面的日志 `12:22:35 [INFO] Verifying ...` 则是 MCL 的

**Comment by 73desi** [comment]
行吧，感觉有这个字段的话可以实现更多的功能
mcl != mirai and mcl != mirai-console

**Comment by MDeath** [comment]
以前我是通过xml替换转发聊天记录id实现的
