### ISSUE TITLE
收到Quote类型消息时，其中的id有可能为负数，导致使用messageFromId查询找不到对象

### ISSUE THREAD

**Issue by MDeath** [project-mirai/mirai-api-http#681]
![image](https://user-images.githubusercontent.com/42289879/217402841-cb5a93ff-fb00-418f-90aa-c08865f683b1.png)
![image](https://user-images.githubusercontent.com/42289879/217404101-16b573a8-c72f-40e1-beb5-99178deea3ae.png)
我用官方安卓客户端，机器人是用的ipad配置
图中是从一个群聊（机器人不在里面）转发图片（使用上图方法）给机器人，机器人收到消息ID：56785
接着我回复我转发的图片，机器人收到消息ID：56789。可是消息链中的Quote ID为负数导致使用messageFromId查询找不到对象
猜测：使用图2的方法转发可以不点开图片下载原图，也能直接发送原图，可能是腾讯的ID引用导致

**Comment by MDeath** [comment]
现在的版本是2.7.1
之前2.5.2也有：https://github.com/project-mirai/mirai-api-http/issues/469

**Comment by ryoii** [comment]
我对您的描述不是特别清晰，但你可以确认一下和这个 #682 是不是同一个问题

**Comment by MDeath** [comment]
是的

> 我对您的描述不是特别清晰，但你可以确认一下和这个 #682 是不是同一个问题
