### ISSUE TITLE
bot收到的回复bot发送的消息中，Quote里的messageId有误

### ISSUE THREAD

**Issue by Jadlokin-Scarlet** [project-mirai/mirai-api-http#682]
bot发送**好友**消息后，主人在**安卓端**回复bot的消息，bot收到的回复消息中，Quote里的messageId和bot发送好友消息时的返回的messageId不一致。
ps：QQpc端回复没问题

1. bot发送**好友**消息
![image](https://user-images.githubusercontent.com/32767557/218259436-521d01e4-73d6-40fa-a5ec-fa65655c6442.png)
![image](https://user-images.githubusercontent.com/32767557/218259473-33ef4ea5-0a62-4656-a236-bf287b9502ff.png)
2. 主人在**QQ安卓端**回复bot消息（图一为pc端回复是正确的，图二是安卓端回复，messageId是不对的）
![image](https://user-images.githubusercontent.com/32767557/218259693-b2879252-cffd-4ba6-880d-73cdbc91b154.png)
![image](https://user-images.githubusercontent.com/32767557/218259677-b053309c-aa3c-487e-b810-75f751f3fe8b.png)

**Comment by ryoii** [comment]
从日志上看，从 core 上获取到引用里的 messageId 就已经带负数了，我怀疑是 core 的问题

**Comment by ryoii** [comment]
从其他 issue 反馈上看，这个出现负数的 messageId 貌似都会出现错误值的情况

**Comment by Jadlokin-Scarlet** [comment]
需要在mirai那边再提一个issue吗

**Comment by ryoii** [comment]
我用 core 复现一下

**Comment by ryoii** [comment]
我复现了，确实是 core 的问题，而且引用中错误的 messageId 会是正确 messageId 的 16 位补码，推断是 core 对好友引用消息的 messageId 生成错误了
