### ISSUE TITLE
 Exception while enabling mirai-api-http

### ISSUE THREAD

**Issue by tori-hotaru** [project-mirai/mirai-api-http#683]
错误如图
![B6`JP@$8QS)%EWXTJ7BKQY3](https://user-images.githubusercontent.com/58972377/218266255-b61201f2-58d1-418e-85d4-eaa7db5401db.png)
我的config文件如图所示：
![HJXP%A}BHL3P}7~$ZNBRF1I](https://user-images.githubusercontent.com/58972377/218266347-03944842-f497-4ec5-8199-c639103d0dea.png)
尝试将channel改为maven-stable仍然出现上述问题

**Comment by cssxsh** [comment]
plugins 里面有重复的插件
