### ISSUE TITLE
机器人通过ws协议发送类型为Forward的群消息时，内容显示不出来

### ISSUE THREAD

**Issue by 3CB3EC** [project-mirai/mirai-api-http#684]
发送Forward类型的内容，调用成功，QQ群内查看无任何显示
改为Plain类型测试，QQ群内正常显示内容

未尝试用其他协议发送
mirai版本是2月10号QQ服务器爆炸后升级的2.14.0
http插件版本mirai-api-http-2.8.0.mirai2

似乎这个问题以前版本曾经有过，并修复过

**Comment by cssxsh** [comment]
转发合并消息 很容易被风控

**Comment by 3CB3EC** [comment]
> 转发合并消息 很容易被风控

好的，那我以后改其他方式了
