### ISSUE TITLE
File "python3.9/dist-packages/revChatGPT/V2.py", line 169, in ask raise Exception("Unknown error")

### ISSUE THREAD

**Issue by fairy7** [project-mirai/mirai-api-http#686]
使用session_token登录openai，paid=false，和机器人对话时抛错

报错如图
![image](https://user-images.githubusercontent.com/30788660/219280178-095a73d6-028b-4796-82fa-b6e6baf5c2c0.png)
![image](https://user-images.githubusercontent.com/30788660/219280308-c85203bd-b4d0-43a7-b8dc-5235031df024.png)

网上的一些回复 <https://pullanswer.com/questions/bug-exception-unknown-error>

必须要plus用户吗？

**Comment by ryoii** [comment]
哪个地方的代码请把 issue 开到对应的项目，该问题内容和本项目无关
