### ISSUE TITLE
实现共存v1和v2接口，任何方法？

### ISSUE THREAD

**Issue by keke1229488344** [project-mirai/mirai-api-http#692]
虽然但是，这个issue提的有点晚（或者需求不高）...
之前一直使用mirai双开的方式同时实现v1和v2版本的共存...但是随着最近一波tx大规模重置缓存，发现只能登上watch的协议了...
所以，是否有方法实现共存...?

**Comment by ryoii** [comment]
fork仓库把v1分支切出来该个plugin id，仓库的workflow可以自动编译。自己编一个不冲突的v1就好了

**Comment by keke1229488344** [comment]
按照你的方法解决了，非常感谢🌹！！
