### ISSUE TITLE
一直无法登录，显示：Login failed: Error(bot=Bot(2087882253), code=45, title=禁止登录, message=登录失败，建议升级最新版本后重试，或通过问题反馈与我们联系。, errorInfo=)

### ISSUE THREAD

**Issue by amazing-fish** [project-mirai/mirai-api-http#694]
![image](https://user-images.githubusercontent.com/71763696/222918939-6008e277-ebdb-46d3-b188-e9c2fc3422f0.png)

**Comment by ryoii** [comment]
升级 core 到 2.14

**Comment by amazing-fish** [comment]
不知道怎么升级，我用/mclx update 显示不能热更新插件，建议重启，但是也不行

**Comment by cssxsh** [comment]
> 不知道怎么升级，我用/mclx update 显示不能热更新插件，建议重启，但是也不行

https://mirai.mamoe.net/topic/1653

**Comment by amazing-fish** [comment]
更新完后

> > 不知道怎么升级，我用/mclx update 显示不能热更新插件，建议重启，但是也不行
> 
> https://mirai.mamoe.net/topic/1653

更新完后要用滑动验证码，那个真的搞不出

**Comment by MDeath** [comment]
> 更新完后
> 
> > > 不知道怎么升级，我用/mclx update 显示不能热更新插件，建议重启，但是也不行
> > 
> > 
> > https://mirai.mamoe.net/topic/1653
> 
> 更新完后要用滑动验证码，那个真的搞不出

https://github.com/mzdluo123/TxCaptchaHelper

**Comment by ctexthuang** [comment]
> 升级 core 到 2.14

我已经升级2.14了 依然还是报这个错误
<img width="568" alt="image" src="https://user-images.githubusercontent.com/24536224/225593319-f7110d5c-0b7a-402c-aa35-d7b34202aec7.png">

**Comment by cssxsh** [comment]
> > 升级 core 到 2.14
> 
> 我已经升级2.14了 依然还是报这个错误 <img alt="image" width="568" src="https://user-images.githubusercontent.com/24536224/225593319-f7110d5c-0b7a-402c-aa35-d7b34202aec7.png">

https://github.com/mamoe/mirai/issues/2570

**Comment by yueyukui** [comment]
出现这种问题的原因是需要手机短信验证码，mirai的配置文件AutoLogin.yml改成MACOS协议，后面会让你输入短信验证码，就可以了
