### ISSUE TITLE
可以外接Java程序不

### ISSUE THREAD

**Issue by onega1** [project-mirai/mirai-api-http#696]
用java写了个socket客户端是不是没法连接这个

**Comment by ryoii** [comment]
可以

**Comment by onega1** [comment]
ws://host:port/all?verifyKey=KEY&qq=123456
我这样子请求连接不上

**Comment by onega1** [comment]
大佬看看







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "project-mirai/mirai-api-http"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月8日(星期三) 晚上9:36
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [project-mirai/mirai-api-http] 可以外接Java程序不 (Issue #696)





 
上代码上配置

**Comment by onega1** [comment]
![图片](https://user-images.githubusercontent.com/55702118/223730787-af5d191f-de09-4bf2-95a1-dcdfe3a9a45c.png)
![图片](https://user-images.githubusercontent.com/55702118/223730816-4d86d85a-7020-44cc-a81c-3800168f6330.png)

**Comment by ryoii** [comment]
说一下你用的什么库，导的包我也看不见，上下文我也看不见，贴代码就贴多点，截个图就几十行给谁看

**Comment by onega1** [comment]
全部逻辑就这些，从这个start方法开始  库用的是这个
![图片](https://user-images.githubusercontent.com/55702118/223743239-2ea15cbd-a45a-4a54-853a-7556e518cb18.png)

**Comment by ryoii** [comment]
这个库是做私有socket通信的吧，和websocket没有关系

**Comment by onega1** [comment]
测试网站可以连通 o(╥﹏╥)o 我换个库试试吧 谢谢大佬
