### ISSUE TITLE
websocket客户端收不到事件?

### ISSUE THREAD

**Issue by wz605721456** [project-mirai/mirai-api-http#697]
消息和响应是正常的,但事件只会在MiraiConsole打印,websocket client没有收到
只测试了bot群权限改变,禁言,资料改变
![QQ截图20230312021139](https://user-images.githubusercontent.com/35329531/224504896-b43a706e-80a0-43cd-af4c-f61779c945fd.png)

**Comment by ryoii** [comment]
连接到 `/event' 或者 '/all' 才有事件

**Comment by wz605721456** [comment]
> 连接到 `/event' 或者 '/all' 才有事件

收到了,不好意思,是我没有视力😂😂😂
