### ISSUE TITLE
转发聊天记录标题显示效果不统一

### ISSUE THREAD

**Issue by MDeath** [project-mirai/mirai-api-http#700]
第一条是不使用display参数生成的
第二、第三条是其他官方客户端生成的
第四条是使用display参数生成的
下面最后一条是我通过以前保存的xml替换`m_resid`生成的
这个能不能解决呢因为标题在预览里感觉有点怪
```
<msg brief="[不存在]" m_fileName="3449B8A6-8E77-4EC3-8BA0-581226009501" action="viewMultiMsg" tSum="2" flag="3" m_resid="0l9jkGbD3AfGr2E2V8R9+XFQiZ+C7Z9VC0pd2n0wYcO/AIGqY5XmnFbhUbby+9ck" serviceID="35" m_fileSize="822"><item layout="1"><title color="#000000" size="34">不存在的的聊天记录 </title><title color="#000000" size="26">受、死: 假的</title><title color="#000000" size="26">受、死: 不存在</title><title color="#000000" size="26">受、死: 不是真的</title><title color="#000000" size="26">精神病院里的人: 这是真的吗</title><hr></hr><summary color="#808080" size="26">查看100条转发消息</summary></item><source name="source"></source></msg>
```
![~G4TE 69~5(LFHJ{2CDIZA7](https://user-images.githubusercontent.com/42289879/224925162-5939a74b-b72f-4c38-ad65-d1bc30514270.png)
![9B100F117D0F84B87177A1A28525A28D](https://user-images.githubusercontent.com/42289879/224925180-45aa6e63-2fc1-4e03-807e-a09d96018eff.png)
![image](https://user-images.githubusercontent.com/42289879/224929504-ad98c728-67d1-4787-9338-f3fcd92e04e9.png)
![B722D4E042141D3A713F80B7EEF0FAFE](https://user-images.githubusercontent.com/42289879/224929906-3c3e46f9-7b53-444b-9033-9220e2b7d511.png)

**Comment by ryoii** [comment]
可以把你发送请求的 json 串贴一下吗

**Comment by MDeath** [comment]
> 可以把你发送请求的 json 串贴一下吗
```
{'type': 'Forward',
 'nodeList': [{'senderId': 2907237958,
   'senderName': 'jsb',
   'messageChain': [{'type': 'Plain', 'text': 'test'}],
   'time': 1678780505}],
 'display': {'title': 'title=',
  'brief': 'brief=',
  'source': 'source=',
  'summary': 'summary='}}```

**Comment by ryoii** [comment]
消息里 `群聊的聊天记录` 那一块就是标题

**Comment by MDeath** [comment]
> 消息里 `群聊的聊天记录` 那一块就是标题
> 
> 你是想要实现什么样的效果

手机端看display标题的效果是第二张图第四条消息的效果，我想实现第四张图的效果

**Comment by ryoii** [comment]
那问题提到 core 吧，应该是不同客户端对协议解析不一样，让他们考虑适配一下

**Comment by MDeath** [comment]
> 那问题提到 core 吧，应该是不同客户端对协议解析不一样，让他们考虑适配一下

好的
