### ISSUE TITLE
Webhook收到Bot被邀请入群申请时返回json格式的疑问

### ISSUE THREAD

**Issue by shirakun** [project-mirai/mirai-api-http#701]
https://docs.mirai.mamoe.net/mirai-api-http/api/EventType.html#bot%E8%A2%AB%E9%82%80%E8%AF%B7%E5%85%A5%E7%BE%A4%E7%94%B3%E8%AF%B7
https://docs.mirai.mamoe.net/mirai-api-http/api/API.html#bot%E8%A2%AB%E9%82%80%E8%AF%B7%E5%85%A5%E7%BE%A4%E7%94%B3%E8%AF%B7
按照上面2个api拼装如下json返回后,bot没有执行任何操作,

```
{
    "command": "resp_botInvitedJoinGroupRequestEvent",
    "content": {
        "eventId": 111111,
        "fromId": 1111,
        "groupId": 11111,
        "message": "",
        "operate": 0
    }
}
```

![image](https://user-images.githubusercontent.com/11274807/225637941-2fa3016a-ca16-4b07-8be8-e872d9a5f1f8.png)

如果json返回不正确,那么正确的json应该是什么样子呢

**Comment by ryoii** [comment]
我用 mock 测试了一下是有反应的。console 有没有出现什么相关日志。响应完成后应该会触发一个 `Event: BotJoinGroupEvent.Invite` 的日志
