### ISSUE TITLE
mirai-api-http语音文件发送

### ISSUE THREAD

**Issue by Apicer** [project-mirai/mirai-api-http#706]
调用语音文件上传接口，上传wav语音文件，上传后返回参数为{"voiceId":"5ED96CF8A0764A8F74B2E92D9F07B87F.amr"}，再调用发送群消息接口sendGroupMessage，将messageChain节点参数组织程voice格式，发现发送到群里的语音文件有问题
![1679992392447](https://user-images.githubusercontent.com/55680823/228177763-684d52ba-37a7-41e6-88aa-8681547562d1.png)
播放语音文件无声音

**Comment by ryoii** [comment]
不支持 wav，手动转码到 slik 或者使用插件自动转码

**Comment by Apicer** [comment]
> 不支持wav，手动转码到slik或者使用插件自动转码

我把文件转成slik后，发送消息，这次可以文字识别，但是播放语音还是没声音
![$T6R4@1T(A@OR)YU$Q3TM~7](https://user-images.githubusercontent.com/55680823/228408122-7f6f4240-44ad-4593-aad5-1a77d0463dde.png)
