### ISSUE TITLE
账号退出或掉线后session不会过期，重新登录后这个session获取不到任何信息

### ISSUE THREAD

**Issue by MDeath** [project-mirai/mirai-api-http#707]
账号退出或掉线后session不会过期或解绑，重新登录后这个session获取不到任何信息，使用接口也只会报code:5
重新登录能不能重新绑定回旧的session，或者掉线或退出让已绑定的session过期或者需要重新绑定呢

**Comment by ryoii** [comment]
#632 关注这一边

**Comment by MDeath** [comment]
> #632 关注这一边

噢噢ok
