### ISSUE TITLE
新的session无法获取消息队列&消息内容等

### ISSUE THREAD

**Issue by ExMikuPro** [project-mirai/mirai-api-http#714]

**Comment by ExMikuPro** [comment]
本次环境是
Python 3.9
requests == 2.30.0
urllib == 1.26.15
 
miria-core-all == 2.15.0-M1
mirai-api-http == 2.9.1.mirai2

**Comment by ExMikuPro** [comment]
使用python编写的脚本
详细代码
![runoob-code](https://user-images.githubusercontent.com/72144156/236727912-0204c5cb-3740-4e1f-9488-b03aefaf056e.png)

**Comment by ExMikuPro** [comment]
返回值虽然是code:0
但是返回内容不正确
<img width="1512" alt="截屏2023-05-08 11 15 27" src="https://user-images.githubusercontent.com/72144156/236728036-d83d9273-de69-47e1-a25a-80085c55cfeb.png">
能看到新的session和旧的session申请到的data数值是不相同的，加上已经循环向Bot发送聊天消息，且未进行```获取队列头部```等操作

**Comment by ExMikuPro** [comment]
不知道是代码编写的问题还是```mirai-api-http```接口的原因

其他功能正常，仅```countMessage```,```fetchMessage```,```fetchLatestMessage```,```peekMessage```,```peekLatestMessage```

有上述问题

**Comment by ryoii** [comment]
未获取的消息是与session挂钩的，新 session 只能获取新的消息

如果需要获取到同一个缓存队列里的消息，需要 [共享同一个session](https://github.com/project-mirai/mirai-api-http/blob/master/docs/adapter/HttpAdapter.md#%E4%BC%A0%E9%80%92%E9%87%8D%E8%A6%81)
