### ISSUE TITLE
群消息发送成功，但是不显示

### ISSUE THREAD

**Issue by Apicer** [project-mirai/mirai-api-http#720]
调用群消息发送接口成功，mcl控制台也都能看见，但是在群聊中未显示，而且调用群消息发送接口返回的messageId是-1，这是被风控了吗？
![1685093362877](https://github.com/project-mirai/mirai-api-http/assets/55680823/a5bfaf77-67ef-49d2-aed5-ab22af4dbc09)
![1685093664009](https://github.com/project-mirai/mirai-api-http/assets/55680823/b9ff2424-e92f-41b3-9402-c2e9d9cb995e)

**Comment by ryoii** [comment]
风控或者涩图太涩

**Comment by lengzu** [comment]
大量的人都出现了这个问题 很多人今天在和我说这个 有没有解决方法
