### ISSUE TITLE
请教mirai-api-http + graia-ariadne 突然提示your account may be blocked

### ISSUE THREAD

**Issue by wy-Eternity** [project-mirai/mirai-api-http#721]
机器人是mirai 2.15.0-M1 采用的手表扫码登录的方式，之前一直挺正常的，今天下午突然出现这种提示“failed to send message,your account may be blocked”。换了一个qq号采用同样的扫码登录后，正常运行了十几分钟，突然又开始出现上述提示，现在两个号扫码登录能等，自动发消息不行，手机qq上发消息正常的。
![QQ截图20230529163212](https://github.com/project-mirai/mirai-api-http/assets/63912341/c572dc41-7b4a-4063-9f6c-4cfc39e590e4)

**Comment by zipper112** [comment]
我也遇到了同样的问题

**Comment by RaphaelCS** [comment]
我也遇到了同样的问题

**Comment by ryoii** [comment]
sdk的警告，登录被风控
