### ISSUE TITLE
是否支持Image类型消息的isEmoji()判断？

### ISSUE THREAD

**Issue by Natsukage** [project-mirai/mirai-api-http#728]
Mirai本体对图片消息有[IsEmoji方法](https://github.com/mamoe/mirai/issues/1476)，判断发出的图片是否为表情，并且会体现在Mirai码中。
[mirai:image:{05DC6B34-5134-0B20-0C46-4F6D6AA44C85}.jpg, width=1024, height=1024, **size=122267, type=JPG, isEmoji=true**]
而[MAH的文档](https://docs.mirai.mamoe.net/mirai-api-http/api/MessageType.html#image)中，Image类型似乎缺失了type与isEmoji这两项内容。
导致即使直接通过MAH复读原图片，发出的图片内容在console上也会显示为
[mirai:image:{05DC6B34-5134-0B20-0C46-4F6D6AA44C85}.jpg, width=1024, height=1024, **size=0, type=UNKNOWN, isEmoji=false**]
这样的图片
在PC端，这样会导致发出的图片大小和前面的表情尺寸明显不同。想问一下MAH现在是否已经支持isEmoji的参数呢？还是说不会考虑支持？

**Comment by Bunnui** [comment]
我看了mirai-api-http 中的图片DTO，里面是有这些属性的，应该是文档没有更新

https://github.com/project-mirai/mirai-api-http/blob/5280f0dc8b2a25380a06dcac6f37aa3683b9bf90/mirai-api-http/src/main/kotlin/net/mamoe/mirai/api/http/adapter/internal/dto/message.kt#L82-L92

https://github.com/project-mirai/mirai-api-http/blob/5280f0dc8b2a25380a06dcac6f37aa3683b9bf90/mirai-api-http/src/main/kotlin/net/mamoe/mirai/api/http/adapter/internal/dto/message.kt#L104-L128

**Comment by ryoii** [comment]
确实只是文档丢字段了
