### ISSUE TITLE
如何接收消息

### ISSUE THREAD

**Issue by xx668888** [project-mirai/mirai-api-http#729]
我研究了2天，始终没有找到，我如何接收bot收到的消息，没有找到
有知道的，指导一下

**Comment by ryoii** [comment]
[基于其他语言sdk的应用](https://github.com/project-mirai/awesome-mirai#%E5%9F%BA%E4%BA%8E%E5%85%B6%E4%BB%96%E8%AF%AD%E8%A8%80sdk%E7%9A%84%E5%BA%94%E7%94%A8) 
直接使用第三方的SDK或参照一下实现，各种开发语言的都有

**Comment by xx668888** [comment]
> [基于其他语言sdk的应用](https://github.com/project-mirai/awesome-mirai#%E5%9F%BA%E4%BA%8E%E5%85%B6%E4%BB%96%E8%AF%AD%E8%A8%80sdk%E7%9A%84%E5%BA%94%E7%94%A8) 直接使用第三方的SDK或参照一下实现，各种开发语言的都有

没有开发文档吗？

**Comment by xx668888** [comment]
这个插件，怎么不主动推送？怎么还需要用别的插件 搞不懂

**Comment by xx668888** [comment]
可以用webhook 进行回调
