### ISSUE TITLE
发送好友消息 Image图片发送失败 且日志无显示

### ISSUE THREAD

**Issue by SyraTi** [project-mirai/mirai-api-http#735]
## 问题描述
使用以下结构发送至ws adapter时没有响应，日志和控制台中也没有报错提示。（setting.yml的debug选项已打开）
```json
{
  "syncId":"-1",
  "command":"sendFriendMessage",
  "subCommand":null,
  "content":{
    "sessionKey":"1pL1j3px",
    "qq":"46xxxxxxx4",
    "messageChain":[{
      "type":"Image",
      "url":"https://static.mercdn.net/c!/w=240,f=webp/thumb/photos/m34362317539_1.jpg" // 此处更换为下图demo中的链接时可以正常发送
    }]
  }
}
```
![image](https://github.com/project-mirai/mirai-api-http/assets/20638533/2b7daa4f-98a1-4983-a044-f431ecbb59b4)

## 已经尝试过的方法
1. 下载到本地使用base64选项替换url选项进行发送， 结果：所有base64都发不出去
2. 下载到本地使用path选项，用绝对路径进行发送，结果：示例图片能发送，但是目标图片依旧无法发送
3. 更换qq号，表现一致

**Comment by ryoii** [comment]
图片有可能被hash检测，敏感图片可以尝试保存本地修改一个像素后变更hash试一下

**Comment by SyraTi** [comment]
> 图片有可能被hash检测，敏感图片可以尝试保存本地修改一个像素后变更hash试一下

感谢 可以发出去了
